import type { CourseOutlineLesson } from '@/lib/course';
import type { Difficulty } from '@/lib/difficulty';

export interface CoursePreset {
  id: string;
  title: string;
  theme: string;
  level: Difficulty;
  blurb: string;
  lessons: CourseOutlineLesson[];
}

export const COURSE_PRESETS: CoursePreset[] = [
  {
    id: 'travel-cities-culture',
    title: 'Travel, Cities & Culture',
    theme: 'Travel, cities, culture, public transport, landmarks, food, and everyday city life',
    level: 'Intermediate',
    blurb: 'A broad travel course using city life, transport, food, and landmarks as the spine.',
    lessons: [
      {
        title: 'Airport Journeys',
        topic: 'airport check-in, gates, and travel announcements',
        keywords: ['airports', 'check-in', 'boarding'],
        goal: 'functional-english',
        suggestedSource: { kind: 'video', sourceType: 'travel-english', id: 'travel-airport', title: 'At the Airport' },
      },
      {
        title: 'Moving Around Cities',
        topic: 'public transport systems in large cities',
        keywords: ['public transport', 'metro', 'subway'],
        goal: 'vocabulary-building',
        suggestedSource: { kind: 'video', sourceType: 'world-flight', id: 'world-flight-tokyo-metro-economics-video', title: "Why Tokyo's Metro Is Profitable" },
      },
      {
        title: 'Asking For Directions',
        topic: 'asking for and giving directions in a city',
        keywords: ['directions', 'maps', 'routes'],
        goal: 'functional-english',
        suggestedSource: { kind: 'video', sourceType: 'travel-english', id: 'travel-directions', title: 'Asking for and Giving Directions' },
      },
      {
        title: 'Designed Cities',
        topic: 'how city design shapes daily life',
        keywords: ['city design', 'urban design', 'public spaces'],
        goal: 'critical-thinking',
        suggestedSource: { kind: 'video', sourceType: 'world-flight', id: 'world-flight-singapore-urban-design-video', title: 'Singapore - Why the City Feels So Designed' },
      },
      {
        title: 'Food Streets',
        topic: 'street food and shared food spaces',
        keywords: ['street food', 'hawker centres', 'markets'],
        goal: 'discussion-debate',
        suggestedSource: { kind: 'video', sourceType: 'world-flight', id: 'world-flight-singapore-hawker-culture-video', title: 'Singapore - Why Hawker Culture Matters' },
      },
      {
        title: 'Museums And Memory',
        topic: 'museums, landmarks, and public memory',
        keywords: ['museums', 'landmarks', 'heritage'],
        goal: 'critical-thinking',
        suggestedSource: { kind: 'video', sourceType: 'world-flight', id: 'world-flight-paris-louvre-history-video', title: 'Paris - The Louvre in 800 Years' },
      },
    ],
  },
  {
    id: 'food-around-world',
    title: 'Food Around the World',
    theme: 'World cuisine, street food, markets, restaurants, food culture, and food systems',
    level: 'Intermediate',
    blurb: 'A culture-rich food course with concrete city examples and one systems lesson.',
    lessons: [
      {
        title: 'Shared Food Spaces',
        topic: 'hawker centres as food culture and public space',
        keywords: ['hawker centres', 'food culture', 'public space'],
        goal: 'vocabulary-building',
        suggestedSource: { kind: 'video', sourceType: 'world-flight', id: 'world-flight-singapore-hawker-culture-video', title: 'Singapore - Why Hawker Culture Matters' },
      },
      {
        title: 'Street Food Stories',
        topic: 'street food and everyday city life',
        keywords: ['street food', 'vendors', 'city life'],
        goal: 'speaking-fluency',
        suggestedSource: { kind: 'video', sourceType: 'world-flight', id: 'world-flight-mexico-city-street-food-video', title: 'Mexico City - Six Street Food Finds' },
      },
      {
        title: 'Markets And Taste',
        topic: 'food markets and local taste',
        keywords: ['markets', 'food markets', 'local food'],
        goal: 'discussion-debate',
        suggestedSource: { kind: 'video', sourceType: 'world-flight', id: 'world-flight-rome-food-market-video', title: 'Rome - Food Markets and Everyday Taste' },
      },
      {
        title: 'Restaurant Language',
        topic: 'ordering food at a restaurant',
        keywords: ['restaurants', 'menus', 'ordering food'],
        goal: 'functional-english',
        suggestedSource: { kind: 'video', sourceType: 'travel-english', id: 'travel-restaurant', title: 'Ordering Food at a Restaurant' },
      },
      {
        title: 'Food And Health',
        topic: 'how food affects the gut and body',
        keywords: ['gut health', 'nutrition', 'food'],
        goal: 'critical-thinking',
        suggestedSource: { kind: 'video', sourceType: 'teded', id: 'teded_food_and_gut', title: 'How the food you eat affects your gut' },
      },
      {
        title: 'Food Waste',
        topic: 'food waste and global food systems',
        keywords: ['food waste', 'food systems', 'waste'],
        goal: 'collaboration',
        suggestedSource: { kind: 'reading', sourceType: 'voa', id: 'voa-food-waste', title: 'Food Waste Around the World' },
      },
    ],
  },
  {
    id: 'animals-nature',
    title: 'Animals & Nature',
    theme: 'Animals, wildlife, habitats, adaptations, ecosystems, conservation, and nature',
    level: 'Intermediate',
    blurb: 'A wildlife course anchored in animal behavior, ecosystems, and conservation.',
    lessons: [
      {
        title: 'Animal Migrations',
        topic: 'epic animal migrations across habitats',
        keywords: ['animal migration', 'habitats', 'wildlife'],
        goal: 'vocabulary-building',
        suggestedSource: { kind: 'video', sourceType: 'natgeo', id: 'natgeo-migration-patterns', title: 'Epic Animal Migrations' },
      },
      {
        title: 'Predators And Ecosystems',
        topic: 'how predators change ecosystems',
        keywords: ['predators', 'wolves', 'ecosystems'],
        goal: 'critical-thinking',
        suggestedSource: { kind: 'video', sourceType: 'natgeo', id: 'natgeo-wolves-change-rivers', title: 'How Wolves Change Rivers' },
      },
      {
        title: 'Animal Intelligence',
        topic: 'octopus brains and animal intelligence',
        keywords: ['octopus', 'animal intelligence', 'brains'],
        goal: 'discussion-debate',
        suggestedSource: { kind: 'video', sourceType: 'natgeo', id: 'natgeo-octopus-intelligence', title: 'Why the Octopus Brain is So Extraordinary' },
      },
      {
        title: 'Animal Memory',
        topic: 'elephant memory and social behavior',
        keywords: ['elephants', 'animal memory', 'herds'],
        goal: 'speaking-fluency',
        suggestedSource: { kind: 'video', sourceType: 'natgeo', id: 'natgeo-elephants-memory', title: 'Why Elephants Never Forget' },
      },
      {
        title: 'Ocean Habitats',
        topic: 'coral reefs and vulnerable marine ecosystems',
        keywords: ['coral reefs', 'marine ecosystems', 'conservation'],
        goal: 'critical-thinking',
        suggestedSource: { kind: 'video', sourceType: 'natgeo', id: 'natgeo-coral-reef-crisis', title: 'Conserving our Spectacular, Vulnerable Coral Reefs' },
      },
      {
        title: 'Animals And Culture',
        topic: 'animal care, breeds, and cultural value',
        keywords: ['animal care', 'sheep', 'culture'],
        goal: 'discussion-debate',
        suggestedSource: { kind: 'video', sourceType: 'world-flight', id: 'world-flight-dakar-ladoum-sheep-video', title: 'Dakar - Inside a Ladoum Sheep Championship' },
      },
    ],
  },
  {
    id: 'climate-environment',
    title: 'Climate & Environment',
    theme: 'Climate change, extreme weather, pollution, oceans, water, conservation, and city adaptation',
    level: 'Intermediate',
    blurb: 'A practical environment course that moves from science to local responses.',
    lessons: [
      {
        title: 'Climate Basics',
        topic: 'climate change and its effects',
        keywords: ['climate change', 'weather', 'environment'],
        goal: 'vocabulary-building',
        suggestedSource: { kind: 'video', sourceType: 'natgeo', id: 'natgeo-climate-change', title: 'How Climate Change Affects Us All' },
      },
      {
        title: 'Extreme Weather',
        topic: 'climate change and extreme weather',
        keywords: ['extreme weather', 'climate', 'storms'],
        goal: 'critical-thinking',
        suggestedSource: { kind: 'reading', sourceType: 'voa', id: 'voa-climate-change-weather', title: 'Climate Change and Extreme Weather' },
      },
      {
        title: 'Plastic Oceans',
        topic: 'plastic pollution in the ocean',
        keywords: ['plastic pollution', 'oceans', 'waste'],
        goal: 'discussion-debate',
        suggestedSource: { kind: 'video', sourceType: 'natgeo', id: 'natgeo-plastic-pollution', title: 'The Plastic Problem' },
      },
      {
        title: 'Water Crisis',
        topic: 'how cities respond to water shortages',
        keywords: ['water crisis', 'water scarcity', 'cities'],
        goal: 'collaboration',
        suggestedSource: { kind: 'video', sourceType: 'world-flight', id: 'world-flight-cape-town-water-crisis-video', title: 'Cape Town - Surviving the Water Crisis' },
      },
      {
        title: 'Flooded Cities',
        topic: 'flood control in growing coastal cities',
        keywords: ['flood control', 'coastal cities', 'infrastructure'],
        goal: 'critical-thinking',
        suggestedSource: { kind: 'video', sourceType: 'world-flight', id: 'world-flight-jakarta-flood-control-video', title: 'Jakarta - Ramping Up Flood Control' },
      },
      {
        title: 'Protecting Nature',
        topic: 'conservation and biodiversity loss',
        keywords: ['conservation', 'biodiversity', 'ecosystems'],
        goal: 'discussion-debate',
        suggestedSource: { kind: 'video', sourceType: 'world-flight', id: 'world-flight-panama-city-amphibian-conservation-video', title: 'Panama - Protecting Amphibians' },
      },
    ],
  },
  {
    id: 'technology-ai',
    title: 'Technology & AI',
    theme: 'Artificial intelligence, the internet, robots, digital culture, media literacy, and future work',
    level: 'Intermediate',
    blurb: 'A tech course for modern discussion, from the internet to AI and work.',
    lessons: [
      {
        title: 'AI In Daily Life',
        topic: 'artificial intelligence in everyday life',
        keywords: ['artificial intelligence', 'AI', 'daily life'],
        goal: 'vocabulary-building',
        suggestedSource: { kind: 'reading', sourceType: 'voa', id: 'voa-artificial-intelligence-daily-life', title: 'Artificial Intelligence in Everyday Life' },
      },
      {
        title: 'Robots And Work',
        topic: 'robots and the future of work',
        keywords: ['robots', 'future of work', 'automation'],
        goal: 'discussion-debate',
        suggestedSource: { kind: 'reading', sourceType: 'voa', id: 'voa-robots-future-of-work', title: 'Robots and the Future of Work' },
      },
      {
        title: 'The Internet Story',
        topic: 'the history of the internet',
        keywords: ['internet', 'technology history', 'web'],
        goal: 'critical-thinking',
        suggestedSource: { kind: 'video', sourceType: 'internet-memes', id: 'memes-history', title: 'A Brief History of the Internet' },
      },
      {
        title: 'Digital Divide',
        topic: 'access to technology and the digital divide',
        keywords: ['digital divide', 'technology access', 'inequality'],
        goal: 'collaboration',
        suggestedSource: { kind: 'reading', sourceType: 'voa', id: 'voa-digital-divide', title: 'The Digital Divide' },
      },
      {
        title: 'Media Literacy',
        topic: 'how to evaluate media and information',
        keywords: ['media literacy', 'misinformation', 'fake news'],
        goal: 'critical-thinking',
        suggestedSource: { kind: 'video', sourceType: 'crash-course', id: 'cc-media-literacy', title: 'Introduction to Media Literacy: Crash Course Media Literacy #1' },
      },
      {
        title: 'Good Ideas',
        topic: 'where innovation and good ideas come from',
        keywords: ['innovation', 'ideas', 'creativity'],
        goal: 'creativity',
        suggestedSource: { kind: 'video', sourceType: 'ted', id: 'steven_johnson_where_good_ideas_come', title: 'Where Good Ideas Come From' },
      },
    ],
  },
  {
    id: 'job-interview-english',
    title: 'Job Interview English',
    theme: 'Job interviews, resumes, professional answers, interview questions, confidence, and follow-up emails',
    level: 'Intermediate',
    blurb: 'A practical business-English course for interview preparation and follow-up.',
    lessons: [
      {
        title: 'Interview Basics',
        topic: 'common job interview questions and answers',
        keywords: ['job interviews', 'interview questions', 'answers'],
        goal: 'vocabulary-building',
        suggestedSource: { kind: 'video', sourceType: 'business-english', id: 'business-interview-prepare-bbc', title: 'How to Prepare for an Interview' },
      },
      {
        title: 'Strong Answers',
        topic: 'structuring interview answers with examples',
        keywords: ['interview answers', 'STAR method', 'examples'],
        goal: 'speaking-fluency',
        suggestedSource: { kind: 'video', sourceType: 'business-english', id: 'business-interview-answering-bbc', title: 'Answering Interview Questions' },
      },
      {
        title: 'Competency Questions',
        topic: 'answering competency-based interview questions',
        keywords: ['competency questions', 'STAR method', 'workplace examples'],
        goal: 'confidence-building',
        suggestedSource: { kind: 'video', sourceType: 'business-english', id: 'business-interview-competency-british-council', title: 'Responding to Competency Questions' },
      },
      {
        title: 'Smart Questions',
        topic: 'questions to ask an interviewer',
        keywords: ['interviewer questions', 'job interviews', 'questions'],
        goal: 'discussion-debate',
        suggestedSource: { kind: 'video', sourceType: 'business-english', id: 'business-interviews', title: 'Job Interview English' },
      },
      {
        title: 'Professional Emails',
        topic: 'writing follow-up and thank-you emails',
        keywords: ['professional emails', 'follow-up emails', 'thank-you notes'],
        goal: 'functional-english',
        suggestedSource: { kind: 'video', sourceType: 'business-english', id: 'business-emails', title: 'Writing Professional Emails in English' },
      },
      {
        title: 'Networking Next Steps',
        topic: 'networking after an interview',
        keywords: ['networking', 'professional communication', 'career'],
        goal: 'speaking-fluency',
        suggestedSource: { kind: 'video', sourceType: 'business-english', id: 'business-networking', title: 'Networking in English' },
      },
    ],
  },
  {
    id: 'health-wellbeing',
    title: 'Health & Wellbeing',
    theme: 'Health, sleep, stress, exercise, food, happiness, and wellbeing',
    level: 'Intermediate',
    blurb: 'A balanced health course that supports vocabulary, advice, and discussion.',
    lessons: [
      {
        title: 'Sleep Matters',
        topic: 'sleep and what happens without enough sleep',
        keywords: ['sleep', 'health', 'brain'],
        goal: 'vocabulary-building',
        suggestedSource: { kind: 'video', sourceType: 'teded', id: 'teded_what_if_you_didnt_sleep', title: "What would happen if you didn't sleep?" },
      },
      {
        title: 'Managing Stress',
        topic: 'how stress affects the brain and body',
        keywords: ['stress', 'brain', 'wellbeing'],
        goal: 'critical-thinking',
        suggestedSource: { kind: 'video', sourceType: 'teded', id: 'teded_how_stress_affects_brain', title: 'How stress affects your brain' },
      },
      {
        title: 'Exercise Benefits',
        topic: 'the health benefits of exercise',
        keywords: ['exercise', 'fitness', 'health'],
        goal: 'speaking-fluency',
        suggestedSource: { kind: 'reading', sourceType: 'voa', id: 'voa-benefits-of-exercise', title: 'The Benefits of Exercise' },
      },
      {
        title: 'Sugar And Health',
        topic: 'how sugar affects the brain and body',
        keywords: ['sugar', 'brain', 'nutrition'],
        goal: 'discussion-debate',
        suggestedSource: { kind: 'video', sourceType: 'teded', id: 'teded_how_sugar_affects_brain', title: 'How sugar affects the brain' },
      },
      {
        title: 'Food And Gut',
        topic: 'food choices and gut health',
        keywords: ['gut health', 'food', 'nutrition'],
        goal: 'critical-thinking',
        suggestedSource: { kind: 'video', sourceType: 'teded', id: 'teded_food_and_gut', title: 'How the food you eat affects your gut' },
      },
      {
        title: 'Happiness Science',
        topic: 'the science of happiness and wellbeing',
        keywords: ['happiness', 'wellbeing', 'psychology'],
        goal: 'discussion-debate',
        suggestedSource: { kind: 'reading', sourceType: 'voa', id: 'voa-science-of-happiness', title: 'The Science of Happiness' },
      },
    ],
  },
  {
    id: 'stories-myths-folktales',
    title: 'Stories, Myths & Folktales',
    theme: 'Stories, myths, folktales, fables, heroes, storytelling, and culture',
    level: 'Intermediate',
    blurb: 'A story course for narrative language, interpretation, and creative retelling.',
    lessons: [
      {
        title: 'Why Stories Work',
        topic: 'how stories shape our minds',
        keywords: ['storytelling', 'psychology', 'narratives'],
        goal: 'critical-thinking',
        suggestedSource: { kind: 'video', sourceType: 'bbc-ideas', id: 'bbcideas_science_of_storytelling', title: 'How Stories Shape Our Minds' },
      },
      {
        title: 'Single Stories',
        topic: 'stereotypes and the danger of a single story',
        keywords: ['stories', 'stereotypes', 'culture'],
        goal: 'discussion-debate',
        suggestedSource: { kind: 'video', sourceType: 'ted', id: 'chimamanda_adichie_danger_single_story', title: 'The Danger of a Single Story' },
      },
      {
        title: 'Hero Patterns',
        topic: 'what makes a hero in stories',
        keywords: ['heroes', 'myths', 'story structure'],
        goal: 'vocabulary-building',
        suggestedSource: { kind: 'video', sourceType: 'teded', id: 'teded_what_makes_a_hero', title: 'What makes a hero?' },
      },
      {
        title: 'Fables And Morals',
        topic: 'fables, morals, and animal characters',
        keywords: ['fables', 'morals', 'animals'],
        goal: 'speaking-fluency',
        suggestedSource: { kind: 'reading', sourceType: 'stories', id: 'stories-tortoise-hare', title: 'The Tortoise and the Hare' },
      },
      {
        title: 'Fairy Tale Choices',
        topic: 'trust, danger, and choices in fairy tales',
        keywords: ['fairy tales', 'trust', 'danger'],
        goal: 'critical-thinking',
        suggestedSource: { kind: 'reading', sourceType: 'stories', id: 'stories-red-riding-hood', title: 'Little Red Riding Hood' },
      },
      {
        title: 'Retell The Tale',
        topic: 'creative retelling of a traditional story',
        keywords: ['retelling', 'creativity', 'folktales'],
        goal: 'creativity',
        suggestedSource: { kind: 'reading', sourceType: 'stories', id: 'stories-emperor-new-clothes', title: "The Emperor's New Clothes" },
      },
    ],
  },
];

export function getCoursePreset(id: string): CoursePreset | null {
  return COURSE_PRESETS.find((preset) => preset.id === id) ?? null;
}
