export interface DestinationFactSource {
  name: string;
  url: string;
}

export interface DestinationPopulationFact extends DestinationFactSource {
  label: 'City population' | 'Metro population' | 'City-state population';
  value: string;
  year: string;
}

export interface DestinationFactSheet {
  population?: DestinationPopulationFact;
  language?: string;
  currency?: string;
  timeZone?: string;
  foodCulture?: string[];
  knownFor?: string[];
  prompt?: string;
  sources?: DestinationFactSource[];
}

export const COUNTRY_LANGUAGE_HINTS: Record<string, string> = {
  Argentina: 'Spanish',
  Australia: 'English',
  Brazil: 'Portuguese',
  Canada: 'English and French',
  Chile: 'Spanish',
  China: 'Mandarin Chinese, Cantonese, and regional languages',
  Colombia: 'Spanish',
  Egypt: 'Arabic',
  Ethiopia: 'Amharic, Oromo, Tigrinya, English, and other languages',
  Fiji: 'English, Fijian, and Fiji Hindi',
  France: 'French',
  Germany: 'German',
  Iceland: 'Icelandic',
  India: 'Hindi, English, and many regional languages',
  Indonesia: 'Indonesian',
  Ireland: 'English and Irish',
  Italy: 'Italian',
  Japan: 'Japanese',
  Kazakhstan: 'Kazakh and Russian',
  Kenya: 'Swahili and English',
  Mexico: 'Spanish',
  Mongolia: 'Mongolian',
  Netherlands: 'Dutch',
  'New Zealand': 'English and Maori',
  Nigeria: 'English, Yoruba, Igbo, Hausa, and other languages',
  Panama: 'Spanish',
  Peru: 'Spanish, Quechua, Aymara, and other languages',
  Philippines: 'Filipino, English, and regional languages',
  Portugal: 'Portuguese',
  Russia: 'Russian',
  Senegal: 'French, Wolof, and other languages',
  Singapore: 'English, Malay, Mandarin, and Tamil',
  'South Africa': 'English, Afrikaans, Zulu, Xhosa, and other languages',
  'South Korea': 'Korean',
  Spain: 'Spanish',
  Thailand: 'Thai',
  Turkey: 'Turkish',
  'United Arab Emirates': 'Arabic, English, and many community languages',
  'United Kingdom': 'English',
  'United States': 'English, Spanish, and many community languages',
  Vietnam: 'Vietnamese',
};

export const DESTINATION_FACTS: Record<string, DestinationFactSheet> = {
  'rio-de-janeiro': {
    population: {
      label: 'City population',
      value: '6.77M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/brazil/rio-de-janeiro',
    },
    language: 'Portuguese',
    currency: 'Brazilian real (BRL)',
    timeZone: 'Brasilia Time (UTC-3)',
    foodCulture: ['Feijoada', 'Churrasco', 'Acai bowls', 'Beach snacks', 'Samba'],
    knownFor: ['Mountains meeting the ocean', 'Samba and Carnival', 'Tijuca Forest', 'Beach public life'],
    prompt: 'What parts of Rio feel natural, and what parts feel built by people?',
  },
  'panama-city': {
    population: {
      label: 'Metro population',
      value: '2.09M',
      year: '2026 estimate',
      name: 'Macrotrends',
      url: 'https://www.macrotrends.net/global-metrics/cities/22063/panama-city/population',
    },
    language: 'Spanish',
    currency: 'Panamanian balboa (PAB) and U.S. dollar (USD)',
    timeZone: 'Eastern Standard Time (UTC-5)',
    foodCulture: ['Sancocho', 'Seafood', 'Plantains', 'Canal history', 'Afro-Panamanian culture'],
    knownFor: ['Panama Canal', 'Casco Viejo', 'Trade routes', 'Afro-Panamanian culture'],
    prompt: 'How can one city connect local neighborhoods with global movement?',
  },
  bangkok: {
    population: {
      label: 'City population',
      value: '5.19M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/thailand/bangkok',
    },
    language: 'Thai',
    currency: 'Thai baht (THB)',
    timeZone: 'Indochina Time (UTC+7)',
    foodCulture: ['Street food', 'Noodle dishes', 'River markets', 'Buddhist temples', 'Night markets'],
    knownFor: ['Street food', 'Chao Phraya River', 'Temples', 'Dense urban movement'],
    prompt: 'How does Bangkok mix daily routines, religion, food, and transport in one city?',
  },
  tokyo: {
    population: {
      label: 'City population',
      value: '10.32M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/japan/tokyo',
    },
    language: 'Japanese',
    currency: 'Japanese yen (JPY)',
    timeZone: 'Japan Standard Time (UTC+9)',
    foodCulture: ['Ramen', 'Sushi', 'Convenience stores', 'Public baths', 'Railway stations'],
    knownFor: ['Dense transit', 'Neighborhood routines', 'Public baths', 'Old and new streets'],
    prompt: 'What daily systems help a very large city feel organized?',
  },
  london: {
    population: {
      label: 'City population',
      value: '9.19M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/united-kingdom/london',
    },
    language: 'English',
    currency: 'Pound sterling (GBP)',
    timeZone: 'GMT / British Summer Time',
    foodCulture: ['Fish and chips', 'South Asian food', 'Markets', 'Museums', 'River history'],
    knownFor: ['River Thames', 'Global finance', 'Museums', 'Multicultural neighborhoods'],
    prompt: 'What makes London feel both historic and global?',
  },
  paris: {
    population: {
      label: 'City population',
      value: '2.06M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/france/paris',
    },
    language: 'French',
    currency: 'Euro (EUR)',
    timeZone: 'Central European Time / Summer Time',
    foodCulture: ['Bakeries', 'Cafes', 'Cheese', 'Fashion', 'Museums'],
    knownFor: ['Seine River', 'Art museums', 'Fashion', 'Historic public spaces'],
    prompt: 'How does Paris use food, design, and public space to shape its identity?',
  },
  delhi: {
    population: {
      label: 'City population',
      value: '23.39M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/india/delhi',
    },
    language: 'Hindi, English, and many regional languages',
    currency: 'Indian rupee (INR)',
    timeZone: 'India Standard Time (UTC+5:30)',
    foodCulture: ['Street food', 'Chaat', 'Markets', 'Historic layers', 'Multilingual public life'],
    knownFor: ['Markets', 'Food variety', 'Multilingual public life', 'Historic layers'],
    prompt: 'What clues show that Delhi is shaped by many regions and languages?',
  },
  'new-york': {
    population: {
      label: 'City population',
      value: '8.55M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/us-cities/new-york/new-york',
    },
    language: 'English, Spanish, and many community languages',
    currency: 'U.S. dollar (USD)',
    timeZone: 'Eastern Time',
    foodCulture: ['Pizza', 'Bagels', 'Food carts', 'Broadway', 'Immigrant neighborhoods'],
    knownFor: ['Skyscrapers', 'Subway life', 'Immigration history', 'Media and finance'],
    prompt: 'How do many communities make one city feel like several cities at once?',
  },
  cairo: {
    population: {
      label: 'Metro population',
      value: '23.54M',
      year: '2026 estimate',
      name: 'Macrotrends',
      url: 'https://www.macrotrends.net/global-metrics/cities/22812/cairo/population',
    },
    language: 'Arabic',
    currency: 'Egyptian pound (EGP)',
    timeZone: 'Eastern European Time (UTC+2; UTC+3 during DST)',
    foodCulture: ['Koshari', 'Ful medames', 'Nile life', 'Markets', 'Ancient monuments'],
    knownFor: ['Nile River', 'Ancient monuments', 'Desert edge', 'Historic capital life'],
    prompt: 'How does the past stay visible inside a modern city?',
  },
  singapore: {
    population: {
      label: 'City-state population',
      value: '6.11M',
      year: 'June 2025',
      name: 'Singapore National Population and Talent Division',
      url: 'https://www.population.gov.sg/our-population/population-trends/overall-population/',
    },
    language: 'English, Malay, Mandarin, and Tamil',
    currency: 'Singapore dollar (SGD)',
    timeZone: 'Singapore Time (UTC+8)',
    foodCulture: ['Hawker centres', 'Chicken rice', 'Laksa', 'Multilingual classrooms', 'Port trade'],
    knownFor: ['Hawker food', 'Multilingual classrooms', 'Port trade', 'Garden city design'],
    prompt: 'How can a small city-state feel connected to many cultures at once?',
  },
  amsterdam: {
    population: {
      label: 'Metro population',
      value: '1.20M',
      year: '2026 estimate',
      name: 'Macrotrends',
      url: 'https://www.macrotrends.net/global-metrics/cities/21930/amsterdam/population',
    },
    language: 'Dutch',
    currency: 'Euro (EUR)',
    timeZone: 'Central European Time / Summer Time',
    foodCulture: ['Cheese', 'Stroopwafels', 'Canal cafes', 'Cycling culture'],
    knownFor: ['Canals', 'Water management', 'Cycling culture', 'Historic streets'],
    prompt: 'When is water beautiful, and when is it infrastructure?',
  },
  nairobi: {
    population: {
      label: 'Metro population',
      value: '6.00M',
      year: '2026 estimate',
      name: 'Macrotrends',
      url: 'https://www.macrotrends.net/global-metrics/cities/21711/nairobi/population',
    },
    language: 'Swahili and English',
    currency: 'Kenyan shilling (KES)',
    timeZone: 'East Africa Time (UTC+3)',
    foodCulture: ['Nyama choma', 'Tea', 'Matatu art', 'Market food'],
    knownFor: ['Matatu culture', 'Urban wildlife edge', 'Regional business', 'Visual transport language'],
    prompt: 'How can transport become part of a city culture?',
  },
  dakar: {
    population: {
      label: 'Metro population',
      value: '3.78M',
      year: '2026 estimate',
      name: 'Macrotrends',
      url: 'https://www.macrotrends.net/global-metrics/cities/22439/dakar/population',
    },
    language: 'French, Wolof, and other languages',
    currency: 'West African CFA franc (XOF)',
    timeZone: 'Greenwich Mean Time (UTC+0)',
    foodCulture: ['Thieboudienne', 'Music', 'Markets', 'Coastal food'],
    knownFor: ['Wolof language', 'Coastal location', 'Music and media', 'West African crossroads'],
    prompt: 'How does multilingual life shape what people hear and see in a city?',
  },
  'addis-ababa': {
    population: {
      label: 'City population',
      value: '4.23M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/ethiopia/addis-ababa',
    },
    language: 'Amharic, Oromo, Tigrinya, English, and other languages',
    currency: 'Ethiopian birr (ETB)',
    timeZone: 'East Africa Time (UTC+3)',
    foodCulture: ['Injera', 'Coffee ceremony', 'Scripts and languages', 'Diplomacy'],
    knownFor: ['African Union diplomacy', 'Scripts and languages', 'Highland capital', 'Coffee culture'],
    prompt: 'How can one capital represent many languages and identities?',
  },
  miami: {
    population: {
      label: 'Metro population',
      value: '6.43M',
      year: '2026 estimate',
      name: 'Macrotrends',
      url: 'https://www.macrotrends.net/global-metrics/cities/23064/miami/population',
    },
    language: 'English, Spanish, Haitian Creole, and many community languages',
    currency: 'U.S. dollar (USD)',
    timeZone: 'Eastern Time',
    foodCulture: ['Cuban food', 'Caribbean music', 'Bilingual media', 'Coastal life'],
    knownFor: ['Caribbean and Latin American migration', 'Bilingual life', 'Coastal risk', 'Music and media'],
    prompt: 'How does migration change the sound and feel of a city?',
  },
  istanbul: {
    population: {
      label: 'City population',
      value: '15.79M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/turkey/istanbul',
    },
    language: 'Turkish',
    currency: 'Turkish lira (TRY)',
    timeZone: 'Turkey Time (UTC+3)',
    foodCulture: ['Tea', 'Street simit', 'Markets', 'Historic food routes'],
    knownFor: ['Europe-Asia crossing', 'Historic peninsula', 'Earthquake readiness', 'Layered architecture'],
    prompt: 'What changes when a city is both a bridge and a risk zone?',
  },
  ulaanbaatar: {
    population: {
      label: 'Metro population',
      value: '1.68M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/countries/mongolia',
    },
    language: 'Mongolian',
    currency: 'Mongolian togrog (MNT)',
    timeZone: 'Ulaanbaatar Time (UTC+8)',
    foodCulture: ['Dairy foods', 'Meat dishes', 'Ger districts', 'Winter routines'],
    knownFor: ['Extreme winter systems', 'Ger districts', 'Mountain valley setting', 'Mongolian capital life'],
    prompt: 'What does a city need to keep working through a very cold winter?',
  },
  sydney: {
    population: {
      label: 'Metro population',
      value: '5.31M',
      year: '2026 estimate',
      name: 'Macrotrends',
      url: 'https://www.macrotrends.net/global-metrics/cities/206167/sydney/population',
    },
    language: 'English and many community languages',
    currency: 'Australian dollar (AUD)',
    timeZone: 'Australian Eastern Time',
    foodCulture: ['Seafood', 'Coffee culture', 'Beach routines', 'Ferry commuting', 'Multicultural food'],
    knownFor: ['Sydney Harbour', 'Opera House', 'Coastal public life', 'Ferries and bridges'],
    prompt: 'How does Sydney use water as both scenery and transportation?',
  },
  'cape-town': {
    population: {
      label: 'Metro population',
      value: '5.23M',
      year: '2026 estimate',
      name: 'Macrotrends',
      url: 'https://www.macrotrends.net/global-metrics/cities/22486/cape-town/population',
    },
    language: 'English, Afrikaans, Xhosa, and other languages',
    currency: 'South African rand (ZAR)',
    timeZone: 'South Africa Standard Time (UTC+2)',
    foodCulture: ['Cape Malay food', 'Braai', 'Seafood', 'Township culture', 'Wine region links'],
    knownFor: ['Table Mountain', 'Coastal neighborhoods', 'Robben Island history', 'Multilingual public life'],
    prompt: 'How do mountain, ocean, and history shape Cape Town at the same time?',
  },
  rome: {
    population: {
      label: 'City population',
      value: '4.35M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/world-cities/rome-population',
    },
    language: 'Italian',
    currency: 'Euro (EUR)',
    timeZone: 'Central European Time / Summer Time',
    foodCulture: ['Pasta dishes', 'Pizza al taglio', 'Public fountains', 'Ancient ruins', 'Piazza life'],
    knownFor: ['Ancient Rome', 'Public squares', 'Churches and ruins', 'Food traditions'],
    prompt: 'How does Rome make ancient history part of everyday streets?',
  },
  'mexico-city': {
    population: {
      label: 'Metro population',
      value: '22.75M',
      year: '2026 estimate',
      name: 'Macrotrends',
      url: 'https://www.macrotrends.net/global-metrics/cities/21849/mexico-city/population',
    },
    language: 'Spanish and many Indigenous languages',
    currency: 'Mexican peso (MXN)',
    timeZone: 'Central Time',
    foodCulture: ['Tacos', 'Tamales', 'Markets', 'Street food', 'Mural art'],
    knownFor: ['High valley city', 'Zocalo', 'Ancient and colonial layers', 'Street food'],
    prompt: 'What clues show Mexico City was built in layers over time?',
  },
  dubai: {
    population: {
      label: 'City population',
      value: '3.79M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/united-arab-emirates/dubai',
    },
    language: 'Arabic, English, Hindi, Urdu, Tagalog, and many community languages',
    currency: 'UAE dirham (AED)',
    timeZone: 'Gulf Standard Time (UTC+4)',
    foodCulture: ['Emirati food', 'South Asian food', 'Spice souks', 'Malls', 'Creek trade'],
    knownFor: ['Burj Khalifa', 'Dubai Creek', 'Global migration', 'Desert-to-skyline growth'],
    prompt: 'How can a city grow quickly while still showing older trade routes?',
  },
  seoul: {
    population: {
      label: 'City population',
      value: '9.21M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/south-korea/seoul',
    },
    language: 'Korean',
    currency: 'South Korean won (KRW)',
    timeZone: 'Korea Standard Time (UTC+9)',
    foodCulture: ['Kimchi', 'Street snacks', 'K-pop districts', 'Palace tourism', 'Cafe culture'],
    knownFor: ['Dense transit', 'Palaces and towers', 'Technology culture', 'Night markets'],
    prompt: 'How does Seoul combine fast technology with older cultural spaces?',
  },
  'hong-kong': {
    population: {
      label: 'City-state population',
      value: '7.43M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/china/hong-kong',
    },
    language: 'Cantonese, English, Mandarin, and other community languages',
    currency: 'Hong Kong dollar (HKD)',
    timeZone: 'Hong Kong Time (UTC+8)',
    foodCulture: ['Dim sum', 'Cha chaan teng', 'Street markets', 'Ferries', 'High-rise housing'],
    knownFor: ['Victoria Harbour', 'Dense skyline', 'Ferries and trams', 'Cantonese food culture'],
    prompt: 'How does Hong Kong fit mountains, water, and dense city life into a small area?',
  },
  madrid: {
    population: {
      label: 'City population',
      value: '3.34M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/spain/madrid',
    },
    language: 'Spanish',
    currency: 'Euro (EUR)',
    timeZone: 'Central European Time / Summer Time',
    foodCulture: ['Tapas', 'Churros', 'Public squares', 'Art museums', 'Late evening routines'],
    knownFor: ['Plaza Mayor', 'Royal Palace', 'Art museums', 'Central Spanish capital life'],
    prompt: 'How do public squares help people share city life?',
  },
  lisbon: {
    population: {
      label: 'Metro population',
      value: '3.09M',
      year: '2026 estimate',
      name: 'Macrotrends',
      url: 'https://www.macrotrends.net/global-metrics/cities/22167/lisbon/population',
    },
    language: 'Portuguese',
    currency: 'Euro (EUR)',
    timeZone: 'Western European Time / Summer Time',
    foodCulture: ['Pastel de nata', 'Seafood', 'Fado music', 'Tram streets', 'Tile facades'],
    knownFor: ['Tagus River', 'Hills and trams', 'Maritime history', 'Tile architecture'],
    prompt: 'How do hills, river routes, and music shape Lisbon identity?',
  },
  vancouver: {
    population: {
      label: 'Metro population',
      value: '2.70M',
      year: '2026 estimate',
      name: 'Macrotrends',
      url: 'https://www.macrotrends.net/global-metrics/cities/20404/vancouver/population',
    },
    language: 'English, Punjabi, Chinese languages, and many community languages',
    currency: 'Canadian dollar (CAD)',
    timeZone: 'Pacific Time',
    foodCulture: ['Sushi', 'Seafood', 'Food trucks', 'Indigenous culture', 'Outdoor routines'],
    knownFor: ['Mountains and water', 'Stanley Park', 'Port city life', 'Multicultural neighborhoods'],
    prompt: 'How does Vancouver connect city life with mountains, ocean, and forests?',
  },
  beijing: {
    population: {
      label: 'City population',
      value: '21.57M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/china/beijing',
    },
    language: 'Mandarin Chinese and many regional languages',
    currency: 'Chinese yuan (CNY)',
    timeZone: 'China Standard Time (UTC+8)',
    foodCulture: ['Peking duck', 'Tea culture', 'Hutong snacks', 'Imperial gardens', 'Street markets'],
    knownFor: ['Forbidden City', 'Temple of Heaven', 'Hutong neighborhoods', 'Capital city power'],
    prompt: 'How does Beijing show older imperial space inside a fast modern capital?',
  },
  berlin: {
    population: {
      label: 'City population',
      value: '3.78M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/germany/berlin',
    },
    language: 'German and many community languages',
    currency: 'Euro (EUR)',
    timeZone: 'Central European Time / Summer Time',
    foodCulture: ['Currywurst', 'Bread culture', 'Street art', 'Museums', 'Public transit life'],
    knownFor: ['Berlin Wall memory', 'Brandenburg Gate', 'Museum Island', 'Creative neighborhoods'],
    prompt: 'How can a city remember division while building shared public life?',
  },
  moscow: {
    population: {
      label: 'City population',
      value: '13.40M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/russia/moscow',
    },
    language: 'Russian',
    currency: 'Russian ruble (RUB)',
    timeZone: 'Moscow Time (UTC+3)',
    foodCulture: ['Borscht', 'Blini', 'Tea culture', 'Metro station art', 'Winter public life'],
    knownFor: ['Red Square', 'Saint Basil Cathedral', 'Moscow Metro', 'River capital geography'],
    prompt: 'How does Moscow use buildings and transport to communicate power and pride?',
  },
  toronto: {
    population: {
      label: 'City population',
      value: '3.36M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/canada/toronto',
    },
    language: 'English and many community languages',
    currency: 'Canadian dollar (CAD)',
    timeZone: 'Eastern Time',
    foodCulture: ['Multicultural food', 'Caribbean festivals', 'South Asian neighborhoods', 'Streetcars', 'Lakefront life'],
    knownFor: ['CN Tower', 'Lake Ontario', 'Streetcar network', 'Migration and media'],
    prompt: 'How does Toronto turn many languages and communities into one city identity?',
  },
  mumbai: {
    population: {
      label: 'City population',
      value: '21.78M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/india/mumbai',
    },
    language: 'Marathi, Hindi, English, and many community languages',
    currency: 'Indian rupee (INR)',
    timeZone: 'India Standard Time (UTC+5:30)',
    foodCulture: ['Vada pav', 'Street snacks', 'Bollywood culture', 'Local trains', 'Seafront routines'],
    knownFor: ['Gateway of India', 'Marine Drive', 'Chhatrapati Shivaji Terminus', 'Dense rail movement'],
    prompt: 'How does Mumbai keep moving when so many people share limited space?',
  },
  'buenos-aires': {
    population: {
      label: 'City population',
      value: '3.17M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/argentina/buenos-aires',
    },
    language: 'Spanish',
    currency: 'Argentine peso (ARS)',
    timeZone: 'Argentina Time (UTC-3)',
    foodCulture: ['Asado', 'Empanadas', 'Tango', 'Cafe culture', 'Football neighborhoods'],
    knownFor: ['Obelisco', 'La Boca and Caminito', 'Casa Rosada', 'Broad avenues'],
    prompt: 'How do music, football, and public squares shape Buenos Aires identity?',
  },
  'los-angeles': {
    population: {
      label: 'Metro population',
      value: '12.77M',
      year: '2026 estimate',
      name: 'Macrotrends',
      url: 'https://www.macrotrends.net/global-metrics/cities/23052/los-angeles/population',
    },
    language: 'English, Spanish, Korean, Tagalog, and many community languages',
    currency: 'U.S. dollar (USD)',
    timeZone: 'Pacific Time',
    foodCulture: ['Film and television work', 'Tacos', 'Korean food', 'Car culture', 'Beach routines'],
    knownFor: ['Hollywood Sign', 'Griffith Observatory', 'Freeways', 'Pacific coast'],
    prompt: 'How does Los Angeles connect image-making, migration, and movement across a huge area?',
  },
  jakarta: {
    population: {
      label: 'City population',
      value: '12.55M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/indonesia/jakarta',
    },
    language: 'Indonesian and many regional languages',
    currency: 'Indonesian rupiah (IDR)',
    timeZone: 'Western Indonesia Time (UTC+7)',
    foodCulture: ['Nasi goreng', 'Street food', 'Markets', 'Mosque and civic spaces', 'Traffic routines'],
    knownFor: ['National Monument', 'Kota Tua', 'Megacity growth', 'Flood and coastal planning'],
    prompt: 'What does Jakarta need to balance history, traffic, water, and rapid growth?',
  },
  lagos: {
    population: {
      label: 'City population',
      value: '14.88M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/nigeria/lagos',
    },
    language: 'English, Yoruba, Nigerian Pidgin, and many community languages',
    currency: 'Nigerian naira (NGN)',
    timeZone: 'West Africa Time (UTC+1)',
    foodCulture: ['Jollof rice', 'Markets', 'Afrobeats', 'Nollywood', 'Lagoon transport'],
    knownFor: ['Lagoon city setting', 'Lekki-Ikoyi bridge', 'Music and media', 'Busy markets'],
    prompt: 'How does Lagos turn speed, trade, music, and water into city energy?',
  },
  honolulu: {
    population: {
      label: 'Metro population',
      value: '936K',
      year: '2026 estimate',
      name: 'Macrotrends',
      url: 'https://www.macrotrends.net/global-metrics/cities/23013/honolulu/population',
    },
    language: 'English, Hawaiian, and many Pacific and Asian languages',
    currency: 'U.S. dollar (USD)',
    timeZone: 'Hawaii-Aleutian Time',
    foodCulture: ['Plate lunch', 'Surf culture', 'Lei traditions', 'Hula', 'Pacific and Asian foodways'],
    knownFor: ['Waikiki', 'Diamond Head', 'Pacific port history', 'Native Hawaiian culture'],
    prompt: 'How does Honolulu balance tourism with local culture and island geography?',
  },
  bogota: {
    population: {
      label: 'City population',
      value: '7.95M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/colombia/bogota',
    },
    language: 'Spanish',
    currency: 'Colombian peso (COP)',
    timeZone: 'Colombia Time (UTC-5)',
    foodCulture: ['Ajiaco', 'Arepas', 'Coffee culture', 'Cycling culture', 'Bus rapid transit'],
    knownFor: ['Andean capital setting', 'Monserrate', 'Plaza Bolivar', 'TransMilenio'],
    prompt: 'How does high elevation change the way Bogota moves and gathers?',
  },
  reykjavik: {
    population: {
      label: 'City population',
      value: '249K',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/iceland/reykjavik',
    },
    language: 'Icelandic and English',
    currency: 'Icelandic krona (ISK)',
    timeZone: 'Greenwich Mean Time (UTC+0)',
    foodCulture: ['Seafood', 'Geothermal pools', 'Sagas', 'Music culture', 'Compact streets'],
    knownFor: ['Hallgrimskirkja', 'Harpa concert hall', 'Geothermal energy', 'North Atlantic setting'],
    prompt: 'How does Reykjavik use heat, light, and compact design in a northern city?',
  },
  lima: {
    population: {
      label: 'City population',
      value: '12.00M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/peru/lima',
    },
    language: 'Spanish, Quechua, Aymara, and other community languages',
    currency: 'Peruvian sol (PEN)',
    timeZone: 'Peru Time (UTC-5)',
    foodCulture: ['Ceviche', 'Markets', 'Coastal cliffs', 'Ancient ruins', 'Fusion cuisine'],
    knownFor: ['Pacific coast', 'Plaza Mayor', 'Huaca Pucllana', 'Food culture'],
    prompt: 'How does Lima show ancient, colonial, and modern layers near the ocean?',
  },
  perth: {
    population: {
      label: 'City population',
      value: '2.22M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/australia/perth',
    },
    language: 'English and many community languages',
    currency: 'Australian dollar (AUD)',
    timeZone: 'Australian Western Standard Time (UTC+8)',
    foodCulture: ['Seafood', 'Coffee culture', 'Beach routines', 'Outdoor parks', 'Swan River life'],
    knownFor: ['Indian Ocean coast', 'Kings Park', 'Elizabeth Quay', 'Remote capital city setting'],
    prompt: 'How does Perth feel connected to nature while sitting far from other big cities?',
  },
  auckland: {
    population: {
      label: 'City population',
      value: '1.54M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/new-zealand/auckland',
    },
    language: 'English, Maori, Pacific languages, and many community languages',
    currency: 'New Zealand dollar (NZD)',
    timeZone: 'New Zealand Time',
    foodCulture: ['Seafood', 'Pacific foodways', 'Cafe culture', 'Sailing', 'Volcano walks'],
    knownFor: ['Sky Tower', 'Harbors', 'Volcanic cones', 'Maori and Pacific culture'],
    prompt: 'How do harbors and volcanoes shape Auckland daily life?',
  },
  suva: {
    population: {
      label: 'City population',
      value: '102K',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/fiji/suva',
    },
    language: 'English, iTaukei, Fiji Hindi, and other community languages',
    currency: 'Fijian dollar (FJD)',
    timeZone: 'Fiji Time (UTC+12)',
    foodCulture: ['Cassava', 'Seafood', 'Kava gatherings', 'Municipal markets', 'Pacific island routines'],
    knownFor: ['Fiji capital', 'Suva Harbor', 'Fiji Museum', 'Pacific diplomacy'],
    prompt: 'How does Suva connect island life, government, markets, and the wider Pacific?',
  },
  almaty: {
    population: {
      label: 'City population',
      value: '2.19M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/kazakhstan/almaty',
    },
    language: 'Kazakh, Russian, and other community languages',
    currency: 'Kazakhstani tenge (KZT)',
    timeZone: 'Almaty Time (UTC+5)',
    foodCulture: ['Apples', 'Tea culture', 'Bazaar foods', 'Mountain recreation', 'Soviet-era streets'],
    knownFor: ['Tian Shan mountains', 'Zenkov Cathedral', 'Kok Tobe', 'Green Bazaar'],
    prompt: 'How do mountains change the way Almaty looks, moves, and spends free time?',
  },
  dublin: {
    population: {
      label: 'City population',
      value: '1.33M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/ireland/dublin',
    },
    language: 'English, Irish, and many community languages',
    currency: 'Euro (EUR)',
    timeZone: 'Greenwich Mean Time / Irish Standard Time',
    foodCulture: ['Pub music', 'Literary culture', 'River walks', 'Market food', 'Tech workplaces'],
    knownFor: ['River Liffey', 'Trinity College', 'Ha-penny Bridge', 'Literary history'],
    prompt: 'How does Dublin use stories, bridges, and public places to connect past and present?',
  },
  recife: {
    population: {
      label: 'City population',
      value: '1.60M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/brazil/recife',
    },
    language: 'Portuguese',
    currency: 'Brazilian real (BRL)',
    timeZone: 'Brasilia Time (UTC-3)',
    foodCulture: ['Frevo', 'Maracatu', 'Seafood', 'Beach culture', 'Carnival traditions'],
    knownFor: ['Recife Antigo', 'Bridges and waterways', 'Boa Viagem Beach', 'Afro-Brazilian culture'],
    prompt: 'Why is Recife sometimes described through bridges, music, and the sea?',
  },
  santiago: {
    population: {
      label: 'Metro population',
      value: '7.00M',
      year: '2025 estimate',
      name: 'Data Commons',
      url: 'https://datacommons.org/place/wikidataId/Q2887',
    },
    language: 'Spanish',
    currency: 'Chilean peso (CLP)',
    timeZone: 'Chile Time',
    foodCulture: ['Marraqueta bread', 'Completos', 'Markets', 'Andes water systems', 'Public memory sites'],
    knownFor: ['Andes skyline', 'Plaza de Armas', 'La Moneda', 'Metro and valley geography'],
    prompt: 'How do the Andes shape Santiago weather, water, views, and movement?',
  },
  manila: {
    population: {
      label: 'Metro population',
      value: '15.53M',
      year: '2026 estimate',
      name: 'Macrotrends',
      url: 'https://www.macrotrends.net/datasets/global-metrics/cities/22109/manila/population',
    },
    language: 'Filipino, English, and many Philippine languages',
    currency: 'Philippine peso (PHP)',
    timeZone: 'Philippine Time (UTC+8)',
    foodCulture: ['Adobo', 'Jeepneys', 'Bay sunsets', 'Markets', 'Family-centered celebrations'],
    knownFor: ['Intramuros', 'Rizal Monument', 'Manila Bay', 'Dense metro movement'],
    prompt: 'How does Manila show colonial history, local transport, and coastal risk at once?',
  },
  'ho-chi-minh-city': {
    population: {
      label: 'City population',
      value: '10.55M',
      year: '2026 estimate',
      name: 'World Population Review',
      url: 'https://worldpopulationreview.com/cities/vietnam/ho-chi-minh-city',
    },
    language: 'Vietnamese and many community languages',
    currency: 'Vietnamese dong (VND)',
    timeZone: 'Indochina Time (UTC+7)',
    foodCulture: ['Pho', 'Banh mi', 'Vietnamese coffee', 'Motorbike routines', 'River trade'],
    knownFor: ['Ben Thanh Market', 'Saigon River', 'Notre-Dame Cathedral Basilica', 'Modern towers'],
    prompt: 'How does Ho Chi Minh City mix markets, motorbikes, river trade, and new towers?',
  },
};

export function getDestinationFacts(destinationId: string) {
  return DESTINATION_FACTS[destinationId] ?? null;
}

export function getLanguageHintForCountry(country: string) {
  return COUNTRY_LANGUAGE_HINTS[country] ?? 'Local and regional languages vary by community';
}
