import { WORLD_DESTINATIONS } from '@/data/world-flight/destinations';
import type { DestinationImage, DestinationPack } from '@/lib/world-flight/types';

export type PlaceMediaUsage = 'lesson-intro' | 'geo-clue' | 'reveal' | 'immersive' | 'background';
export type PlaceMediaProvider = 'wikimedia' | 'unsplash' | 'mapillary' | 'local' | 'external';
export type PlaceMediaKind = 'cityscape' | 'landmark' | 'street-scene' | 'landscape' | 'airport' | 'culture';
export type PlaceDifficulty = 'easy' | 'medium' | 'hard';

export interface PlaceMediaAsset {
  id: string;
  kind: PlaceMediaKind;
  title: string;
  provider: PlaceMediaProvider;
  usage: PlaceMediaUsage[];
  difficulty: PlaceDifficulty;
  alt: string;
  caption: string;
  sourceName: string;
  sourceUrl: string;
  url?: string;
  thumbnailUrl?: string;
  mapillaryImageId?: string;
  creator?: string;
  license?: string;
  focalPoint?: { x: number; y: number };
  spoilerRisk?: 'low' | 'medium' | 'high';
  tags?: string[];
}

export interface PlaceMediaRecord {
  id: string;
  name: string;
  city?: string;
  country: string;
  region: string;
  lat: number;
  lng: number;
  kind: 'city' | 'landmark' | 'region';
  difficulty: PlaceDifficulty;
  destinationId?: string;
  countryCode?: string;
  tags: string[];
  media: PlaceMediaAsset[];
}

function providerForImage(image: DestinationImage): PlaceMediaProvider {
  if (image.sourceName.toLowerCase().includes('wikimedia')) return 'wikimedia';
  if (image.sourceName.toLowerCase().includes('unsplash')) return 'unsplash';
  return 'external';
}

function destinationDifficulty(destination: DestinationPack): PlaceDifficulty {
  if (['paris', 'london', 'new-york', 'tokyo', 'cairo', 'sydney', 'rome'].includes(destination.id)) {
    return 'easy';
  }
  if (['suva', 'ulaanbaatar', 'almaty', 'dakar', 'recife', 'addis-ababa'].includes(destination.id)) {
    return 'hard';
  }
  return 'medium';
}

function mediaFromDestinationImage(destination: DestinationPack): PlaceMediaAsset {
  const image = destination.heroImage;
  return {
    id: `${destination.id}-hero`,
    kind: destination.scene.landmarkSilhouette ? 'cityscape' : 'landscape',
    title: `${destination.city} arrival view`,
    provider: providerForImage(image),
    usage: ['lesson-intro', 'geo-clue', 'reveal', 'background'],
    difficulty: destinationDifficulty(destination),
    url: image.url,
    alt: image.alt,
    caption: image.caption,
    sourceName: image.sourceName,
    sourceUrl: image.sourceUrl,
    creator: image.creator,
    license: image.license,
    focalPoint: image.focalPoint,
    spoilerRisk: 'medium',
    tags: [destination.scene.terrain, destination.scene.skyline, destination.region],
  };
}

function wikimediaFileUrl(fileName: string, width = 1200) {
  return `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(fileName)}?width=${width}`;
}

function wikimediaFilePage(fileName: string) {
  return `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(fileName).replace(/%20/g, '_')}`;
}

function wikimediaMediaAsset({
  id,
  kind,
  title,
  difficulty,
  fileName,
  alt,
  caption,
  creator,
  license,
  spoilerRisk = 'medium',
  tags = [],
}: {
  id: string;
  kind: PlaceMediaKind;
  title: string;
  difficulty: PlaceDifficulty;
  fileName: string;
  alt: string;
  caption: string;
  creator: string;
  license: string;
  spoilerRisk?: PlaceMediaAsset['spoilerRisk'];
  tags?: string[];
}): PlaceMediaAsset {
  return {
    id,
    kind,
    title,
    provider: 'wikimedia',
    usage: ['lesson-intro', 'geo-clue', 'reveal'],
    difficulty,
    url: wikimediaFileUrl(fileName),
    alt,
    caption,
    sourceName: 'Wikimedia Commons',
    sourceUrl: wikimediaFilePage(fileName),
    creator,
    license,
    spoilerRisk,
    tags,
  };
}

const CURATED_DESTINATION_MEDIA: Record<string, PlaceMediaAsset[]> = {
  'addis-ababa': [
    wikimediaMediaAsset({
      id: 'addis-ababa-african-union',
      kind: 'landmark',
      title: 'African Union Conference Centre',
      difficulty: 'hard',
      fileName: 'African Union Conference Centre building.jpg',
      alt: 'African Union Conference Centre in Addis Ababa',
      caption: 'Addis Ababa is a diplomatic capital and home to the African Union headquarters.',
      creator: 'Andrew Moore',
      license: 'CC BY-SA 2.0',
      spoilerRisk: 'high',
      tags: ['african-union', 'diplomacy', 'capital'],
    }),
    wikimediaMediaAsset({
      id: 'addis-ababa-holy-trinity',
      kind: 'landmark',
      title: 'Holy Trinity Cathedral',
      difficulty: 'medium',
      fileName: 'Holy Trinity Cathedral, Addis Ababa (3434312871).jpg',
      alt: 'Holy Trinity Cathedral in Addis Ababa',
      caption: 'Holy Trinity Cathedral shows Addis Ababa through faith, history, and national memory.',
      creator: 'A. Davey',
      license: 'CC BY 2.0',
      tags: ['cathedral', 'history', 'faith'],
    }),
    wikimediaMediaAsset({
      id: 'addis-ababa-coffee-ceremony',
      kind: 'culture',
      title: 'Coffee Ceremony',
      difficulty: 'medium',
      fileName: 'Coffee ceremony in Ethiopia - Addis Ababa.jpg',
      alt: 'Coffee ceremony in Addis Ababa',
      caption: 'Coffee ceremony is a social routine tied to hospitality, conversation, and Ethiopian culture.',
      creator: 'Scanfers',
      license: 'CC BY-SA 4.0',
      tags: ['coffee', 'ceremony', 'culture'],
    }),
  ],
  amsterdam: [
    wikimediaMediaAsset({
      id: 'amsterdam-bicycles-canals',
      kind: 'street-scene',
      title: 'Bicycles and Canals',
      difficulty: 'easy',
      fileName: 'Bicycles & Canals (5719321178).jpg',
      alt: 'Bicycles beside a canal in Amsterdam',
      caption: 'Amsterdam streets show how canals, bicycles, and daily routines fit together.',
      creator: 'Rob Young',
      license: 'CC BY 2.0',
      spoilerRisk: 'high',
      tags: ['canals', 'bicycles', 'daily-life'],
    }),
    wikimediaMediaAsset({
      id: 'amsterdam-rijksmuseum',
      kind: 'culture',
      title: 'Rijksmuseum',
      difficulty: 'easy',
      fileName: 'Rijksmuseum in Amsterdam.jpg',
      alt: 'Rijksmuseum in Amsterdam',
      caption: 'The Rijksmuseum connects Amsterdam with art, public space, and tourism.',
      creator: 'Marco Almbauer',
      license: 'CC BY-SA 3.0',
      tags: ['rijksmuseum', 'museum', 'art'],
    }),
    wikimediaMediaAsset({
      id: 'amsterdam-cheese-shop',
      kind: 'culture',
      title: 'Cheese Shop Near the Flower Market',
      difficulty: 'medium',
      fileName: 'Cheese shop in Amsterdam near the Flower Market (26211123761).jpg',
      alt: 'Cheese shop near the Flower Market in Amsterdam',
      caption: 'Cheese shops and market streets are part of Amsterdam food culture.',
      creator: 'Tobias Niepel',
      license: 'CC BY 2.0',
      tags: ['cheese', 'market', 'food'],
    }),
  ],
  bangkok: [
    wikimediaMediaAsset({
      id: 'bangkok-wat-arun-river',
      kind: 'landmark',
      title: 'Wat Arun on the Chao Phraya',
      difficulty: 'easy',
      fileName: 'Wat Arun from Chao Phraya River.jpg',
      alt: 'Wat Arun temple beside the Chao Phraya River in Bangkok',
      caption: 'Wat Arun links Bangkok river life with Buddhist temple architecture.',
      creator: 'Diliff',
      license: 'CC BY 2.5',
      spoilerRisk: 'high',
      tags: ['wat-arun', 'chao-phraya', 'temple'],
    }),
    wikimediaMediaAsset({
      id: 'bangkok-chatuchak-tuk-tuk',
      kind: 'street-scene',
      title: 'Tuk-tuk at Chatuchak Market',
      difficulty: 'medium',
      fileName: 'Tuk-tuk waiting outside Chatuchak Market - Bangkok.jpg',
      alt: 'Tuk-tuk waiting outside Chatuchak Market in Bangkok',
      caption: 'Tuk-tuks, markets, and street movement are part of everyday Bangkok.',
      creator: 'Zeugma fr (Antoine FLEURY-GOBERT)',
      license: 'CC BY-SA 3.0',
      tags: ['tuk-tuk', 'market', 'transport'],
    }),
    wikimediaMediaAsset({
      id: 'bangkok-chatuchak-market',
      kind: 'culture',
      title: 'Chatuchak Weekend Market',
      difficulty: 'medium',
      fileName: 'Chatuchak Weekend Market, Bangkok, Thailand (4570450571).jpg',
      alt: 'Shoppers and stalls at Chatuchak Weekend Market in Bangkok',
      caption: 'Chatuchak shows Bangkok as a city of markets, food, shopping, and crowds.',
      creator: 'yeowatzup',
      license: 'CC BY 2.0',
      tags: ['chatuchak', 'market', 'daily-life'],
    }),
  ],
  cairo: [
    wikimediaMediaAsset({
      id: 'cairo-giza-pyramids',
      kind: 'landmark',
      title: 'Giza Pyramids',
      difficulty: 'easy',
      fileName: 'The Giza Pyramids.jpg',
      alt: 'The Giza Pyramids near Cairo',
      caption: 'The pyramids place ancient history at the edge of modern Cairo.',
      creator: 'Morhaf Kamal Aljanee',
      license: 'CC BY-SA 3.0',
      spoilerRisk: 'high',
      tags: ['giza', 'pyramids', 'ancient-history'],
    }),
    wikimediaMediaAsset({
      id: 'cairo-nile-view',
      kind: 'cityscape',
      title: 'The Nile Through Cairo',
      difficulty: 'medium',
      fileName: 'River Nile in Cairo.jpg',
      alt: 'The Nile River running through Cairo',
      caption: 'The Nile is still a central line through Cairo city life.',
      creator: 'Mathew Eshak',
      license: 'CC BY-SA 4.0',
      tags: ['nile', 'river', 'cityscape'],
    }),
    wikimediaMediaAsset({
      id: 'cairo-khan-el-khalili',
      kind: 'culture',
      title: 'Khan el-Khalili Bazaar',
      difficulty: 'medium',
      fileName: 'Khan el-Khalili 2019 1.jpg',
      alt: 'Khan el-Khalili bazaar in Cairo',
      caption: 'Khan el-Khalili shows Cairo through trade, craft, tourism, and local movement.',
      creator: 'Mohammed Ali Moussa',
      license: 'CC BY-SA 4.0',
      tags: ['market', 'bazaar', 'historic-cairo'],
    }),
  ],
  dakar: [
    wikimediaMediaAsset({
      id: 'dakar-soumbedioune-fish-market',
      kind: 'culture',
      title: 'Soumbedioune Fish Market',
      difficulty: 'medium',
      fileName: 'PICT0275 Soumbedioune fish market (Dakar Senegal).jpg',
      alt: 'Soumbedioune fish market in Dakar',
      caption: 'Soumbedioune fish market shows Dakar through coast, work, trade, and food.',
      creator: 'Komalick',
      license: 'CC BY-SA 4.0',
      tags: ['fish-market', 'coast', 'daily-life'],
    }),
    wikimediaMediaAsset({
      id: 'dakar-goree-island',
      kind: 'landmark',
      title: 'Goree Island',
      difficulty: 'hard',
      fileName: 'Goree-island-senegal.png',
      alt: 'Goree Island and the House of Slaves off Dakar',
      caption: 'Goree Island is a major historical site off the coast of Dakar.',
      creator: 'Warren McKenzie',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['goree-island', 'history', 'atlantic'],
    }),
    wikimediaMediaAsset({
      id: 'dakar-mosque-of-divinity',
      kind: 'landmark',
      title: 'Mosque of the Divinity',
      difficulty: 'medium',
      fileName: 'Ouakam-Mosquée de la Divinité (3).jpg',
      alt: 'Mosque of the Divinity near the coast in Dakar',
      caption: 'The Mosque of the Divinity shows Dakar through coastline, faith, and neighborhood geography.',
      creator: 'Jeff Attaway',
      license: 'CC BY 2.0',
      tags: ['ouakam', 'mosque', 'coast'],
    }),
  ],
  delhi: [
    wikimediaMediaAsset({
      id: 'delhi-jama-masjid-market',
      kind: 'street-scene',
      title: 'Jama Masjid and Market',
      difficulty: 'medium',
      fileName: 'Jama Masjid and Market (1580792175).jpg',
      alt: 'Jama Masjid and nearby market street in Delhi',
      caption: 'Jama Masjid and nearby market streets show Delhi as a layered, crowded, historic city.',
      creator: 'Francisco Anzola',
      license: 'CC BY 2.0',
      spoilerRisk: 'high',
      tags: ['jama-masjid', 'market', 'old-delhi'],
    }),
    wikimediaMediaAsset({
      id: 'delhi-red-fort',
      kind: 'landmark',
      title: 'Red Fort',
      difficulty: 'easy',
      fileName: 'Red Fort in Delhi 03-2016 img3.jpg',
      alt: 'Red Fort in Delhi',
      caption: 'The Red Fort connects Delhi with Mughal history, public memory, and national identity.',
      creator: 'A.Savin',
      license: 'FAL',
      spoilerRisk: 'high',
      tags: ['red-fort', 'history', 'landmark'],
    }),
    wikimediaMediaAsset({
      id: 'delhi-india-gate',
      kind: 'landmark',
      title: 'India Gate',
      difficulty: 'easy',
      fileName: 'India Gate 1 (New Delhi).jpg',
      alt: 'India Gate in New Delhi',
      caption: 'India Gate is a major civic landmark in New Delhi.',
      creator: 'Subeesh Balan',
      license: 'CC BY-SA 3.0',
      tags: ['india-gate', 'new-delhi', 'landmark'],
    }),
  ],
  london: [
    wikimediaMediaAsset({
      id: 'london-tower-bridge-thames',
      kind: 'landmark',
      title: 'Tower Bridge and the Thames',
      difficulty: 'easy',
      fileName: "Tower Bridge and St Paul's Cathedral.jpg",
      alt: 'Tower Bridge and St Pauls Cathedral seen from across the River Thames',
      caption: 'The Thames connects London landmarks, transport, trade, and public space.',
      creator: 'sebastiandoe5',
      license: 'CC BY-SA 2.0',
      spoilerRisk: 'high',
      tags: ['tower-bridge', 'thames', 'landmark'],
    }),
    wikimediaMediaAsset({
      id: 'london-kings-cross-concourse',
      kind: 'street-scene',
      title: "King's Cross Station",
      difficulty: 'medium',
      fileName: "London banner King's Cross Western Concourse.jpg",
      alt: 'The western concourse of Kings Cross station in London',
      caption: "King's Cross shows how London moves through rail, work, and daily commuting.",
      creator: 'Colin; derivative work by Jjtkk',
      license: 'CC BY-SA 3.0',
      tags: ['rail', 'station', 'transport'],
    }),
    wikimediaMediaAsset({
      id: 'london-british-museum-court',
      kind: 'culture',
      title: 'British Museum Great Court',
      difficulty: 'medium',
      fileName: 'British Museum Great Court, London, UK - Diliff.jpg',
      alt: 'The Great Court inside the British Museum in London',
      caption: "Museums are part of London's global history, tourism, and public culture.",
      creator: 'Diliff',
      license: 'CC BY-SA 3.0',
      tags: ['museum', 'history', 'culture'],
    }),
  ],
  istanbul: [
    wikimediaMediaAsset({
      id: 'istanbul-historic-peninsula-skyline',
      kind: 'cityscape',
      title: 'Historic Peninsula and Modern Skyline',
      difficulty: 'easy',
      fileName: 'Historical peninsula and modern skyline of Istanbul.jpg',
      alt: 'Historic peninsula and modern skyline of Istanbul',
      caption: 'Istanbul layers historic mosques, waterways, bridges, and modern skyline in one view.',
      creator: 'Hunanuk',
      license: 'CC0',
      spoilerRisk: 'high',
      tags: ['historic-peninsula', 'skyline', 'bosphorus'],
    }),
    wikimediaMediaAsset({
      id: 'istanbul-bosphorus-ferry',
      kind: 'street-scene',
      title: 'Bosphorus Ferry',
      difficulty: 'medium',
      fileName: 'Istanbul Bosphorus ferry.jpg',
      alt: 'Ferry on the Bosphorus in Istanbul',
      caption: 'Bosphorus ferries show Istanbul as a city connected by water as much as roads.',
      creator: 'Jwslubbock',
      license: 'CC BY-SA 3.0',
      tags: ['bosphorus', 'ferry', 'transport'],
    }),
    wikimediaMediaAsset({
      id: 'istanbul-grand-bazaar',
      kind: 'culture',
      title: 'Grand Bazaar',
      difficulty: 'medium',
      fileName: 'Grand Bazaar, Istanbul TR(1).jpg',
      alt: 'Grand Bazaar in Istanbul',
      caption: 'The Grand Bazaar shows Istanbul through trade, tourism, craft, and historic routes.',
      creator: 'Stefano Vigorelli',
      license: 'CC BY-SA 4.0',
      tags: ['grand-bazaar', 'market', 'trade'],
    }),
  ],
  miami: [
    wikimediaMediaAsset({
      id: 'miami-biscayne-bay-skyline',
      kind: 'cityscape',
      title: 'Skyline from Biscayne Bay',
      difficulty: 'easy',
      fileName: 'Miami - City Skyline from Biscayne Bay 2.jpg',
      alt: 'Miami skyline from Biscayne Bay',
      caption: 'Biscayne Bay frames Miami as a coastal city shaped by water, towers, and climate.',
      creator: 'P. Hughes',
      license: 'CC BY 4.0',
      spoilerRisk: 'high',
      tags: ['biscayne-bay', 'skyline', 'coast'],
    }),
    wikimediaMediaAsset({
      id: 'miami-south-beach-art-deco',
      kind: 'culture',
      title: 'South Beach Art Deco District',
      difficulty: 'medium',
      fileName: 'Art Deco District, South Beach, Miami Beach. - panoramio.jpg',
      alt: 'Art Deco District in South Beach, Miami Beach',
      caption: 'South Beach art deco buildings connect Miami with design, tourism, and beach culture.',
      creator: 'Ivan Curra',
      license: 'CC BY-SA 3.0',
      tags: ['south-beach', 'art-deco', 'design'],
    }),
    wikimediaMediaAsset({
      id: 'miami-calle-ocho',
      kind: 'street-scene',
      title: 'Calle Ocho in Little Havana',
      difficulty: 'medium',
      fileName: 'Calle Ocho, Little Havana, Miami, Florida 2021 - Gallo de Calle Ocho.jpg',
      alt: 'Calle Ocho in Little Havana, Miami',
      caption: 'Calle Ocho shows Miami through Cuban American culture, bilingual streets, and neighborhood identity.',
      creator: 'Sharon Hahn Darlin',
      license: 'CC BY 2.0',
      tags: ['little-havana', 'calle-ocho', 'culture'],
    }),
  ],
  nairobi: [
    wikimediaMediaAsset({
      id: 'nairobi-national-park-skyline',
      kind: 'landscape',
      title: 'Nairobi Skyline from National Park',
      difficulty: 'medium',
      fileName: 'Nairobi Skyline from Nairobi National Park - panoramio.jpg',
      alt: 'Nairobi skyline seen from Nairobi National Park',
      caption: 'Nairobi has a rare city edge where skyline and wildlife landscape meet.',
      creator: 'Greg Gebhardt',
      license: 'CC BY-SA 3.0',
      spoilerRisk: 'high',
      tags: ['national-park', 'skyline', 'urban-wildlife'],
    }),
    wikimediaMediaAsset({
      id: 'nairobi-colorful-matatu',
      kind: 'street-scene',
      title: 'Colorful Matatu',
      difficulty: 'medium',
      fileName: 'A colorful matatu in Nairobi, Kenya, during rush hour.jpg',
      alt: 'Colorful matatu in Nairobi during rush hour',
      caption: 'Matatus show Nairobi transport as movement, art, sound, and social life.',
      creator: 'AEira-WMF',
      license: 'CC BY 4.0',
      tags: ['matatu', 'transport', 'street-life'],
    }),
    wikimediaMediaAsset({
      id: 'nairobi-city-market',
      kind: 'culture',
      title: 'Nairobi City Market',
      difficulty: 'medium',
      fileName: 'City Market in Nairobi.jpg',
      alt: 'City Market in Nairobi',
      caption: 'Nairobi City Market shows trade, food, craft, and everyday city exchange.',
      creator: 'Sam Wilson',
      license: 'CC BY-SA 2.0',
      tags: ['market', 'craft', 'daily-life'],
    }),
  ],
  'new-york': [
    wikimediaMediaAsset({
      id: 'new-york-brooklyn-bridge-skyline',
      kind: 'cityscape',
      title: 'Brooklyn Bridge and Manhattan',
      difficulty: 'easy',
      fileName: 'Brooklyn Bridge And Manhattan At Sunset New York Cityscape Photography (238415973).jpeg',
      alt: 'Brooklyn Bridge and Manhattan skyline at sunset',
      caption: 'The Brooklyn Bridge frames New York as a city of movement, density, and skyline views.',
      creator: 'Giuseppe Milo',
      license: 'CC BY 3.0',
      spoilerRisk: 'high',
      tags: ['brooklyn-bridge', 'manhattan', 'skyline'],
    }),
    wikimediaMediaAsset({
      id: 'new-york-central-park-skyline',
      kind: 'landscape',
      title: 'Central Park and Midtown',
      difficulty: 'easy',
      fileName: 'Central Park New York May 2015 007.jpg',
      alt: 'Central Park with New York buildings around it',
      caption: 'Central Park shows how green public space fits inside a very dense city.',
      creator: 'King of Hearts',
      license: 'CC BY-SA 3.0',
      tags: ['central-park', 'public-space', 'skyline'],
    }),
    wikimediaMediaAsset({
      id: 'new-york-times-square-food-carts',
      kind: 'culture',
      title: 'Food Carts in Times Square',
      difficulty: 'medium',
      fileName: 'Food Carts in Times Square NYC.jpg',
      alt: 'Food carts in Times Square in New York City',
      caption: 'Food carts are part of New York street life, tourism, and quick daily routines.',
      creator: 'SteveStrummer',
      license: 'CC0',
      tags: ['food-carts', 'times-square', 'street-food'],
    }),
  ],
  paris: [
    wikimediaMediaAsset({
      id: 'paris-eiffel-front-de-seine',
      kind: 'landmark',
      title: 'Eiffel Tower and the Seine',
      difficulty: 'easy',
      fileName: 'Aerial photograph of Eiffel Tower and Front de Seine, Paris 2005.jpg',
      alt: 'Aerial view of the Eiffel Tower and the Seine in Paris',
      caption: 'The Eiffel Tower and Seine make Paris easy to recognize from above.',
      creator: 'NateBW',
      license: 'CC BY-SA 2.0',
      spoilerRisk: 'high',
      tags: ['eiffel-tower', 'seine', 'landmark'],
    }),
    wikimediaMediaAsset({
      id: 'paris-grand-louvre',
      kind: 'culture',
      title: 'The Grand Louvre',
      difficulty: 'easy',
      fileName: 'The Grand Louvre (235493607).jpeg',
      alt: 'The Louvre Museum in Paris',
      caption: 'The Louvre connects Paris with art, tourism, history, and public space.',
      creator: 'Wichien W',
      license: 'CC0',
      tags: ['louvre', 'museum', 'art'],
    }),
    wikimediaMediaAsset({
      id: 'paris-bakery-counter',
      kind: 'culture',
      title: 'Paris Bakery Counter',
      difficulty: 'medium',
      fileName: 'Bakery sales counter in Paris.jpg',
      alt: 'Bakery sales counter in Paris',
      caption: 'Bakeries and small food routines are part of everyday Paris culture.',
      creator: 'THOR',
      license: 'CC BY 2.0',
      tags: ['bakery', 'food', 'daily-life'],
    }),
  ],
  'panama-city': [
    {
      id: 'panama-city-panama-canal-gatun-locks',
      kind: 'landmark',
      title: 'Panama Canal - Gatun Locks',
      provider: 'wikimedia',
      usage: ['lesson-intro', 'geo-clue', 'reveal'],
      difficulty: 'easy',
      url: wikimediaFileUrl('Panama Canal Gatun Locks.jpg'),
      alt: 'Gatun Locks on the Panama Canal',
      caption: 'The Panama Canal connects Atlantic and Pacific shipping routes through Panama.',
      sourceName: 'Wikimedia Commons',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Panama_Canal_Gatun_Locks.jpg',
      creator: 'Stan Shebs',
      license: 'CC BY-SA 3.0',
      spoilerRisk: 'high',
      tags: ['canal', 'engineering', 'waterway', 'trade'],
    },
    wikimediaMediaAsset({
      id: 'panama-city-skyline-casco-viejo',
      kind: 'cityscape',
      title: 'Panama City Skyline',
      difficulty: 'medium',
      fileName: 'Panama Skyline.jpg',
      alt: 'Panama City skyline seen from Casco Viejo',
      caption: 'Panama City pairs a historic district with a dense modern skyline.',
      creator: 'Nico2panama',
      license: 'CC BY-SA 3.0',
      tags: ['skyline', 'casco-viejo', 'waterfront'],
    }),
    wikimediaMediaAsset({
      id: 'panama-city-casco-viejo-street',
      kind: 'street-scene',
      title: 'Casco Viejo Street',
      difficulty: 'medium',
      fileName: 'Old Panama City - Casco Viejo - Panama - panoramio.jpg',
      alt: 'Street in Casco Viejo in Panama City',
      caption: "Casco Viejo shows the city's colonial streets, restoration, and neighborhood life.",
      creator: 'David Broad',
      license: 'CC BY 3.0',
      tags: ['casco-viejo', 'historic-district', 'street'],
    }),
  ],
  'rio-de-janeiro': [
    {
      id: 'rio-de-janeiro-christ-redeemer',
      kind: 'landmark',
      title: 'Christ the Redeemer',
      provider: 'wikimedia',
      usage: ['lesson-intro', 'geo-clue', 'reveal'],
      difficulty: 'easy',
      url: wikimediaFileUrl('Rio by night-Christ, The Redeemer, moon and Sugarloaf (9071376882).jpg'),
      alt: 'Wide night view of Rio de Janeiro with Christ the Redeemer and Sugarloaf Mountain',
      caption: 'Christ the Redeemer, Sugarloaf, and the city lights show Rio as a mountain-and-coast city.',
      sourceName: 'Wikimedia Commons',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Rio_by_night-Christ,_The_Redeemer,_moon_and_Sugarloaf_(9071376882).jpg',
      creator: 'Edmir Silvestre',
      license: 'CC BY 2.0',
      spoilerRisk: 'high',
      tags: ['christ-the-redeemer', 'corcovado', 'landmark'],
    },
    {
      id: 'rio-de-janeiro-copacabana-aerial',
      kind: 'landscape',
      title: 'Copacabana Beach',
      provider: 'wikimedia',
      usage: ['lesson-intro', 'geo-clue', 'reveal'],
      difficulty: 'medium',
      url: wikimediaFileUrl('Aerial view of Copacabana beach.jpg'),
      alt: 'Aerial view of Copacabana Beach in Rio de Janeiro',
      caption: 'Copacabana shows Rio as a dense coastal city shaped by beach public life.',
      sourceName: 'Wikimedia Commons',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Aerial_view_of_Copacabana_beach.jpg',
      creator: 'Gustavo Facci',
      license: 'CC BY-SA 2.0',
      spoilerRisk: 'medium',
      tags: ['copacabana', 'beach', 'coast'],
    },
    {
      id: 'rio-de-janeiro-tijuca-waterfall',
      kind: 'landscape',
      title: 'Tijuca Forest Waterfall',
      provider: 'wikimedia',
      usage: ['lesson-intro', 'geo-clue', 'reveal'],
      difficulty: 'medium',
      url: wikimediaFileUrl('Cachoeira - Floresta da Tijuca, Rio de Janeiro, Brazil.jpg'),
      alt: 'Waterfall in Tijuca Forest in Rio de Janeiro',
      caption: 'Tijuca Forest brings Atlantic forest, water, shade, and biodiversity into the city.',
      sourceName: 'Wikimedia Commons',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cachoeira_-_Floresta_da_Tijuca,_Rio_de_Janeiro,_Brazil.jpg',
      creator: 'slasher-fun',
      license: 'CC BY-SA 2.0',
      spoilerRisk: 'medium',
      tags: ['tijuca-forest', 'waterfall', 'nature'],
    },
    {
      id: 'rio-de-janeiro-sambadrome-carnaval',
      kind: 'culture',
      title: 'Carnaval at the Sambadrome',
      provider: 'wikimedia',
      usage: ['lesson-intro', 'geo-clue', 'reveal'],
      difficulty: 'medium',
      url: wikimediaFileUrl('Carnaval celebrations at Sambadrome, Rio 2019 03.jpg'),
      alt: 'Carnaval celebration at the Sambadrome in Rio de Janeiro',
      caption: 'Carnaval connects music, costume, dance, planning, and neighborhood pride.',
      sourceName: 'Wikimedia Commons',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Carnaval_celebrations_at_Sambadrome,_Rio_2019_03.jpg',
      creator: 'The John Templeton',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'medium',
      tags: ['carnaval', 'sambadrome', 'culture'],
    },
  ],
  singapore: [
    wikimediaMediaAsset({
      id: 'singapore-marina-bay-dusk',
      kind: 'cityscape',
      title: 'Marina Bay at Dusk',
      difficulty: 'easy',
      fileName: 'Singapore Marina Bay Dusk 2018-02-27.jpg',
      alt: 'Singapore Marina Bay skyline at dusk',
      caption: "Marina Bay shows Singapore's skyline, waterfront design, and global city identity.",
      creator: 'Benh LIEU SONG (Flickr)',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['marina-bay', 'skyline', 'waterfront'],
    }),
    wikimediaMediaAsset({
      id: 'singapore-gardens-by-the-bay',
      kind: 'landscape',
      title: 'Gardens by the Bay',
      difficulty: 'easy',
      fileName: 'Gardens by the Bay, Singapore 2012.JPG',
      alt: 'Gardens by the Bay in Singapore',
      caption: 'Gardens by the Bay connects nature, design, tourism, and city planning.',
      creator: 'RudolfSimon',
      license: 'CC BY-SA 3.0',
      tags: ['gardens-by-the-bay', 'garden-city', 'design'],
    }),
    wikimediaMediaAsset({
      id: 'singapore-hawker-centre',
      kind: 'culture',
      title: 'Singapore Hawker Centre',
      difficulty: 'medium',
      fileName: 'Image of a Singapore hawker center.jpg',
      alt: 'Hawker centre in Singapore',
      caption: 'Hawker centres show Singapore through affordable food, shared tables, and multilingual life.',
      creator: 'Qvssjp',
      license: 'CC BY-SA 4.0',
      tags: ['hawker-centre', 'food', 'daily-life'],
    }),
  ],
  shanghai: [
    wikimediaMediaAsset({
      id: 'shanghai-pudong-skyline',
      kind: 'cityscape',
      title: 'Pudong Skyline',
      difficulty: 'medium',
      fileName: 'Pudong Shanghai November 2017 panorama.jpg',
      alt: 'Pudong skyline in Shanghai across the Huangpu River',
      caption: 'Pudong places Shanghai modern towers across the river from older waterfront history.',
      creator: 'King of Hearts',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['pudong', 'skyline', 'huangpu-river'],
    }),
    wikimediaMediaAsset({
      id: 'shanghai-bund-waterfront',
      kind: 'cityscape',
      title: 'The Bund',
      difficulty: 'medium',
      fileName: 'Shanghai Bund-20150516-RM-173803.jpg',
      alt: 'The Bund waterfront in Shanghai',
      caption: 'The Bund shows Shanghai through riverfront architecture, trade history, and public memory.',
      creator: 'Ermell',
      license: 'CC BY-SA 4.0',
      tags: ['bund', 'waterfront', 'history'],
    }),
    wikimediaMediaAsset({
      id: 'shanghai-shikumen-museum',
      kind: 'culture',
      title: 'Shikumen Museum',
      difficulty: 'hard',
      fileName: '20090518 Shanghai Shikumen Museum 6860.jpg',
      alt: 'Interior of the Shanghai Shikumen Museum',
      caption: 'Shikumen spaces reveal Shanghai through lane neighborhoods, housing, memory, and redevelopment.',
      creator: 'Jakub Halun',
      license: 'CC BY-SA 3.0',
      tags: ['shikumen', 'lilong', 'neighborhoods'],
    }),
  ],
  tokyo: [
    wikimediaMediaAsset({
      id: 'tokyo-shibuya-crossing',
      kind: 'street-scene',
      title: 'Shibuya Crossing',
      difficulty: 'easy',
      fileName: 'Tokyo Shibuya Crossing 01.jpg',
      alt: 'Shibuya Crossing in Tokyo',
      caption: "Shibuya Crossing shows Tokyo's density, transit rhythms, and pedestrian flow.",
      creator: 'Zairon',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['shibuya', 'crossing', 'pedestrians'],
    }),
    wikimediaMediaAsset({
      id: 'tokyo-sensoji-kaminarimon',
      kind: 'landmark',
      title: 'Senso-ji Kaminarimon Gate',
      difficulty: 'easy',
      fileName: 'Senso-ji Kaminarimon 201503b.jpg',
      alt: 'Kaminarimon gate at Senso-ji temple in Tokyo',
      caption: 'Senso-ji brings historic temple space into the middle of modern Tokyo tourism.',
      creator: 'Tak1701d',
      license: 'CC BY-SA 3.0',
      tags: ['senso-ji', 'asakusa', 'temple'],
    }),
    wikimediaMediaAsset({
      id: 'tokyo-station-marunouchi',
      kind: 'street-scene',
      title: 'Tokyo Station',
      difficulty: 'medium',
      fileName: 'Tokyo Station (Marunouchi Building).jpg',
      alt: 'Tokyo Station Marunouchi building',
      caption: "Tokyo Station connects rail, work, shopping, and the city's organized movement.",
      creator: 'Alexandr3126',
      license: 'CC BY-SA 4.0',
      tags: ['tokyo-station', 'rail', 'transport'],
    }),
  ],
  sydney: [
    wikimediaMediaAsset({
      id: 'sydney-opera-house-harbour-bridge',
      kind: 'landmark',
      title: 'Opera House and Harbour Bridge',
      difficulty: 'easy',
      fileName: 'Sydney Opera House and Harbour Bridge.jpg',
      alt: 'Sydney Opera House and Harbour Bridge across the harbor',
      caption: 'Sydney Harbour links the Opera House, bridge, ferries, and public waterfront life.',
      creator: 'J. Woodward',
      license: 'CC BY-SA 3.0',
      spoilerRisk: 'high',
      tags: ['opera-house', 'harbour-bridge', 'harbor'],
    }),
    wikimediaMediaAsset({
      id: 'sydney-bondi-beach',
      kind: 'landscape',
      title: 'Bondi Beach',
      difficulty: 'easy',
      fileName: 'Bondi Beach.jpg',
      alt: 'Bondi Beach in Sydney',
      caption: 'Bondi Beach shows Sydney as a coastal city with outdoor public routines.',
      creator: 'Rabs003',
      license: 'CC BY-SA 3.0',
      tags: ['bondi', 'beach', 'coast'],
    }),
    wikimediaMediaAsset({
      id: 'sydney-circular-quay',
      kind: 'street-scene',
      title: 'Circular Quay Harbour View',
      difficulty: 'medium',
      fileName: 'Sydney Harbour from Circular Quay.jpg',
      alt: 'Sydney Harbour viewed from Circular Quay',
      caption: 'Circular Quay shows how ferries make the harbor part of daily movement.',
      creator: 'Paul Carmona',
      license: 'CC BY-SA 2.0',
      tags: ['circular-quay', 'ferries', 'transport'],
    }),
  ],
  'cape-town': [
    wikimediaMediaAsset({
      id: 'cape-town-table-mountain',
      kind: 'landscape',
      title: 'Table Mountain',
      difficulty: 'easy',
      fileName: 'Table mountain in Cape Town.jpg',
      alt: 'Table Mountain above Cape Town',
      caption: 'Table Mountain gives Cape Town one of the clearest geography signatures in the world.',
      creator: 'Hilton1949',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['table-mountain', 'mountain', 'landscape'],
    }),
    wikimediaMediaAsset({
      id: 'cape-town-bo-kaap',
      kind: 'culture',
      title: 'Bo-Kaap Houses',
      difficulty: 'medium',
      fileName: 'Bo-Kaap, Cape Town (P1050993).jpg',
      alt: 'Colorful houses in Bo-Kaap in Cape Town',
      caption: 'Bo-Kaap connects Cape Town with Cape Malay history, color, food, and neighborhood identity.',
      creator: 'Matti Blume',
      license: 'CC BY-SA 4.0',
      tags: ['bo-kaap', 'cape-malay', 'neighborhood'],
    }),
    wikimediaMediaAsset({
      id: 'cape-town-va-waterfront',
      kind: 'street-scene',
      title: 'V&A Waterfront',
      difficulty: 'medium',
      fileName: 'Victoria Wharf, V&A Waterfront, Cape Town (01).jpg',
      alt: 'Victoria Wharf at the V&A Waterfront in Cape Town',
      caption: 'The V&A Waterfront mixes tourism, harbor work, shopping, food, and public space.',
      creator: 'Moheen Reeyad',
      license: 'CC BY-SA 4.0',
      tags: ['waterfront', 'harbor', 'public-space'],
    }),
  ],
  rome: [
    wikimediaMediaAsset({
      id: 'rome-colosseum',
      kind: 'landmark',
      title: 'Colosseum',
      difficulty: 'easy',
      fileName: 'Colosseo 2020.jpg',
      alt: 'The Colosseum in Rome',
      caption: 'The Colosseum makes ancient Rome visible inside the modern city.',
      creator: 'FeaturedPics',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['colosseum', 'ancient-rome', 'landmark'],
    }),
    wikimediaMediaAsset({
      id: 'rome-roman-forum',
      kind: 'landmark',
      title: 'Roman Forum',
      difficulty: 'easy',
      fileName: 'Roman Forum.JPG',
      alt: 'Roman Forum ruins in Rome',
      caption: 'The Roman Forum shows Rome as a city where ruins and daily streets sit side by side.',
      creator: 'J. Miers',
      license: 'CC BY-SA 1.0',
      tags: ['roman-forum', 'ruins', 'history'],
    }),
    wikimediaMediaAsset({
      id: 'rome-campo-fiori-market',
      kind: 'culture',
      title: "Campo de' Fiori Market",
      difficulty: 'medium',
      fileName: "Market scene - Campo de' Fiori - Rome, Italy - DSC01645.jpg",
      alt: "Food market at Campo de' Fiori in Rome",
      caption: "Campo de' Fiori shows Rome through food, public squares, and neighborhood routines.",
      creator: 'Daderot',
      license: 'CC0',
      tags: ['market', 'food', 'public-square'],
    }),
  ],
  'mexico-city': [
    wikimediaMediaAsset({
      id: 'mexico-city-zocalo-cathedral',
      kind: 'landmark',
      title: 'Zocalo and Metropolitan Cathedral',
      difficulty: 'easy',
      fileName: 'Catedral Metropolitana.jpg',
      alt: 'Metropolitan Cathedral beside the Zocalo in Mexico City',
      caption: 'The Zocalo shows Mexico City through civic space, cathedral history, and public gathering.',
      creator: 'Anna Maj Michelson',
      license: 'CC BY 2.0',
      spoilerRisk: 'high',
      tags: ['zocalo', 'cathedral', 'historic-center'],
    }),
    wikimediaMediaAsset({
      id: 'mexico-city-bellas-artes',
      kind: 'culture',
      title: 'Palacio de Bellas Artes',
      difficulty: 'easy',
      fileName: 'Palacio de las Bellas Artes (Mexico City).jpg',
      alt: 'Palacio de Bellas Artes in Mexico City',
      caption: 'Palacio de Bellas Artes connects Mexico City with art, performance, architecture, and public life.',
      creator: 'Alex Covarrubias',
      license: 'CC BY 2.5',
      tags: ['bellas-artes', 'art', 'architecture'],
    }),
    wikimediaMediaAsset({
      id: 'mexico-city-xochimilco-trajineras',
      kind: 'culture',
      title: 'Xochimilco Trajineras',
      difficulty: 'medium',
      fileName: 'Xochimilco trajineras.jpg',
      alt: 'Colorful trajineras on the canals of Xochimilco',
      caption: 'Xochimilco keeps canal culture, music, food, and weekend gathering visible in the city.',
      creator: 'JorgeBRAZIL',
      license: 'CC BY 2.0',
      tags: ['xochimilco', 'canals', 'trajineras'],
    }),
  ],
  dubai: [
    wikimediaMediaAsset({
      id: 'dubai-downtown-skyline',
      kind: 'cityscape',
      title: 'Downtown Dubai Skyline',
      difficulty: 'easy',
      fileName: 'Dubai skyline 2015 (crop).jpg',
      alt: 'Downtown Dubai skyline with Burj Khalifa',
      caption: 'Dubai skyline shows rapid vertical growth from desert and trade routes.',
      creator: 'Tim.Reckmann',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['burj-khalifa', 'skyline', 'downtown'],
    }),
    wikimediaMediaAsset({
      id: 'dubai-creek-abra',
      kind: 'street-scene',
      title: 'Abra on Dubai Creek',
      difficulty: 'medium',
      fileName: 'UAE Dubai Abra img4 asv2018-01.jpg',
      alt: 'Abra boat on Dubai Creek',
      caption: 'Abras on Dubai Creek connect older trade routes with everyday transport.',
      creator: 'A.Savin',
      license: 'FAL',
      tags: ['dubai-creek', 'abra', 'transport'],
    }),
    wikimediaMediaAsset({
      id: 'dubai-spice-souk',
      kind: 'culture',
      title: 'Dubai Spice Souk',
      difficulty: 'medium',
      fileName: 'Dubai Spice Souk.jpg',
      alt: 'Spice souk in Deira, Dubai',
      caption: 'The spice souk shows Dubai through trade, smell, food, and older market streets.',
      creator: 'Stzeman',
      license: 'CC BY-SA 3.0',
      tags: ['spice-souk', 'deira', 'trade'],
    }),
  ],
  seoul: [
    wikimediaMediaAsset({
      id: 'seoul-gyeongbokgung-palace',
      kind: 'landmark',
      title: 'Gyeongbokgung Palace',
      difficulty: 'easy',
      fileName: 'Gyeongbokgung-GeunJeongJeon.jpg',
      alt: 'Gyeongbokgung Palace in Seoul',
      caption: 'Gyeongbokgung shows Seoul through palace history, tourism, and national memory.',
      creator: 'Jinho Jung',
      license: 'CC BY-SA 2.0',
      spoilerRisk: 'high',
      tags: ['gyeongbokgung', 'palace', 'history'],
    }),
    wikimediaMediaAsset({
      id: 'seoul-cheonggyecheon-stream',
      kind: 'landscape',
      title: 'Cheonggyecheon Stream',
      difficulty: 'medium',
      fileName: 'Korea-Seoul-Cheonggyecheon-2008-01.jpg',
      alt: 'Cheonggyecheon stream in Seoul',
      caption: 'Cheonggyecheon shows Seoul using water and public space inside a dense city.',
      creator: 'Ian Muttoo',
      license: 'CC BY-SA 2.0',
      tags: ['cheonggyecheon', 'stream', 'public-space'],
    }),
    wikimediaMediaAsset({
      id: 'seoul-myeongdong-night-market',
      kind: 'culture',
      title: 'Myeongdong Night Market',
      difficulty: 'medium',
      fileName: 'Myeongdong night market seoul 4.jpg',
      alt: 'Myeongdong night market street food in Seoul',
      caption: 'Myeongdong shows Seoul through shopping, street food, signs, and youth culture.',
      creator: 'Sgroey',
      license: 'CC BY-SA 4.0',
      tags: ['myeongdong', 'shopping', 'street-food'],
    }),
  ],
  'hong-kong': [
    wikimediaMediaAsset({
      id: 'hong-kong-victoria-peak-skyline',
      kind: 'cityscape',
      title: 'Skyline from Victoria Peak',
      difficulty: 'easy',
      fileName: 'Hong Kong Skyline viewed from Victoria Peak.jpg',
      alt: 'Hong Kong skyline viewed from Victoria Peak',
      caption: 'Victoria Peak shows Hong Kong as mountains, harbor, and dense high-rise city.',
      creator: 'Chensiyuan',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['victoria-peak', 'skyline', 'harbor'],
    }),
    wikimediaMediaAsset({
      id: 'hong-kong-star-ferry-view',
      kind: 'street-scene',
      title: 'Star Ferry View',
      difficulty: 'medium',
      fileName: 'Tsim Sha Tsui wharf from ferry.jpg',
      alt: 'Tsim Sha Tsui wharf viewed from a Star Ferry in Hong Kong',
      caption: 'The Star Ferry connects both sides of Victoria Harbour as daily transport and symbol.',
      creator: 'Enoch Lau',
      license: 'CC BY-SA 2.5',
      tags: ['star-ferry', 'victoria-harbour', 'transport'],
    }),
    wikimediaMediaAsset({
      id: 'hong-kong-temple-street-market',
      kind: 'culture',
      title: 'Temple Street Night Market',
      difficulty: 'medium',
      fileName: 'Temple Street Night Market, Kowloon, Hong Kong.jpg',
      alt: 'Temple Street Night Market in Hong Kong',
      caption: 'Temple Street Night Market shows food, signs, bargaining, and evening street life.',
      creator: 'Daniel Case',
      license: 'CC BY-SA 3.0',
      tags: ['temple-street', 'night-market', 'food'],
    }),
  ],
  madrid: [
    wikimediaMediaAsset({
      id: 'madrid-plaza-mayor',
      kind: 'landmark',
      title: 'Plaza Mayor',
      difficulty: 'easy',
      fileName: 'Plaza Mayor de Madrid 06.jpg',
      alt: 'Plaza Mayor in Madrid',
      caption: 'Plaza Mayor shows Madrid through public square life, history, and gathering.',
      creator: 'Carlos Delgado',
      license: 'CC BY-SA 3.0',
      spoilerRisk: 'high',
      tags: ['plaza-mayor', 'public-square', 'history'],
    }),
    wikimediaMediaAsset({
      id: 'madrid-royal-palace',
      kind: 'landmark',
      title: 'Royal Palace of Madrid',
      difficulty: 'easy',
      fileName: 'Palacio Real de Madrid - 05.jpg',
      alt: 'Royal Palace of Madrid',
      caption: 'The Royal Palace connects Madrid with monarchy, ceremony, tourism, and national history.',
      creator: 'Carlos Delgado',
      license: 'CC BY-SA 3.0',
      tags: ['royal-palace', 'history', 'landmark'],
    }),
    wikimediaMediaAsset({
      id: 'madrid-retiro-park',
      kind: 'landscape',
      title: 'Retiro Park',
      difficulty: 'medium',
      fileName: 'Palacio de Cristal - Parque del Retiro.jpg',
      alt: 'Crystal Palace in Retiro Park in Madrid',
      caption: 'Retiro Park shows how green public space shapes everyday life in central Madrid.',
      creator: 'Carlos Delgado',
      license: 'CC BY-SA 3.0',
      tags: ['retiro-park', 'public-space', 'green-space'],
    }),
  ],
  lisbon: [
    wikimediaMediaAsset({
      id: 'lisbon-belem-tower',
      kind: 'landmark',
      title: 'Belem Tower',
      difficulty: 'easy',
      fileName: 'Torre de Belem, Lisboa, Portugal.jpg',
      alt: 'Belem Tower in Lisbon',
      caption: 'Belem Tower connects Lisbon with maritime history and the Tagus River.',
      creator: 'Diego Delso',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['belem-tower', 'tagus', 'maritime-history'],
    }),
    wikimediaMediaAsset({
      id: 'lisbon-tram-28',
      kind: 'street-scene',
      title: 'Tram 28',
      difficulty: 'medium',
      fileName: 'Tram 28 Lisbon Portuguese.jpg',
      alt: 'Tram 28 in Lisbon',
      caption: 'Lisbon trams show how hills, narrow streets, and transport shape the city.',
      creator: 'Alvesgaspar',
      license: 'CC BY-SA 4.0',
      tags: ['tram', 'hills', 'transport'],
    }),
    wikimediaMediaAsset({
      id: 'lisbon-praca-comercio',
      kind: 'landmark',
      title: 'Praca do Comercio',
      difficulty: 'easy',
      fileName: 'Arco Triunfal da Rua Augusta, Plaza del Comercio, Lisboa, Portugal, 2012-05-12, DD 02.JPG',
      alt: 'Rua Augusta Arch at Praca do Comercio in Lisbon',
      caption: 'Praca do Comercio opens Lisbon toward the river and its trade history.',
      creator: 'Diego Delso',
      license: 'CC BY-SA 3.0',
      tags: ['praca-do-comercio', 'riverfront', 'public-square'],
    }),
  ],
  vancouver: [
    wikimediaMediaAsset({
      id: 'vancouver-stanley-park-seawall',
      kind: 'landscape',
      title: 'Stanley Park Seawall',
      difficulty: 'medium',
      fileName: 'Stanley Park Seawall.jpg',
      alt: 'Stanley Park seawall in Vancouver',
      caption: 'Stanley Park shows Vancouver through forest, ocean edge, and outdoor routines.',
      creator: 'GoToVan',
      license: 'CC BY 2.0',
      spoilerRisk: 'high',
      tags: ['stanley-park', 'seawall', 'outdoors'],
    }),
    wikimediaMediaAsset({
      id: 'vancouver-granville-island',
      kind: 'culture',
      title: 'Granville Island Public Market',
      difficulty: 'medium',
      fileName: 'Granville Island Market interior 01.jpg',
      alt: 'Granville Island Public Market in Vancouver',
      caption: 'Granville Island shows Vancouver through food, art, markets, and waterfront reuse.',
      creator: 'Joe Mabel',
      license: 'CC BY-SA 3.0',
      tags: ['granville-island', 'market', 'food'],
    }),
    wikimediaMediaAsset({
      id: 'vancouver-gastown-steam-clock',
      kind: 'street-scene',
      title: 'Gastown Steam Clock',
      difficulty: 'medium',
      fileName: 'Vancouver - Gastown Steam Clock 01.jpg',
      alt: 'Gastown steam clock in Vancouver',
      caption: 'Gastown connects Vancouver with older streets, tourism, brick buildings, and urban change.',
      creator: 'Joe Mabel',
      license: 'CC BY-SA 3.0',
      tags: ['gastown', 'historic-streets', 'tourism'],
    }),
  ],
  beijing: [
    wikimediaMediaAsset({
      id: 'beijing-forbidden-city',
      kind: 'landmark',
      title: 'Forbidden City from Coal Hill',
      difficulty: 'easy',
      fileName: 'The Forbidden City - View from Coal Hill.jpg',
      alt: 'The Forbidden City viewed from Coal Hill in Beijing',
      caption: 'The Forbidden City shows Beijing through imperial scale, gates, courtyards, and political memory.',
      creator: 'Pixelflake',
      license: 'CC BY-SA 3.0',
      spoilerRisk: 'high',
      tags: ['forbidden-city', 'imperial-history', 'capital'],
    }),
    wikimediaMediaAsset({
      id: 'beijing-temple-of-heaven',
      kind: 'landmark',
      title: 'Temple of Heaven',
      difficulty: 'easy',
      fileName: 'Temple of Heaven 20160323 01.jpg',
      alt: 'Temple of Heaven in Beijing',
      caption: 'The Temple of Heaven connects architecture, ritual, color, and public park life.',
      creator: 'Shujianyang',
      license: 'CC BY-SA 4.0',
      tags: ['temple-of-heaven', 'architecture', 'ritual'],
    }),
    wikimediaMediaAsset({
      id: 'beijing-hutong-neighborhood',
      kind: 'street-scene',
      title: 'Hutong Neighborhood',
      difficulty: 'medium',
      fileName: 'Beijing hutong area 3.jpg',
      alt: 'A hutong street in Beijing',
      caption: 'Hutongs show older neighborhood life inside a city known for large monuments and fast change.',
      creator: 'Geoff McKim',
      license: 'CC BY-SA 2.0',
      tags: ['hutong', 'neighborhood', 'urban-change'],
    }),
  ],
  berlin: [
    wikimediaMediaAsset({
      id: 'berlin-brandenburg-gate',
      kind: 'landmark',
      title: 'Brandenburg Gate',
      difficulty: 'easy',
      fileName: 'Brandenburger Tor abends.jpg',
      alt: 'Brandenburg Gate in Berlin in the evening',
      caption: 'Brandenburg Gate is a central Berlin symbol for division, reunification, and public gathering.',
      creator: 'Thomas Wolf, www.foto-tw.de',
      license: 'CC BY-SA 3.0',
      spoilerRisk: 'high',
      tags: ['brandenburg-gate', 'reunification', 'public-space'],
    }),
    wikimediaMediaAsset({
      id: 'berlin-east-side-gallery',
      kind: 'culture',
      title: 'East Side Gallery',
      difficulty: 'medium',
      fileName: 'Segment with Graffiti of the Berlin Wall (3 of 4) (cropped).jpg',
      alt: 'Painted Berlin Wall segment at the East Side Gallery',
      caption: 'The East Side Gallery turns a former barrier into public art and memory work.',
      creator: 'Lklundin',
      license: 'CC BY-SA 3.0',
      tags: ['berlin-wall', 'street-art', 'memory'],
    }),
    wikimediaMediaAsset({
      id: 'berlin-museum-island',
      kind: 'cityscape',
      title: 'Museum Island',
      difficulty: 'medium',
      fileName: 'Berlin Museumsinsel Fernsehturm.jpg',
      alt: 'Museum Island and the Berlin TV Tower',
      caption: 'Museum Island shows Berlin as a place where culture, institutions, and skyline meet.',
      creator: 'Thomas Wolf, www.foto-tw.de',
      license: 'CC BY-SA 3.0',
      tags: ['museum-island', 'museums', 'skyline'],
    }),
  ],
  moscow: [
    wikimediaMediaAsset({
      id: 'moscow-saint-basils-cathedral',
      kind: 'landmark',
      title: "Saint Basil's Cathedral",
      difficulty: 'easy',
      fileName: "Saint Basil's Cathedral in Moscow.jpg",
      alt: "Saint Basil's Cathedral in Moscow",
      caption: "Saint Basil's Cathedral makes Moscow's religious, political, and visual identity immediately recognizable.",
      creator: 'Tsy1980',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['saint-basils', 'red-square', 'landmark'],
    }),
    wikimediaMediaAsset({
      id: 'moscow-kievskaya-metro',
      kind: 'street-scene',
      title: 'Kievskaya Metro Station',
      difficulty: 'medium',
      fileName: 'Moscow KievskayaFL metro station asv2018-08.jpg',
      alt: 'Kievskaya metro station in Moscow',
      caption: 'Moscow Metro stations show how public transport can also communicate art, pride, and state image.',
      creator: 'A.Savin',
      license: 'FAL',
      tags: ['metro', 'transport', 'design'],
    }),
    wikimediaMediaAsset({
      id: 'moscow-kremlin-red-square',
      kind: 'landmark',
      title: 'Kremlin and Red Square',
      difficulty: 'easy',
      fileName: 'Kremlin and Red Square.1.jpg',
      alt: 'The Kremlin and Red Square in Moscow',
      caption: 'Red Square concentrates government, ceremony, tourism, and national symbols in one public space.',
      creator: 'mos.ru',
      license: 'CC BY 4.0',
      tags: ['kremlin', 'red-square', 'public-space'],
    }),
  ],
  toronto: [
    wikimediaMediaAsset({
      id: 'toronto-cn-tower',
      kind: 'landmark',
      title: 'CN Tower',
      difficulty: 'easy',
      fileName: 'Toronto - ON - CN Tower bei Nacht.jpg',
      alt: 'CN Tower in Toronto at night',
      caption: 'The CN Tower anchors Toronto skyline identity above Lake Ontario and downtown growth.',
      creator: 'Wladyslaw Sojka',
      license: 'CC BY-SA 3.0',
      spoilerRisk: 'high',
      tags: ['cn-tower', 'skyline', 'lake-ontario'],
    }),
    wikimediaMediaAsset({
      id: 'toronto-spadina-streetcar',
      kind: 'street-scene',
      title: 'Spadina Streetcar',
      difficulty: 'medium',
      fileName: '510 Spadina Streetcar 4425 at King Street stop, May 22 2026 (01).jpg',
      alt: 'A Toronto streetcar at a downtown stop',
      caption: 'Streetcars show how Toronto uses surface transit to connect dense neighborhoods.',
      creator: 'Dillan Payne',
      license: 'CC BY-SA 4.0',
      tags: ['streetcar', 'transit', 'neighborhoods'],
    }),
    wikimediaMediaAsset({
      id: 'toronto-st-lawrence-market',
      kind: 'culture',
      title: 'St. Lawrence Market',
      difficulty: 'medium',
      fileName: 'St Lawerence South Market Exterior 202112.jpg',
      alt: 'Exterior of St. Lawrence Market in Toronto',
      caption: 'St. Lawrence Market connects food, migration, commerce, and older downtown public life.',
      creator: 'Canmenwalker',
      license: 'CC BY 4.0',
      tags: ['market', 'food', 'downtown'],
    }),
  ],
  mumbai: [
    wikimediaMediaAsset({
      id: 'mumbai-gateway-of-india',
      kind: 'landmark',
      title: 'Gateway of India',
      difficulty: 'easy',
      fileName: 'Mumbai 03-2016 30 Gateway of India.jpg',
      alt: 'Gateway of India in Mumbai',
      caption: 'The Gateway of India shows Mumbai through port history, tourism, and colonial architecture.',
      creator: 'A.Savin',
      license: 'FAL',
      spoilerRisk: 'high',
      tags: ['gateway-of-india', 'port', 'history'],
    }),
    wikimediaMediaAsset({
      id: 'mumbai-marine-drive',
      kind: 'cityscape',
      title: 'Marine Drive',
      difficulty: 'easy',
      fileName: 'Mumbai 03-2016 27 skyline at Marine Drive.jpg',
      alt: 'Mumbai skyline at Marine Drive',
      caption: 'Marine Drive shows Mumbai as a dense coastal city with a famous public seafront.',
      creator: 'A.Savin',
      license: 'FAL',
      tags: ['marine-drive', 'coast', 'skyline'],
    }),
    wikimediaMediaAsset({
      id: 'mumbai-chhatrapati-shivaji-terminus',
      kind: 'landmark',
      title: 'Chhatrapati Shivaji Terminus',
      difficulty: 'medium',
      fileName: 'Chhatrapati shivaji terminus, esterno 01.jpg',
      alt: 'Chhatrapati Shivaji Terminus in Mumbai',
      caption: 'Chhatrapati Shivaji Terminus connects architecture with the rail movement that keeps Mumbai working.',
      creator: 'Sailko',
      license: 'CC BY 3.0',
      tags: ['rail', 'station', 'architecture'],
    }),
  ],
  'buenos-aires': [
    wikimediaMediaAsset({
      id: 'buenos-aires-obelisco',
      kind: 'landmark',
      title: 'Obelisco',
      difficulty: 'easy',
      fileName: 'Buenos Aires (20234294752).jpg',
      alt: 'Obelisco in Buenos Aires',
      caption: 'The Obelisco marks the broad avenues and central public identity of Buenos Aires.',
      creator: 'Rodrigo Paredes',
      license: 'CC BY 2.0',
      spoilerRisk: 'high',
      tags: ['obelisco', 'avenues', 'city-center'],
    }),
    wikimediaMediaAsset({
      id: 'buenos-aires-caminito',
      kind: 'culture',
      title: 'Caminito',
      difficulty: 'medium',
      fileName: 'Caminito - Entrada.jpg',
      alt: 'Colorful entrance to Caminito in Buenos Aires',
      caption: 'Caminito shows Buenos Aires through color, tourism, tango imagery, and neighborhood storytelling.',
      creator: 'Hernan Pinera',
      license: 'CC BY-SA 2.0',
      tags: ['caminito', 'la-boca', 'tango'],
    }),
    wikimediaMediaAsset({
      id: 'buenos-aires-casa-rosada',
      kind: 'landmark',
      title: 'Casa Rosada',
      difficulty: 'medium',
      fileName: 'Casa Rosada exterior from Plaza de Mayo.JPG',
      alt: 'Casa Rosada from Plaza de Mayo in Buenos Aires',
      caption: 'Casa Rosada and Plaza de Mayo connect Buenos Aires with government, protest, and public memory.',
      creator: 'Lars Curfs (Grashoofd)',
      license: 'CC BY-SA 3.0 nl',
      tags: ['casa-rosada', 'plaza-de-mayo', 'government'],
    }),
  ],
  'los-angeles': [
    wikimediaMediaAsset({
      id: 'los-angeles-hollywood-sign',
      kind: 'landmark',
      title: 'Hollywood Sign',
      difficulty: 'easy',
      fileName: 'Hollywood sign (8485145044).jpg',
      alt: 'Hollywood Sign in Los Angeles',
      caption: 'The Hollywood Sign links Los Angeles to image-making, entertainment, and global media.',
      creator: 'Gnaphron',
      license: 'CC BY-SA 2.0',
      spoilerRisk: 'high',
      tags: ['hollywood-sign', 'film', 'media'],
    }),
    wikimediaMediaAsset({
      id: 'los-angeles-griffith-observatory',
      kind: 'landmark',
      title: 'Griffith Observatory',
      difficulty: 'easy',
      fileName: 'Griffith observatory 2006.jpg',
      alt: 'Griffith Observatory in Los Angeles',
      caption: 'Griffith Observatory shows Los Angeles through public science, hills, views, and skyline distance.',
      creator: 'Matthew Field',
      license: 'CC BY 2.5',
      tags: ['griffith-observatory', 'science', 'hills'],
    }),
    wikimediaMediaAsset({
      id: 'los-angeles-santa-monica-pier',
      kind: 'culture',
      title: 'Santa Monica Pier',
      difficulty: 'medium',
      fileName: 'Santa monica pier entrance evening.jpg',
      alt: 'Santa Monica Pier entrance in the evening',
      caption: 'Santa Monica Pier connects Los Angeles with beach life, tourism, amusement, and the Pacific edge.',
      creator: 'web4camguy',
      license: 'CC BY-SA 2.0',
      tags: ['santa-monica', 'pier', 'coast'],
    }),
  ],
  jakarta: [
    wikimediaMediaAsset({
      id: 'jakarta-city-panorama',
      kind: 'cityscape',
      title: 'Jakarta Panorama',
      difficulty: 'medium',
      fileName: 'Jakarta Panorama.jpg',
      alt: 'Panorama of Jakarta city center',
      caption: 'Jakarta panorama shows the scale and vertical growth of one of Southeast Asia\'s largest cities.',
      creator: 'Gunawan Kartapranata',
      license: 'CC BY-SA 3.0',
      spoilerRisk: 'high',
      tags: ['skyline', 'megacity', 'growth'],
    }),
    wikimediaMediaAsset({
      id: 'jakarta-kota-tua',
      kind: 'landmark',
      title: 'Kota Tua and Fatahillah Square',
      difficulty: 'medium',
      fileName: 'Batavia City Hall (Jakarta History Museum) Fatahillah Square (2025) - img 01.jpg',
      alt: 'Jakarta History Museum at Fatahillah Square in Kota Tua',
      caption: 'Kota Tua shows Jakarta through colonial layers, museums, public squares, and preservation.',
      creator: 'Chainwit.',
      license: 'CC BY 4.0',
      tags: ['kota-tua', 'fatahillah-square', 'history'],
    }),
    wikimediaMediaAsset({
      id: 'jakarta-monas-from-istiqlal',
      kind: 'landmark',
      title: 'Monas from Istiqlal',
      difficulty: 'easy',
      fileName: 'Monas from Istiqlal.jpg',
      alt: 'National Monument seen from Istiqlal Mosque in Jakarta',
      caption: 'Monas and Istiqlal place national memory and religious public space close together in Jakarta.',
      creator: 'Salmiah La Suma',
      license: 'CC BY-SA 4.0',
      tags: ['monas', 'istiqlal', 'national-symbols'],
    }),
  ],
  lagos: [
    wikimediaMediaAsset({
      id: 'lagos-lekki-ikoyi-bridge',
      kind: 'landmark',
      title: 'Lekki-Ikoyi Link Bridge',
      difficulty: 'medium',
      fileName: 'Lekki-link-bridge--full-view2.jpg',
      alt: 'Lekki-Ikoyi Link Bridge in Lagos',
      caption: 'The Lekki-Ikoyi bridge shows Lagos through water crossings, growth, and new urban links.',
      creator: 'S.aderogba',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['lekki-ikoyi', 'bridge', 'lagoon'],
    }),
    wikimediaMediaAsset({
      id: 'lagos-national-theatre',
      kind: 'culture',
      title: 'National Theatre',
      difficulty: 'medium',
      fileName: 'National Theatre Nigeria.jpg',
      alt: 'National Theatre in Lagos',
      caption: 'The National Theatre connects Lagos with performance, national culture, and public architecture.',
      creator: 'Godiva Omoruyi',
      license: 'CC BY-SA 4.0',
      tags: ['national-theatre', 'performance', 'culture'],
    }),
    wikimediaMediaAsset({
      id: 'lagos-island',
      kind: 'cityscape',
      title: 'Lagos Island',
      difficulty: 'medium',
      fileName: 'Lagos Island.jpg',
      alt: 'View of Lagos Island',
      caption: 'Lagos Island shows density, commerce, and water-shaped city geography.',
      creator: 'Benji Robertson',
      license: 'CC BY-SA 1.0',
      tags: ['lagos-island', 'commerce', 'density'],
    }),
  ],
  honolulu: [
    wikimediaMediaAsset({
      id: 'honolulu-waikiki',
      kind: 'landscape',
      title: 'Waikiki',
      difficulty: 'easy',
      fileName: 'City of Waikiki view.jpg',
      alt: 'Waikiki skyline and coast in Honolulu',
      caption: 'Waikiki shows Honolulu through tourism, beach routines, hotels, and ocean identity.',
      creator: 'Pickle the cool',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['waikiki', 'beach', 'tourism'],
    }),
    wikimediaMediaAsset({
      id: 'honolulu-diamond-head',
      kind: 'landscape',
      title: 'Diamond Head',
      difficulty: 'easy',
      fileName: 'Diamond Head Hawaii From Round Top Rd.JPG',
      alt: 'Diamond Head volcanic crater in Honolulu',
      caption: 'Diamond Head makes Honolulu geography visible as a volcanic island landscape.',
      creator: 'mar1865',
      license: 'CC BY-SA 3.0',
      tags: ['diamond-head', 'volcano', 'landscape'],
    }),
    wikimediaMediaAsset({
      id: 'honolulu-iolani-palace',
      kind: 'landmark',
      title: 'Iolani Palace',
      difficulty: 'medium',
      fileName: 'Iolani Palace (51872681413).jpg',
      alt: 'Iolani Palace in Honolulu',
      caption: 'Iolani Palace connects Honolulu with the history of the Hawaiian Kingdom and statehood.',
      creator: 'Gage Skidmore',
      license: 'CC BY-SA 2.0',
      tags: ['iolani-palace', 'hawaiian-kingdom', 'history'],
    }),
  ],
  bogota: [
    wikimediaMediaAsset({
      id: 'bogota-monserrate',
      kind: 'landscape',
      title: 'Monserrate',
      difficulty: 'easy',
      fileName: 'Monserrate Bogota.jpg',
      alt: 'Monserrate above Bogota',
      caption: 'Monserrate shows Bogota as a high Andean capital with hills shaping orientation and views.',
      creator: 'Briyotome',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['monserrate', 'andes', 'viewpoint'],
    }),
    wikimediaMediaAsset({
      id: 'bogota-plaza-bolivar',
      kind: 'landmark',
      title: 'Plaza Bolivar',
      difficulty: 'easy',
      fileName: 'Plaza de Bolivar - Bogota - Colombia - ANDREA GAETANO.JPG',
      alt: 'Plaza Bolivar in Bogota',
      caption: 'Plaza Bolivar concentrates civic buildings, protest history, tourism, and public memory.',
      creator: 'Andrea Gaetano',
      license: 'CC BY-SA 3.0',
      tags: ['plaza-bolivar', 'civic-space', 'government'],
    }),
    wikimediaMediaAsset({
      id: 'bogota-transmilenio',
      kind: 'street-scene',
      title: 'TransMilenio',
      difficulty: 'medium',
      fileName: 'TransMilenio-Bogota-2007-1.jpg',
      alt: 'TransMilenio bus rapid transit in Bogota',
      caption: 'TransMilenio shows how Bogota uses bus rapid transit to move people across a large city.',
      creator: 'Managementboy',
      license: 'CC BY-SA 4.0',
      tags: ['transmilenio', 'bus-rapid-transit', 'mobility'],
    }),
  ],
  reykjavik: [
    wikimediaMediaAsset({
      id: 'reykjavik-hallgrimskirkja',
      kind: 'landmark',
      title: 'Hallgrimskirkja',
      difficulty: 'easy',
      fileName: 'Hallgrimskirkja mai 2026.jpg',
      alt: 'Hallgrimskirkja church in Reykjavik',
      caption: 'Hallgrimskirkja gives Reykjavik a strong vertical landmark in a compact northern city.',
      creator: 'Steinninn',
      license: 'CC BY 4.0',
      spoilerRisk: 'high',
      tags: ['hallgrimskirkja', 'church', 'landmark'],
    }),
    wikimediaMediaAsset({
      id: 'reykjavik-harpa',
      kind: 'culture',
      title: 'Harpa Concert Hall',
      difficulty: 'medium',
      fileName: 'Harpa harpa 01.jpg',
      alt: 'Harpa concert hall in Reykjavik',
      caption: 'Harpa connects Reykjavik with music, waterfront redevelopment, light, glass, and public culture.',
      creator: 'H. Zell',
      license: 'CC BY-SA 3.0',
      tags: ['harpa', 'music', 'waterfront'],
    }),
    wikimediaMediaAsset({
      id: 'reykjavik-city-panorama',
      kind: 'cityscape',
      title: 'Reykjavik Panorama',
      difficulty: 'medium',
      fileName: 'Reykjavik pano Saga.jpg',
      alt: 'Panorama of Reykjavik',
      caption: 'Reykjavik panorama shows a low, compact city in a dramatic North Atlantic setting.',
      creator: 'Wurzeller',
      license: 'CC BY-SA 3.0',
      tags: ['panorama', 'north-atlantic', 'compact-city'],
    }),
  ],
  lima: [
    wikimediaMediaAsset({
      id: 'lima-plaza-mayor',
      kind: 'landmark',
      title: 'Plaza Mayor',
      difficulty: 'easy',
      fileName: 'Plaza Mayor de Lima (1).jpg',
      alt: 'Plaza Mayor in Lima',
      caption: 'Plaza Mayor shows Lima through colonial architecture, government, public gathering, and tourism.',
      creator: 'Jonathan M. Corredor O.',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['plaza-mayor', 'historic-center', 'government'],
    }),
    wikimediaMediaAsset({
      id: 'lima-miraflores',
      kind: 'landscape',
      title: 'Miraflores Coast',
      difficulty: 'medium',
      fileName: 'Miraflores 2023.jpg',
      alt: 'Miraflores coast in Lima',
      caption: 'Miraflores shows Lima as a Pacific coastal city built above cliffs and ocean routes.',
      creator: 'Mojnsen',
      license: 'CC BY-SA 4.0',
      tags: ['miraflores', 'coast', 'cliffs'],
    }),
    wikimediaMediaAsset({
      id: 'lima-huaca-pucllana',
      kind: 'landmark',
      title: 'Huaca Pucllana',
      difficulty: 'medium',
      fileName: 'Huaca Pucllana Miraflores.jpg',
      alt: 'Huaca Pucllana ruins in Lima',
      caption: 'Huaca Pucllana makes pre-colonial history visible inside modern Lima neighborhoods.',
      creator: 'McKay Savage',
      license: 'CC BY 2.0',
      tags: ['huaca-pucllana', 'ancient-history', 'urban-layers'],
    }),
  ],
  perth: [
    wikimediaMediaAsset({
      id: 'perth-elizabeth-quay',
      kind: 'cityscape',
      title: 'Elizabeth Quay',
      difficulty: 'medium',
      fileName: 'Elizabeth Quay June 2018 b.jpg',
      alt: 'Elizabeth Quay in Perth',
      caption: 'Elizabeth Quay shows Perth building public space around the Swan River and downtown waterfront.',
      creator: 'Nick-D / Georgfotoart',
      license: 'CC BY-SA 3.0',
      spoilerRisk: 'high',
      tags: ['elizabeth-quay', 'swan-river', 'waterfront'],
    }),
    wikimediaMediaAsset({
      id: 'perth-kings-park',
      kind: 'landscape',
      title: 'Kings Park',
      difficulty: 'medium',
      fileName: 'Kings Park War Memorial Sunrise.jpg',
      alt: 'Kings Park War Memorial at sunrise in Perth',
      caption: 'Kings Park shows Perth through native plants, public views, memory, and outdoor life.',
      creator: 'Mark',
      license: 'GFDL',
      tags: ['kings-park', 'green-space', 'views'],
    }),
    wikimediaMediaAsset({
      id: 'perth-cottesloe-beach',
      kind: 'landscape',
      title: 'Cottesloe Beach',
      difficulty: 'medium',
      fileName: 'Cottesloe Beach, Perth, Western Australia (4431664542).jpg',
      alt: 'Cottesloe Beach in Perth',
      caption: 'Cottesloe Beach connects Perth with Indian Ocean routines, leisure, weather, and coastal identity.',
      creator: 'Michael Spencer',
      license: 'CC BY 2.0',
      tags: ['cottesloe', 'beach', 'indian-ocean'],
    }),
  ],
  auckland: [
    wikimediaMediaAsset({
      id: 'auckland-sky-tower',
      kind: 'landmark',
      title: 'Sky Tower',
      difficulty: 'easy',
      fileName: '01 Auckland New Zealand-1000137.jpg',
      alt: 'Sky Tower in Auckland',
      caption: 'Sky Tower gives Auckland a clear skyline landmark above the harbor city.',
      creator: 'QFSE Media',
      license: 'CC BY-SA 3.0 nz',
      spoilerRisk: 'high',
      tags: ['sky-tower', 'skyline', 'harbor-city'],
    }),
    wikimediaMediaAsset({
      id: 'auckland-harbour-bridge',
      kind: 'landmark',
      title: 'Auckland Harbour Bridge',
      difficulty: 'medium',
      fileName: 'Auckland Harbour Bridge - August 2024.jpg',
      alt: 'Auckland Harbour Bridge',
      caption: 'Auckland Harbour Bridge shows how water shapes commuting, views, and city expansion.',
      creator: 'MrSeabody',
      license: 'CC0',
      tags: ['harbour-bridge', 'commuting', 'water'],
    }),
    wikimediaMediaAsset({
      id: 'auckland-mount-eden',
      kind: 'landscape',
      title: 'Mount Eden',
      difficulty: 'medium',
      fileName: 'Mount Eden from Maungawhau (Mount Eden).jpg',
      alt: 'Mount Eden volcanic cone in Auckland',
      caption: 'Mount Eden shows Auckland as a city shaped by volcanic cones and layered cultural meaning.',
      creator: 'russellstreet',
      license: 'CC BY-SA 2.0',
      tags: ['mount-eden', 'volcano', 'maungawhau'],
    }),
  ],
  suva: [
    wikimediaMediaAsset({
      id: 'suva-city-view',
      kind: 'cityscape',
      title: 'Suva City View',
      difficulty: 'hard',
      fileName: 'Suva, Fiji 77.jpg',
      alt: 'View of Suva in Fiji',
      caption: 'Suva shows a compact Pacific capital shaped by harbor geography, government, and markets.',
      creator: 'Maksym Kozlenko',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['suva', 'pacific-capital', 'harbor'],
    }),
    wikimediaMediaAsset({
      id: 'suva-fiji-museum',
      kind: 'culture',
      title: 'Fiji Museum',
      difficulty: 'hard',
      fileName: 'Fiji Museum Clock Tower Suva MatthiasSuessen-7816.jpg',
      alt: 'Fiji Museum clock tower in Suva',
      caption: 'Fiji Museum connects Suva with Pacific history, material culture, and shared memory.',
      creator: 'Matthias Suessen',
      license: 'CC BY-SA 3.0',
      tags: ['fiji-museum', 'history', 'culture'],
    }),
    wikimediaMediaAsset({
      id: 'suva-government-house',
      kind: 'landmark',
      title: 'Government House',
      difficulty: 'hard',
      fileName: 'The Government House, Suva.jpg',
      alt: 'Government House in Suva',
      caption: 'Government House shows Suva through capital-city institutions and colonial-era architecture.',
      creator: 'Qiliho',
      license: 'CC BY 3.0',
      tags: ['government-house', 'capital', 'architecture'],
    }),
  ],
  almaty: [
    wikimediaMediaAsset({
      id: 'almaty-zenkov-cathedral',
      kind: 'landmark',
      title: 'Zenkov Cathedral',
      difficulty: 'hard',
      fileName: 'Zenkov cathedral.jpg',
      alt: 'Zenkov Cathedral in Almaty',
      caption: 'Zenkov Cathedral connects Almaty with wooden architecture, faith, parks, and older city layers.',
      creator: 'Petar Milosevic',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['zenkov-cathedral', 'architecture', 'faith'],
    }),
    wikimediaMediaAsset({
      id: 'almaty-kok-tobe-tower',
      kind: 'landscape',
      title: 'Kok Tobe Tower',
      difficulty: 'hard',
      fileName: 'TV-Turm Almaty - 3.jpg',
      alt: 'Kok Tobe television tower above Almaty',
      caption: 'Kok Tobe shows Almaty as a mountain-edge city with high viewpoints and recreation above downtown.',
      creator: 'Michael Grau',
      license: 'CC BY-SA 3.0',
      tags: ['kok-tobe', 'mountains', 'viewpoint'],
    }),
    wikimediaMediaAsset({
      id: 'almaty-green-bazaar',
      kind: 'culture',
      title: 'Green Bazaar',
      difficulty: 'hard',
      fileName: '2008 Green bazaar Almaty nuts 2472773966.jpg',
      alt: 'Nuts for sale at Green Bazaar in Almaty',
      caption: 'Green Bazaar shows Almaty through food, trade, seasonal produce, and everyday social exchange.',
      creator: 'sly06',
      license: 'CC BY 2.0',
      tags: ['green-bazaar', 'market', 'food'],
    }),
  ],
  dublin: [
    wikimediaMediaAsset({
      id: 'dublin-hapenny-bridge',
      kind: 'landmark',
      title: 'Ha-penny Bridge',
      difficulty: 'easy',
      fileName: 'HalfPennyBridge.jpg',
      alt: 'Ha-penny Bridge over the River Liffey in Dublin',
      caption: 'Ha-penny Bridge makes the River Liffey visible as a daily crossing and city symbol.',
      creator: 'Wikimedia Commons contributor',
      license: 'Public domain',
      spoilerRisk: 'high',
      tags: ['ha-penny-bridge', 'river-liffey', 'bridge'],
    }),
    wikimediaMediaAsset({
      id: 'dublin-trinity-college',
      kind: 'landmark',
      title: 'Trinity College',
      difficulty: 'medium',
      fileName: 'The entrance of the historic Trinity College (Unsplash).jpg',
      alt: 'Entrance to Trinity College Dublin',
      caption: 'Trinity College connects Dublin with learning, books, tourism, and public memory.',
      creator: 'Stephen Bergin',
      license: 'CC0',
      tags: ['trinity-college', 'education', 'books'],
    }),
    wikimediaMediaAsset({
      id: 'dublin-temple-bar',
      kind: 'street-scene',
      title: 'Temple Bar',
      difficulty: 'medium',
      fileName: 'Temple Bar street scenes, Dublin.jpg',
      alt: 'Temple Bar street scene in Dublin',
      caption: 'Temple Bar shows Dublin through music, tourism, nightlife, walking streets, and performance.',
      creator: 'William Murphy',
      license: 'CC BY-SA 2.0',
      tags: ['temple-bar', 'music', 'street-life'],
    }),
  ],
  recife: [
    wikimediaMediaAsset({
      id: 'recife-marco-zero',
      kind: 'landmark',
      title: 'Marco Zero',
      difficulty: 'medium',
      fileName: 'Marco Zero - Recife Antigo - Recife, Pernambuco, Brasil.jpg',
      alt: 'Marco Zero square in Recife Antigo',
      caption: 'Marco Zero marks Recife Antigo as a civic and cultural gathering point near the waterfront.',
      creator: 'A. Junior',
      license: 'CC BY 2.0',
      spoilerRisk: 'high',
      tags: ['marco-zero', 'recife-antigo', 'public-square'],
    }),
    wikimediaMediaAsset({
      id: 'recife-rua-bom-jesus',
      kind: 'street-scene',
      title: 'Rua do Bom Jesus',
      difficulty: 'medium',
      fileName: 'Recife bom jesus.jpg',
      alt: 'Rua do Bom Jesus in Recife',
      caption: 'Rua do Bom Jesus shows Recife through historic streets, color, tourism, and layered heritage.',
      creator: 'Wikimedia Commons contributor',
      license: 'Public domain',
      tags: ['recife-antigo', 'historic-street', 'heritage'],
    }),
    wikimediaMediaAsset({
      id: 'recife-aerial-coast',
      kind: 'cityscape',
      title: 'Recife Aerial View',
      difficulty: 'medium',
      fileName: 'Recife aerial view.jpg',
      alt: 'Aerial view of Recife',
      caption: 'Recife aerial view shows water, bridges, coast, and dense urban development together.',
      creator: 'Arne Mueseler',
      license: 'CC BY-SA 3.0 de',
      tags: ['aerial', 'bridges', 'coast'],
    }),
  ],
  santiago: [
    wikimediaMediaAsset({
      id: 'santiago-plaza-de-armas',
      kind: 'landmark',
      title: 'Plaza de Armas',
      difficulty: 'medium',
      fileName: 'Plaza de Armas de Santiago 2017 b.jpg',
      alt: 'Plaza de Armas in Santiago',
      caption: 'Plaza de Armas shows Santiago through civic gathering, colonial layout, and everyday public life.',
      creator: 'WeHaKa',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['plaza-de-armas', 'public-square', 'historic-center'],
    }),
    wikimediaMediaAsset({
      id: 'santiago-la-moneda',
      kind: 'landmark',
      title: 'La Moneda Palace',
      difficulty: 'medium',
      fileName: 'Palacio de La Moneda - miguelreflex.jpg',
      alt: 'La Moneda Palace in Santiago',
      caption: 'La Moneda connects Santiago with government, ceremony, protest, and public memory.',
      creator: 'Miguel Hernandez',
      license: 'CC BY-SA 2.0',
      tags: ['la-moneda', 'government', 'memory'],
    }),
    wikimediaMediaAsset({
      id: 'santiago-cerro-san-cristobal',
      kind: 'landscape',
      title: 'Cerro San Cristobal',
      difficulty: 'medium',
      fileName: 'Cerro San Cristobal Santiago, Chile.jpg',
      alt: 'View from Cerro San Cristobal in Santiago',
      caption: 'Cerro San Cristobal shows how hills and the Andes frame Santiago views and public recreation.',
      creator: 'David Berkowitz',
      license: 'CC BY 2.0',
      tags: ['cerro-san-cristobal', 'andes', 'viewpoint'],
    }),
  ],
  manila: [
    wikimediaMediaAsset({
      id: 'manila-fort-santiago',
      kind: 'landmark',
      title: 'Fort Santiago',
      difficulty: 'medium',
      fileName: 'Fort Santiago, Intramuros.JPG',
      alt: 'Fort Santiago in Intramuros, Manila',
      caption: 'Fort Santiago shows Manila through walls, colonial history, wartime memory, and reconstruction.',
      creator: 'Elmer B. Domingo',
      license: 'CC BY-SA 3.0',
      spoilerRisk: 'high',
      tags: ['fort-santiago', 'intramuros', 'history'],
    }),
    wikimediaMediaAsset({
      id: 'manila-rizal-monument',
      kind: 'landmark',
      title: 'Rizal Monument',
      difficulty: 'medium',
      fileName: 'Rizal Monument at Rizal Park.jpg',
      alt: 'Rizal Monument in Manila',
      caption: 'Rizal Monument connects Manila with national memory, public parks, and civic identity.',
      creator: 'Maynard Rabanal',
      license: 'CC BY-SA 3.0',
      tags: ['rizal-monument', 'public-memory', 'park'],
    }),
    wikimediaMediaAsset({
      id: 'manila-jeepney',
      kind: 'culture',
      title: 'Jeepney',
      difficulty: 'medium',
      fileName: 'Jeepney, Magallanes Drive, Intramuros, 2018 (02).jpg',
      alt: 'A jeepney on Magallanes Drive in Manila',
      caption: 'Jeepneys show Manila through transport, visual culture, livelihoods, and modernization debates.',
      creator: 'Bahnfrend',
      license: 'CC BY-SA 4.0',
      tags: ['jeepney', 'transport', 'visual-culture'],
    }),
  ],
  'ho-chi-minh-city': [
    wikimediaMediaAsset({
      id: 'ho-chi-minh-city-ben-thanh-market',
      kind: 'culture',
      title: 'Ben Thanh Market',
      difficulty: 'medium',
      fileName: 'Ben Thanh, Ciudad Ho Chi Minh, Vietnam, 2013-08-14, DD 01.JPG',
      alt: 'Ben Thanh Market in Ho Chi Minh City',
      caption: 'Ben Thanh Market shows Ho Chi Minh City through food, bargaining, tourism, and daily commerce.',
      creator: 'Diego Delso',
      license: 'CC BY-SA 3.0',
      spoilerRisk: 'high',
      tags: ['ben-thanh', 'market', 'commerce'],
    }),
    wikimediaMediaAsset({
      id: 'ho-chi-minh-city-notre-dame-basilica',
      kind: 'landmark',
      title: 'Notre-Dame Cathedral Basilica',
      difficulty: 'medium',
      fileName: 'Ho Chi Minh City, Notre-Dame Basilica, 2020-01 CN-01.jpg',
      alt: 'Notre-Dame Cathedral Basilica in Ho Chi Minh City',
      caption: 'The basilica shows one of the colonial-era architectural layers inside the modern city.',
      creator: 'Steffen Schmitz',
      license: 'CC BY-SA 4.0',
      tags: ['notre-dame-basilica', 'architecture', 'history'],
    }),
    wikimediaMediaAsset({
      id: 'ho-chi-minh-city-bitexco-tower',
      kind: 'cityscape',
      title: 'Bitexco Financial Tower',
      difficulty: 'medium',
      fileName: 'DJI 0550-HDR-Pano Bitexco Financial Tower.jpg',
      alt: 'Bitexco Financial Tower in Ho Chi Minh City',
      caption: 'Bitexco Financial Tower shows Ho Chi Minh City through vertical growth and modern business districts.',
      creator: 'Le Minh Phat',
      license: 'CC BY-SA 4.0',
      tags: ['bitexco', 'skyline', 'growth'],
    }),
  ],
  ulaanbaatar: [
    wikimediaMediaAsset({
      id: 'ulaanbaatar-gandan-monastery',
      kind: 'landmark',
      title: 'Gandantegchinlen Monastery',
      difficulty: 'hard',
      fileName: 'Gandantegchinlen Monastery (2024).jpg',
      alt: 'Gandantegchinlen Monastery in Ulaanbaatar',
      caption: 'Gandantegchinlen Monastery shows Ulaanbaatar through Buddhist history and capital city life.',
      creator: 'Chongkian',
      license: 'CC BY-SA 4.0',
      spoilerRisk: 'high',
      tags: ['gandan', 'monastery', 'faith'],
    }),
    wikimediaMediaAsset({
      id: 'ulaanbaatar-ger-district',
      kind: 'street-scene',
      title: 'Ger District',
      difficulty: 'hard',
      fileName: 'Ger district of Ulaanbaatar.jpg',
      alt: 'Ger district housing on the northern hills of Ulaanbaatar',
      caption: 'Ger districts show migration, winter routines, housing pressure, and infrastructure needs.',
      creator: 'Quintin Soloviev',
      license: 'CC BY 4.0',
      tags: ['ger-district', 'housing', 'winter'],
    }),
    wikimediaMediaAsset({
      id: 'ulaanbaatar-sukhbaatar-square',
      kind: 'landmark',
      title: 'Sukhbaatar Square',
      difficulty: 'medium',
      fileName: 'Sukhbaatar Square, Ulaanbaatar, Mongolia (48788243773).jpg',
      alt: 'Sukhbaatar Square in Ulaanbaatar',
      caption: 'Sukhbaatar Square is a central civic space for government, gathering, and national symbols.',
      creator: 'Dan Nevill',
      license: 'CC BY 2.0',
      tags: ['sukhbaatar-square', 'civic-space', 'capital'],
    }),
  ],
};

function recordFromDestination(destination: DestinationPack): PlaceMediaRecord {
  const difficulty = destinationDifficulty(destination);
  return {
    id: destination.id,
    name: `${destination.city}, ${destination.country}`,
    city: destination.city,
    country: destination.country,
    region: destination.region,
    lat: destination.lat,
    lng: destination.lng,
    kind: 'city',
    difficulty,
    destinationId: destination.id,
    tags: [
      destination.primaryAirport,
      destination.region,
      destination.scene.terrain,
      destination.scene.skyline,
      ...(destination.scene.landmarkSilhouette ? [destination.scene.landmarkSilhouette] : []),
    ],
    media: [
      ...(CURATED_DESTINATION_MEDIA[destination.id] ?? []),
      mediaFromDestinationImage(destination),
    ],
  };
}

export const PLACE_MEDIA_LIBRARY: PlaceMediaRecord[] = WORLD_DESTINATIONS.map(recordFromDestination);

export function getPlaceMediaRecord(id: string) {
  return PLACE_MEDIA_LIBRARY.find((place) => place.id === id);
}

export function getPlaceMediaRecordByDestination(destinationId: string) {
  return PLACE_MEDIA_LIBRARY.find((place) => place.destinationId === destinationId);
}

export function getMediaForUsage(place: PlaceMediaRecord, usage: PlaceMediaUsage) {
  return place.media.filter((media) => media.usage.includes(usage) && (media.url || media.thumbnailUrl));
}

export function getLessonIntroMediaForDestination(destinationId: string) {
  const place = getPlaceMediaRecordByDestination(destinationId);
  return place ? getMediaForUsage(place, 'lesson-intro')[0] ?? null : null;
}

export function getRevealMediaForDestination(destinationId: string) {
  const place = getPlaceMediaRecordByDestination(destinationId);
  return place ? getMediaForUsage(place, 'reveal')[0] ?? null : null;
}

export function getWorldLensPlacePool() {
  return PLACE_MEDIA_LIBRARY.filter((place) => getMediaForUsage(place, 'geo-clue').length > 0);
}
