/** Reviewed, concrete sticker choices for each Focus briefing. Run once after editing this map. */
import fs from 'node:fs';

const choices: Record<string, string> = {
  cats: 'cat kitten mouse fish bed sofa',
  dogs: 'dog puppy ball walk park feed-the-dog',
  horses: 'horse foal farm farmer grass carrot',
  elephants: 'elephant tree water river grass zoo',
  giraffes: 'giraffe tree leaf grass zoo zebra',
  zebras: 'zebra grass lion tree zoo horse',
  lions: 'lion grass tree zoo tiger deer',
  tigers: 'tiger forest tree deer zoo lion',
  pandas: 'panda bear forest tree leaf zoo',
  koalas: 'koala tree leaf forest bear zoo',
  kangaroos: 'kangaroo baby grass tree zoo rabbit',
  penguins: 'penguin ice snow fish sea swim',
  'polar-bears': 'polar-bear ice snow sea fish cold',
  dolphins: 'dolphin sea fish swim boat wave',
  whales: 'whale sea fish boat water swim',
  sharks: 'shark sea fish boat swim teeth',
  'sea-turtles': 'turtle sea shell sand beach swim',
  frogs: 'frog lake rain water jump worm',
  butterflies: 'butterfly flower garden leaf bee ladybug',
  bees: 'bee flower honey garden tree butterfly',
  dinosaurs: 'dinosaur rock egg tree forest museum',
  fossils: 'dinosaur rock sand museum shovel cave',
  'the-moon': 'moon night sky star earth rocket',
  'the-sun': 'sun sky hot summer beach sunscreen',
  planets: 'planet earth moon star sun rocket',
  stars: 'star night sky moon sun planet',
  rockets: 'rocket astronaut moon planet sky star',
  astronauts: 'astronaut rocket moon planet earth star',
  volcanoes: 'volcano mountain fire rock island map',
  earthquakes: 'earth rock house road bridge mountain',
  mountains: 'mountain rock snow tree climb map',
  rivers: 'river water bridge fish boat waterfall',
  oceans: 'sea fish whale shark boat island',
  'coral-reefs': 'sea fish turtle shark octopus crab',
  rainforests: 'forest tree rain monkey parrot leaf',
  deserts: 'desert sand cactus camel sun hot',
  forests: 'forest tree leaf fox deer bird',
  seasons: 'spring summer autumn winter sun snow',
  rain: 'rain cloud raindrop umbrella puddle raincoat',
  snow: 'snow snowflake snowman ice mitten cold',
  wind: 'wind kite tree leaf cloud storm',
  clouds: 'cloud sky rain sun storm rainbow',
  rainbows: 'rainbow rain cloud sun sky puddle',
  'water-cycle': 'water sun cloud rain river sea',
  'plant-growth': 'seed seedling flower leaf tree watering-can',
  cooking: 'kitchen cook frying-pan spatula oven plate',
  baking: 'bake oven cake rolling-pin muffin sugar',
  fruits: 'apple banana orange grapes strawberry mango',
  vegetables: 'carrot broccoli potato tomato corn peas',
  breakfast: 'cereal milk egg bread pancake juice',
  'school-lunch': 'lunchbox sandwich apple water school table',
  'caring-for-pets': 'dog cat rabbit fish feed-the-dog water',
  'school-day': 'school classroom teacher desk book backpack',
  'classroom-rules': 'classroom teacher listen hand book tidy-up',
  'making-friends': 'friend smile talk play hug happy',
  'family-traditions': 'family mother father grandmother party cake',
  'birthday-parties': 'birthday cake balloon present party candle',
  'festivals-around-the-world': 'party flag drum dance cake family',
  holidays: 'airplane beach hotel camera family map',
  'jobs-people-do': 'doctor teacher chef pilot farmer firefighter',
  soccer: 'football goalpost ball kick stadium shoes',
  basketball: 'basketball ball throw catch stadium run',
  swimming: 'swim swimming-pool swimsuit water lifebuoy snorkel',
  cycling: 'bike ride-a-bike road park shoes seat-belt',
  running: 'run shoes park road foot stadium',
  dancing: 'dance singer drum clap party guitar',
  'board-games': 'board-game table friend play count marbles',
  puzzles: 'puzzle table blocks think play friend',
  'building-blocks': 'blocks build house toy-car play robot',
  kites: 'kite wind sky park beach flag',
  playgrounds: 'playground swing slide seesaw sandbox climbing-frame',
  superheroes: 'crown brave firefighter robot police-officer jump',
  robots: 'robot computer build toy-car lightbulb button',
  trains: 'train station road bridge driver tram',
  airplanes: 'airplane airport pilot sky map globe',
  boats: 'boat ship sailboat canoe river sea',
  'musical-instruments': 'drum guitar piano trumpet violin flute',
  drawing: 'draw pencil crayon paper artist eraser',
  painting: 'paint paintbrush paper artist crayon draw',
  'the-five-senses': 'eye ear nose mouth hand tongue',
  'video-games': 'video-game computer phone headphones friend robot',
  'game-design': 'video-game computer robot pencil paper puzzle',
  esports: 'video-game computer headphones microphone friend stadium',
  'social-media': 'phone camera friend take-a-photo talk',
  'online-privacy': 'phone computer camera',
  'screen-time': 'phone computer television clock book sleep',
  'digital-footprints': 'phone computer camera take-a-photo',
  'internet-memes': 'phone computer camera laugh friend',
  'artificial-intelligence': 'computer robot phone',
  'robots-and-automation': 'robot computer build car button lightbulb',
  'virtual-reality': 'headphones glasses video-game computer look',
  coding: 'computer robot button',
  cybersecurity: 'computer phone key',
  'online-learning': 'computer phone teacher book headphones notebook',
  'digital-art': 'computer phone paintbrush draw artist crayon',
  friendship: 'friend talk smile hug play happy',
  'peer-pressure': 'friend worried scared talk brave',
  teamwork: 'friend ball build talk listen carry',
  'music-genres': 'guitar drum piano singer headphones dance',
  'live-music': 'singer microphone guitar drum stadium clap',
  songwriting: 'singer microphone piano guitar notebook pen',
  'film-genres': 'cinema camera television scared laugh popcorn',
  'film-making': 'camera cinema microphone lightbulb draw',
  fashion: 'shirt dress jeans shoes hat jacket',
  'personal-style': 'shirt jeans jacket shoes glasses hat',
  'food-culture': 'rice noodles bread chopsticks plate family',
  'cooking-skills': 'cook knife frying-pan spatula oven plate',
  'language-learning': 'book pen talk listen teacher friend',
  'travel-etiquette': 'airplane hotel map talk smile bag',
  'local-traditions': 'family party cake dance flag drum',
  exams: 'school pen paper book desk clock',
  homework: 'notebook pencil book desk school clock',
  'school-clubs': 'school friend ball guitar book robot',
  'part-time-jobs': 'shop restaurant chef coin clock driver',
  'future-jobs': 'doctor teacher robot computer chef pilot',
  entrepreneurship: 'shop coin computer calculator',
  'money-and-saving': 'coin box shop basket count',
  budgeting: 'coin calculator notebook shop',
  volunteering: 'friend park tree shovel bag sweep',
  'public-speaking': 'microphone talk classroom teacher friend clap',
  'study-habits': 'book notebook pen clock desk pencil',
  'sleep-and-learning': 'bed pillow blanket clock book sleep',
  'choosing-subjects': 'book school teacher calculator paintbrush globe',
  'gap-years': 'bag airplane map hotel camera train',
  'career-skills': 'computer talk listen book clock notebook',
  'climate-change': 'earth sun storm ice tree snow',
  'renewable-energy': 'sun wind water lightbulb earth river',
  'plastic-waste': 'bottle bag sea fish beach turtle',
  'wildlife-conservation': 'forest tree elephant tiger bird panda',
  'urban-nature': 'city park tree bird garden flower',
  'public-transport': 'bus train tram station road taxi',
  'cities-of-the-future': 'city robot bus tree computer tram',
  'space-exploration': 'rocket astronaut moon planet star earth',
  'mars-missions': 'rocket astronaut planet rock map earth',
  satellites: 'rocket earth planet star computer moon',
  inventions: 'lightbulb robot computer bike hammer magnet',
  'medical-technology': 'hospital doctor nurse thermometer wheelchair bandage',
  'food-waste': 'apple banana plate basket bread carrot',
  'sustainable-fashion': 'shirt jeans jacket shoes button dress',
  'water-conservation': 'water sink shower river bottle rain',
  'team-sports': 'football basketball ball goalpost friend stadium',
  'solo-sports': 'run swim bike tennis shoes racket',
  fitness: 'run jump swim bike water shoes',
  'outdoor-adventures': 'mountain forest tent rope map climb',
  'mysteries-and-clues': 'key flashlight map door box envelope',
  'unexplained-places': 'cave castle island mountain map forest',
  'optical-illusions': 'eye mirror circle look glasses triangle',
  'healthy-eating': 'apple carrot water salad bread fish',
  'stress-management': 'worried tired sleep walk friend smile',
  'travel-planning': 'map bag airplane hotel camera train',
};

const file = 'src/data/topic-briefings.json';
const text = fs.readFileSync(file, 'utf8');
const topics = JSON.parse(text) as { id: string; title: string; pictureWords?: string[] }[];
const stickers = new Set((JSON.parse(fs.readFileSync('src/data/sticker-words.json', 'utf8')) as { id: string }[]).map((row) => row.id));
if (topics.length !== 150) throw new Error(`Expected 150 topics, found ${topics.length}`);
const missing: string[] = [];
const invalid: string[] = [];
let output = text;
for (const topic of topics) {
  const key = topic.id.replace(/^topic-(?:kids|teens)-/, '');
  const words = choices[key]?.split(' ') || [];
  if (!choices[key]) missing.push(topic.id);
  if (words.length < 3 || words.length > 10 || words.some((word) => !stickers.has(word)) || new Set(words).size !== words.length) {
    invalid.push(`${topic.id}: ${words.filter((word) => !stickers.has(word)).join(', ')}`);
    continue;
  }
  const titleLine = `"id": "${topic.id}",\\r?\\n    "title": "${topic.title.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}",`;
  const pattern = topic.pictureWords === undefined
    ? new RegExp(`(${titleLine})(\\r?\\n)`)
    : new RegExp(`(${titleLine}\\r?\\n    "pictureWords": )\\[[^\\]]*\\]`);
  if (!pattern.test(output)) throw new Error(`Could not find words position for ${topic.id}`);
  output = output.replace(pattern, topic.pictureWords === undefined
    ? `$1$2    "pictureWords": ${JSON.stringify(words)},$2`
    : `$1${JSON.stringify(words)}`);
}
if (missing.length || invalid.length) throw new Error(`Missing maps: ${missing.join(', ')}; invalid IDs: ${invalid.join('; ')}`);
fs.writeFileSync(file, output);
console.log(`Added pictureWords to ${topics.length} topics.`);
