/** Author the second 60 checked motions. Sources are mapped in docs/library-round-14-debate-sources.md. */
import fs from 'node:fs';

type Level = 'K' | 'B' | 'C';
type Spec = [string, string, Level, string, string, string, string, string, string];
const sources: Record<string, [string, string]> = {
  READ: ['UNICEF, How to Teach Your Child to Love Reading', 'https://www.unicef.org/parenting/child-care/teach-your-child-to-love-reading'],
  ART: ['UNESCO, State of the Education Report for India 2024', 'https://www.unesco.org/en/articles/state-education-report-india-2024'],
  PET: ['CDC, Ways to Stay Healthy Around Animals', 'https://www.cdc.gov/healthy-pets/about/index.html'],
  DIET: ['WHO, Healthy Diet', 'https://www.who.int/news-room/fact-sheets/detail/healthy-diet'],
  MEAL: ['USDA, School Nutrition and Meal Cost Study', 'https://www.fna.usda.gov/research/school-meals/nutrition-meal-cost-study'],
  PLAY: ['UNICEF, The Power of Play', 'https://data.unicef.org/resources/the-power-of-play/'],
  FOODSAFE: ['CDC, Handwashing as a Healthy Habit in the Kitchen', 'https://www.cdc.gov/clean-hands/prevention/about-handwashing-a-healthy-habit-in-the-kitchen.html'],
  LOCAL: ['USDA, Locally Produced Foods in School Districts', 'https://ers.usda.gov/data-products/charts-of-note/104505'],
  MEALCOST: ['USDA, School Foodservice Costs: Location Matters', 'https://www.ers.usda.gov/publications/44845'],
  PLATE: ['USDA, Plate Waste in School Nutrition Programs', 'https://ers.usda.gov/publications/43132'],
  COOK: ['USDA NIFA, Family Nutrition Education', 'https://www.nifa.usda.gov/about-nifa/impacts/efnep-taking-charge-health-one-lesson-one-meal-one-family-time'],
  BIKE: ['CDC, Bicycle Safety', 'https://cdc.gov/pedestrian-bike-safety/about/bicycle-safety.html'],
  ACTIVE: ['CDC, Health Benefits of Physical Activity for Children', 'https://www.cdc.gov/physical-activity-basics/health-benefits/children.html'],
  SCHOOLACT: ['CDC, Physical Education and Activity Strategies', 'https://www.cdc.gov/whole-school-community-child/strategies/strategies-physical-education-and-activity.html'],
  BREAK: ['CDC, Classroom Physical Activity Breaks', 'https://www.cdc.gov/physical-activity-education/media/pdfs/PA_breaks_508.pdf'],
  ROUTE: ['CDC, Safe Routes to School', 'https://archive.cdc.gov/www_cdc_gov/policy/hi5/saferoutes/index.html'],
  DIGITAL: ['UNICEF Innocenti, Childhood in a Digital World', 'https://www.unicef.org/innocenti/reports/childhood-digital-world'],
  OUTDOOR: ['US EPA, EnviroAtlas Educational Materials', 'https://www.epa.gov/enviroatlas/enviroatlas-educational-materials'],
  POLL: ['USDA NRCS, Pollinator Biology and Habitat', 'https://www.nrcs.usda.gov/plantmaterials/mipmctn11774.pdf'],
  DARK: ['US National Park Service, Night Sky-Friendly Lighting', 'https://www.nps.gov/zion/learn/nature/night_friendly_lighting.htm'],
  VOICE: ['UNICEF, Meaningful Consultations with Young People', 'https://www.unicef.org/youthledaction/documents/meaningful-consultations-young-people'],
  MUSEUM: ['UNESCO, Recommendation on Museums and Collections', 'https://www.unesco.org/en/legal-affairs/recommendation-concerning-protection-and-promotion-museums-and-collections-their-diversity-and-their'],
  NASAIMAGE: ['NASA Earthdata, Land Processes Archive', 'https://www.earthdata.nasa.gov/centers/lp-daac'],
  NASABEN: ['NASA, Why Go to Space', 'https://www.nasa.gov/humans-in-space/why-go-to-space/'],
  NASARISK: ['NASA, Risks of Human Spaceflight', 'https://www.nasa.gov/hrp/risks/'],
  TRANSPORT: ['WHO, Safe Environments and Mobility', 'https://www.who.int/tools/compendium-on-health-and-environment/safe-environments-and-mobility'],
  TOURISM: ['UNESCO, World Heritage Sustainable Tourism Toolkit', 'https://whc.unesco.org/en/sustainabletourismtoolkit/guide4/'],
  TOURISMRISK: ['UNESCO World Heritage Committee, Tourism Impacts', 'https://whc.unesco.org/en/compendium/341'],
  INTERNSHIP: ['ILO, Internships: Head Start or Labour Trap?', 'https://www.ilo.org/resource/article/internships-head-start-or-labour-trap'],
  APPRENTICE: ['ILO, Quality Apprenticeships Recommendation 2023', 'https://www.ilo.org/resource/other/r208-quality-apprenticeships-recommendation-2023'],
  MEDIA: ['UNESCO, Media and Information Literacy for Global Communication and Learning', 'https://www.unesco.org/en/media-information-literacy/global-communication-learning'],
  OER: ['UNESCO, Open Educational Resources Guidance', 'https://www.unesco.org/en/articles/guidelines-open-educational-resources-oer-higher-education'],
  LIBRARY: ['ALA YALSA, The Need for Teen Spaces in Public Libraries', 'https://www.ala.org/yalsa/guidelines/whitepapers/teenspaces'],
  ENERGY: ['IEA, Integrating Solar and Wind', 'https://www.iea.org/reports/integrating-solar-and-wind/executive-summary'],
  WATER: ['WHO, Drinking-Water Guidelines', 'https://www.who.int/news-room/questions-and-answers/item/guidelines-for-drinking-water-quality---frequently-asked-questions'],
  REUSE: ['WHO, Potable Reuse Guidance', 'https://www.who.int/publications/i/item/9789241512770'],
  CITIZEN: ['NASA, GLOBE Citizen Science Data Quality', 'https://ntrs.nasa.gov/citations/20200000257'],
  REPAIR: ['US EPA, Sustainable Materials Management Hierarchy', 'https://www.epa.gov/smm/sustainable-materials-management-non-hazardous-materials-and-waste-management-hierarchy'],
  BATTERY: ['US EPA, Lithium-Ion Battery Recycling FAQ', 'https://www.epa.gov/hw/lithium-ion-battery-recycling-frequently-asked-questions'],
  FIRSTAID: ['WHO, Improving Care of the Injured', 'https://www.who.int/activities/improving-care-of-the-injured'],
  LITERACY: ['WHO, Health Literacy', 'https://www.who.int/vietnam/news/fact-sheets/detail/health-literacy'],
  NOISE: ['WHO, Environmental Noise Guidance', 'https://www.who.int/tools/compendium-on-health-and-environment/environmental-noise/'],
};
const specs: Spec[] = [
  // motion, topic, cohort, three for points, three against points, pro fact/source, con fact/source
  ['Every class should have a reading corner','books','K','Books are easy to reach|Quiet reading helps children settle|Classmates can share stories','A corner takes classroom space|Some pupils prefer moving while reading|Books need care and replacement','UNICEF says reading together supports vocabulary and speaking confidence.','READ','UNICEF advises making reading enjoyable and suited to each child, rather than forcing one routine.','READ'],
  ['Children should pick one library book every week','books','K','Choice can make reading fun|A new book brings new words|Libraries let children try different stories','A weekly deadline may rush slow readers|Some children want to reread favourites|Not every family can reach a library','UNICEF says letting children choose books helps build a love of reading.','READ','UNICEF advises reading at a child’s pace and rereading favourite books.','READ'],
  ['Teachers should read stories aloud every day','stories','K','Everyone hears rich new words|Children can ask about the story|A shared story starts conversation','Children also need time to read alone|Daily reading aloud uses lesson time|One book may not suit every learner','UNICEF says reading aloud builds speech and vocabulary.','READ','UNICEF recommends letting children participate and choose books they enjoy.','READ'],
  ['Class plays should have parts for everyone','stories','K','Every child can take part|Acting gives stories a voice|Small roles can build confidence','Some children dislike performing|Planning many roles takes time|Behind-the-scenes jobs also matter','UNESCO reports that arts education can build creativity and inclusion.','ART','UNESCO says good arts programmes require teaching capacity and resources.','ART'],
  ['Children should draw their own story endings','stories','K','Drawing lets quiet pupils share ideas|There can be many creative endings|Pictures help explain a story','The original ending may be important|Some pupils prefer speaking or writing|Drawing can take extra time','UNESCO says arts education supports creativity and different forms of expression.','ART','UNESCO calls for clear learning goals and ways to assess arts education.','ART'],
  ['Every family should have a pet','pets','K','Pets can be good companions|Caring for an animal teaches routines|Playing with pets gets people moving','Pets need time and money|Some families have allergies|Animals can carry germs','CDC says pets can increase opportunities for exercise and companionship.','PET','CDC warns that even healthy-looking pets can carry germs that make people sick.','PET'],
  ['Schools should allow a class pet','pets','K','Children can learn daily care|Watching an animal can spark questions|The class could share duties','Some children have allergies|Animals need care on holidays|Noise may upset an animal','CDC says pets can increase opportunities to socialize and spend time outdoors.','PET','CDC says children should wash hands after handling animals because pets can carry germs.','PET'],
  ['Families should research a pet before adopting','pets','K','They can choose a suitable animal|They can plan daily care|They can check health needs','Research takes time|A shelter can answer questions|Families may still need to meet the pet','CDC advises choosing pets that fit a family’s health and lifestyle.','PET','CDC warns that even healthy-looking animals can carry germs.','PET'],
  ['Schools should offer water with every lunch','food','K','Water is easy to drink with food|It avoids added sugar|Children can refill a bottle','Schools need clean taps|Some pupils prefer milk|Bottles and cups need washing','WHO recommends limiting free sugars in a healthy diet.','DIET','USDA school meal rules include milk among required meal components.','MEAL'],
  ['Children should help prepare one family meal weekly','food','K','They can learn food skills|Cooking gives families time together|Children may try new foods','Hot tools need adult supervision|Families may be busy|Young children need simple jobs','USDA reports that youth nutrition lessons helped participants learn food preparation.','COOK','CDC says handwashing during food preparation helps prevent cross-contamination.','FOODSAFE'],
  ['School lunches should include a local fruit','food','K','Children can discover nearby farms|Fresh fruit adds variety|Schools can support local growers','Local fruit changes with seasons|It may cost more in some places|Children still need other foods','USDA reports that local fruit is a common farm-to-school food.','LOCAL','USDA reports that food prices vary across places and affect meal costs.','MEALCOST'],
  ['Children should choose between two lunch sizes','food','K','Small eaters waste less|Hungry pupils can choose more|Choice respects different appetites','A small meal may leave someone hungry|Servers need extra planning|Balanced meals still matter','USDA identifies tailoring serving sizes to appetites as a possible way to reduce plate waste.','PLATE','USDA says schools must serve meals that meet nutrition requirements.','MEAL'],
  ['Schools should teach safe cycling in PE','sport','K','Children learn road rules|Riding gives active travel choices|Helmets become a habit','Not every child has a bicycle|Schools need safe practice space|Walking skills matter too','CDC says Safe Routes programmes can make walking and cycling to school safer.','BIKE','CDC says cycling injuries remain a risk and correctly fitted helmets reduce head injury.','BIKE'],
  ['Every child should try a team game','sport','K','Games teach cooperation|Children can make friends|Movement supports health','Some pupils prefer solo activities|Teams can leave children out|Choice keeps sport enjoyable','CDC says physical activity benefits children’s brain and body health.','ACTIVE','CDC recommends offering varied physical activity opportunities, not only team sport.','SCHOOLACT'],
  ['Schools should hold a weekly dance break','sport','K','Dancing can be active fun|No team needs to win|Music can change the mood','Some pupils dislike public dancing|Noise may disturb another class|There are other ways to move','CDC says classroom activity breaks can improve attention and physical activity.','BREAK','CDC lists recess, PE, clubs and active travel as different ways to be active.','SCHOOLACT'],
  ['Children should walk short school trips','sport','K','Walking adds daily movement|The class can notice its area|Fewer vehicles stop outside school','Roads may be unsafe|Some pupils cannot walk that distance|Weather can change plans','CDC says safe walking routes can support physical activity.','ROUTE','CDC says traffic safety concerns and missing sidewalks can stop children walking to school.','ROUTE'],
  ['Family game night should happen every week','games','K','Families can talk while playing|Games give everyone a turn|No screen is needed','Schedules are different|Some families prefer other activities|Weekly rules may feel forced','UNICEF says play with caregivers can support learning and relationships.','PLAY','UNICEF says play takes many forms and should follow children’s interests.','PLAY'],
  ['Digital games should count as play','games','K','Some games invite creative choices|Friends can cooperate online|Children may learn new skills','Some games push purchases|Long sessions replace movement|Online spaces need safety rules','UNICEF reports that digital games can offer active, social and creative play.','PLAY','UNICEF warns that games may include in-game purchases or hidden advertising.','PLAY'],
  ['Schools should lend board games at break','games','K','More children can try games|Games can start friendships|A rainy break has options','Pieces can get lost|Not everyone enjoys board games|Staff need to manage lending','UNICEF says different kinds of play support social skills.','PLAY','UNICEF says children need varied play choices, including active play.','PLAY'],
  ['Parents should choose children’s screen time together','screens','K','A shared rule can be clear|Children can explain their needs|Families can plan other activities','One rule may not fit every day|School work uses screens too|Older children need some independence','UNICEF says family conversation helps children use digital spaces safely.','DIGITAL','UNICEF warns that strict time limits alone miss the quality and context of digital use.','DIGITAL'],
  ['Children should be allowed to keep a nature diary','nature','K','They can notice seasonal change|Drawing makes observation fun|A diary helps remember discoveries','Not every child likes writing|Outdoor access differs|Teachers need time to discuss entries','US EPA provides outdoor ecosystem lessons that use observation of local places.','OUTDOOR','US EPA notes that outdoor lessons need attention to local environmental conditions.','OUTDOOR'],
  ['Classes should plant flowers for insects','nature','K','Flowers can help pollinators|Children see life cycles nearby|A small space can be useful','Plants need water and care|Some pupils fear insects|Local plants must be chosen carefully','USDA says pollinators help many flowering plants reproduce.','POLL','USDA advises choosing plants suited to local conditions for pollinator habitat.','POLL'],
  ['Schools should turn off outdoor lights earlier','nature','K','Darker nights help some animals|Schools use less electricity|Children can learn about night nature','Paths still need safe lighting|Some events finish late|A timer may be needed','US National Park Service says artificial light can disrupt nocturnal wildlife.','DARK','US National Park Service recommends using lighting where needed for safety.','DARK'],
  ['Families should take one screen-free walk weekly','home','K','A walk gives time to talk|Movement is healthy|Children can notice local nature','Some families have unsafe routes|Weather may be difficult|Other shared activities also count','CDC says regular physical activity benefits children’s health.','ACTIVE','CDC says access to safe walking spaces differs by community.','ROUTE'],
  ['Children should help set one family rule','home','K','Children can explain what feels fair|They may follow a rule they helped make|Adults hear different needs','Adults must keep children safe|Some decisions are too complex|Rules may need to change quickly','UNICEF guidance calls for children’s views to be heard in decisions affecting them.','VOICE','UNICEF guidance says adults retain responsibility for children’s safety and wellbeing.','VOICE'],
  ['Holidays should include a local day trip','holidays','K','Families can explore nearby places|Travel time stays short|Local visits may cost less','Some families need rest at home|Transport may still cost money|A trip is not the only adventure','UNESCO says museums support informal learning and community education.','MUSEUM','UNESCO says museums need resources for collection care and education, so visits require planning.','MUSEUM'],
  ['Children should help plan a holiday day','holidays','K','Their interests get heard|Planning can teach choices|Families can compare activities','Adults know the budget|Plans need to be safe|Not every wish can fit one day','UNICEF guidance says young people’s participation works when adults listen seriously.','VOICE','UNICEF guidance says participation needs time, preparation and practical support.','VOICE'],
  ['Space lessons should show real satellite images','space','K','Images show Earth from above|Children can ask new questions|Real data can make science exciting','Images need explanation|Not every image is easy to read|Models and experiments also help','NASA provides Earth-observation data and imagery for learning and research.','NASAIMAGE','NASA says satellite data need interpretation and validation before use.','NASAIMAGE'],
  ['Children should design a pretend Moon base','space','K','Designing encourages imagination|Teams can solve a problem|The Moon becomes less abstract','Pretend designs can miss real limits|Building takes materials|Science facts still need checking','NASA says exploration drives new technology and scientific questions.','NASABEN','NASA identifies radiation, isolation and other hazards that real Moon crews must address.','NASARISK'],
  ['Superhero stories should include ordinary helpers','stories','K','Children see everyday courage|Helpers can work as a team|More characters can join in','A fantasy hero can be fun|Stories need clear focus|Not every tale needs a lesson','UNESCO says arts education can foster empathy and social connection.','ART','UNESCO says artistic expression should leave room for creativity and cultural diversity.','ART'],
  ['Cities should make buses free for teenagers','transport','B','More teens could reach activities|Families would save fares|A bus can replace a car ride','Bus services still need funding|Crowded routes need more vehicles|Safety and access matter beyond price','WHO says public transport can improve access to education for people without cars.','TRANSPORT','WHO says transport health also depends on road safety, noise and air pollution, not fares alone.','TRANSPORT'],
  ['Cities should charge for busy road space','transport','C','Less congestion can speed buses|Charges could fund better transit|Cleaner air helps residents','Charges can burden some drivers|Good alternatives are needed first|Delivery workers may need exceptions','WHO identifies travel-demand management as one route to cleaner, healthier urban transport.','TRANSPORT','WHO says transport policy must account for equitable access to work, health care and education.','TRANSPORT'],
  ['Museums should offer free entry to teenagers','museums','B','More teens could visit|Families could try a museum together|History becomes easier to explore','Museums must pay for staff|Collections need protection|Free entry alone may not solve travel barriers','UNESCO says museums provide formal and informal education for young people.','MUSEUM','UNESCO says conservation, security and collection management require resources.','MUSEUM'],
  ['Museums should lend objects to local schools','museums','C','Students could study real objects|Schools far away could participate|Loans may inspire later visits','Fragile objects can be damaged|Staff must track and insure loans|Digital copies may be safer','UNESCO recommends museum partnerships with schools for educational programmes.','MUSEUM','UNESCO says collections require security, risk analysis and preventive conservation.','MUSEUM'],
  ['Visitors should choose local guides on heritage trips','tourism','B','Local people can earn income|Guides know community stories|Visitors may learn respectful behaviour','Guided trips can cost more|Visitors may want independence|Guides need training and fair work','UNESCO says locally involved tourism can create economic benefits for communities.','TOURISM','UNESCO warns tourism growth must respect limits that protect heritage and residents.','TOURISM'],
  ['Popular heritage sites should limit daily visitors','tourism','C','Crowding can damage places|Visitors may enjoy calmer visits|Residents keep access to their area','Limits can cut local earnings|Tickets may become hard to get|Good crowd management may work instead','UNESCO reports that overcrowding, congestion and tourism infrastructure increasingly harm some heritage sites.','TOURISMRISK','UNESCO says tourism can create jobs and income for local communities when managed sustainably.','TOURISM'],
  ['Teen internships should always be paid','work','B','Pay makes placements fairer|Teens can cover travel costs|Work has value','Small groups may offer fewer places|Training must remain the main goal|Some short observation visits are different','ILO warns that unpaid internships can be abused and exclude young people without financial support.','INTERNSHIP','ILO distinguishes internships with strong training from jobs that displace paid workers.','INTERNSHIP'],
  ['Schools should expand apprenticeships instead of exams','work','C','Learning at work builds skills|Students see different careers|Employers can offer feedback','Core knowledge still needs checking|Placement quality can vary|Not every career has a local employer','ILO says quality apprenticeships combine training with real work experience.','APPRENTICE','ILO stresses that apprenticeships need regulation, social protection and quality assurance.','APPRENTICE'],
  ['News lessons should teach misleading images','media','B','Students can check visual claims|Edited images spread quickly|A picture needs context','Lessons need careful examples|Skills must cover text and sound too|Teachers need support','UNESCO’s media-literacy guidance includes checking information and responding to misinformation.','MEDIA','UNESCO says media literacy spans many formats and requires educator capacity, not image lessons alone.','MEDIA'],
  ['Platforms should label edited news images','media','C','Labels help viewers pause|Sources become easier to question|Clear labels can reduce confusion','Editing can be harmless|A label cannot verify the whole story|False confidence is possible','UNESCO says media and information literacy must address disinformation and digital manipulation.','MEDIA','UNESCO says users also need skills to judge sources and context; a platform label is not a full check.','MEDIA'],
  ['Libraries should stay open after school','libraries','B','Teens get a quiet place|Books and computers are shared|Friends can study together','Staff need safe working hours|Buildings cost money to run|Some pupils need transport home','ALA calls libraries informal learning spaces that bridge school and after-school time.','LIBRARY','ALA says teen library space must be designed around local needs, priorities and budgets.','LIBRARY'],
  ['Libraries should offer printed and digital lessons','libraries','C','Different learners get choices|Printed pages work offline|Digital copies can be updated','Two formats cost more to maintain|Devices may be missing|Licences can limit sharing','ALA recommends teen library spaces include both print and digital collections.','LIBRARY','UNESCO says hardware, connectivity and quality assurance remain challenges for digital learning.','OER'],
  ['School trips should offer accessible routes','accessibility','B','More classmates can join|Planning helps the whole group|Routes can be checked early','Some sites need major changes|Transport options may be limited|Staff need extra planning','WHO says accessible transport improves independent access to education and leisure.','TRANSPORT','WHO notes that safe, equitable mobility requires suitable infrastructure and transport services.','TRANSPORT'],
  ['Cities should give accessible information at every transit stop','accessibility','C','More riders can travel alone|Clear signs help visitors too|Audio and text offer choice','Equipment needs upkeep|Small stops have limited space|Information must stay accurate','WHO says transport access is particularly important for people with disabilities.','TRANSPORT','WHO says equitable mobility requires infrastructure and services, so information alone is insufficient.','TRANSPORT'],
  ['Schools should use free satellite images in science','space','B','Students see real patterns|Local change can be observed|Data may spark questions','Images need interpretation|Some schools lack devices|Hands-on experiments still matter','NASA makes Earth imagery and data available for education and research.','NASAIMAGE','NASA explains that Earth-observation data need interpretation and validation.','NASAIMAGE'],
  ['More space budgets should support Earth observation','space','C','Satellites track changes on Earth|Data can aid research|Weather services use space data','Human missions also produce discoveries|Budgets have different goals|Space systems need long-term upkeep','NASA says Earth-observation data support research, education and decision-making.','NASAIMAGE','NASA says human exploration produces research and technologies with Earth applications.','NASABEN'],
  ['Schools should install solar panels when roofs allow','energy','B','Solar power can cut grid use|Students can monitor output|The roof becomes a lesson','Roofs may need repair|Upfront costs can be high|Power is lower at night','IEA says solar and wind can reduce fossil-fuel dependence when integrated well.','ENERGY','IEA says weather-dependent solar supply requires grid flexibility and sometimes storage.','ENERGY'],
  ['Cities should pair new solar projects with storage','energy','C','Stored power helps after sunset|Supply becomes more flexible|Less clean power is wasted','Storage adds cost|Other flexibility tools may work|Batteries need materials and management','IEA says storage is one option for integrating variable solar and wind power.','ENERGY','IEA says grid upgrades, flexible generation and demand response can also balance variable supply.','ENERGY'],
  ['Public places should offer water refill points','water','B','People can refill bottles|Less packaging is needed|Water becomes easier to find','Taps need cleaning and tests|Installation costs money|Some places already have fountains','WHO says safe drinking-water supplies protect public health.','WATER','WHO says water safety depends on reliable treatment, monitoring and maintenance.','WATER'],
  ['Cities should reuse treated water for public gardens','water','C','Gardens need less drinking water|Cities can conserve supplies|Reuse can fit dry periods','Treatment must be reliable|Pipes and checks cost money|Some sites need different water quality','WHO says safely treated wastewater can be a useful resource when managed to protect health.','REUSE','WHO says wastewater reuse requires risk management because untreated water can carry hazards.','REUSE'],
  ['Students should collect local weather observations','science','B','Real data make science concrete|Classes can compare seasons|A group can share tasks','Readings can be inaccurate|Equipment may cost money|Short projects miss long patterns','NASA citizen-science projects let volunteers contribute observations to research.','CITIZEN','NASA explains that citizen-science data need clear instructions and quality checks.','CITIZEN'],
  ['Citizen science projects should publish their methods','science','C','Others can check results|Volunteers learn careful practice|Projects gain trust','Writing methods takes time|Some personal data need protection|A method alone does not ensure quality','NASA says citizen science expands research by involving public observations.','CITIZEN','NASA says project teams must train volunteers and check data quality.','CITIZEN'],
  ['Shops should give customers simple repair guides','repair','B','People can keep products longer|Small faults may be fixed|Guides make parts easier to find','Some repairs are unsafe|Instructions cost time to write|Warranty rules can be complex','US EPA ranks reuse and repair above disposal in its materials-management hierarchy.','REPAIR','US EPA warns that damaged lithium-ion batteries require special handling because of fire risk.','BATTERY'],
  ['Products should show likely repair costs at purchase','repair','C','Buyers can compare lasting value|Costs become more transparent|Repairable goods may sell better','Future prices can change|Some faults are unpredictable|Small shops need fair rules','US EPA says source reduction and reuse avoid waste before recycling is needed.','REPAIR','US EPA says battery repair and recycling can involve safety and handling requirements.','BATTERY'],
  ['Every town should offer free public art walks','public-art','B','Residents discover local artists|Families can join at no cost|Streets tell community stories','Routes need safe access|Art needs care|Not everyone enjoys guided walks','UNESCO says culture and arts education can strengthen community connection.','ART','UNESCO says arts access needs teaching capacity, funding and suitable local resources.','ART'],
  ['Cities should reserve wall space for community murals','public-art','C','Artists gain legal space|Residents can share stories|Murals can enliven streets','Walls need owner agreement|Paint needs upkeep|Public space serves many uses','UNESCO says artistic expression and cultural participation can support social cohesion.','ART','UNESCO calls for resources and local planning when arts programmes use shared public space.','ART'],
  ['Schools should teach practical first aid','health','B','Students can respond calmly|Small injuries happen often|Practice makes steps memorable','Training takes class time|Skills need updating|Adults still carry responsibility','WHO says basic first-aid knowledge helps people respond to injuries before professional help arrives.','FIRSTAID','WHO advises seeking trained medical care for serious injuries; first aid has limits.','FIRSTAID'],
  ['Public health messages should use two reading levels','health','C','More people can understand advice|Clear language helps quick decisions|Teens and adults have different needs','Two versions take staff time|Translation may matter more|No single reading level fits all','WHO says health literacy affects people’s ability to find and use health information.','LITERACY','WHO says health communication must also consider language, culture and access barriers.','LITERACY'],
  ['School streets should have quiet traffic hours','noise','B','Less traffic noise helps nearby people|Walking can feel calmer|Drivers learn a simple schedule','Families may need vehicle access|Traffic may move to another street|Rules need enforcement','WHO identifies traffic noise as a health concern in urban areas.','NOISE','WHO says transport also provides access to education and services, so changes need equitable planning.','TRANSPORT'],
  ['Cities should map noise before adding major roads','noise','C','Planners can spot exposed homes|Designs can change early|Residents get useful information','Mapping takes time and money|Maps cannot predict every change|Roads may still be needed','WHO environmental-noise guidance links transport noise to sleep and health effects.','NOISE','WHO says transport supports access to jobs, health care and education, so decisions must weigh mobility needs.','TRANSPORT'],
];

function main() {
  const existing = JSON.parse(fs.readFileSync('src/data/debate-motions.json', 'utf8')) as Array<{ id: string; motion: string }>;
  const bank = existing.filter((entry) => entry.id.indexOf('debate-r14-') !== 0);
  if (bank.length !== 60) throw new Error(`Expected 60 existing motions, found ${bank.length}`);
  if (specs.length !== 60) throw new Error(`Expected 60 new motions, found ${specs.length}`);
  const seen = new Set(bank.map((entry) => entry.motion.toLowerCase()));
  const added = specs.map(([motion, topic, cohort, forText, againstText, forFact, forSource, againstFact, againstSource], index) => {
    if (seen.has(motion.toLowerCase())) throw new Error(`Repeated motion: ${motion}`);
    seen.add(motion.toLowerCase());
    const forPoints = forText.split('|');
    const againstPoints = againstText.split('|');
    if (forPoints.length !== 3 || againstPoints.length !== 3) throw new Error(`Wrong argument count: ${motion}`);
    if (!sources[forSource] || !sources[againstSource]) throw new Error(`Unknown source for ${motion}`);
    return {
      id: `debate-r14-${String(index + 1).padStart(2, '0')}`, motion, topics: [topic],
      ageBand: cohort === 'K' ? 'kids' : 'teens', cefr: cohort === 'K' ? 'A2' : cohort === 'B' ? 'B1' : 'B2',
      forPoints, againstPoints,
      evidence: [{ fact: forFact, side: 'for', source: sources[forSource][0] }, { fact: againstFact, side: 'against', source: sources[againstSource][0] }],
      pulse: `Do you think ${motion.charAt(0).toLowerCase()}${motion.slice(1)}?`,
    };
  });
  if (process.argv.indexOf('--write') !== -1) {
    fs.writeFileSync('src/data/debate-motions.json', JSON.stringify([...bank, ...added], null, 2) + '\n');
    const used = new Set(specs.flatMap((entry) => [entry[6], entry[8]]));
    const rows = Object.keys(sources).filter((key) => used.has(key)).map((key) => `| ${sources[key][0]} | [Primary source](${sources[key][1]}) |`);
    fs.writeFileSync('docs/library-round-14-debate-sources.md', '# Round 14 debate evidence sources\n\nEvidence facts are paraphrases of the named primary sources. The side label indicates which argument the fact helps the class discuss; it does not claim the source endorses every motion.\n\n| Named source in bank | Link |\n| --- | --- |\n' + rows.join('\n') + '\n');
  }
  console.log(`Prepared ${added.length} motions: kids A2 ${added.filter((item) => item.ageBand === 'kids').length}, teens B1 ${added.filter((item) => item.cefr === 'B1').length}, teens B2 ${added.filter((item) => item.cefr === 'B2').length}.`);
}
main();
