/** Scene endings replacing explicit morals in the four Aesop lessons. */
export const fableEndings: Record<string, {A2:string;B1:string}> = {
  'book-aesop-1': {
    A2:`The mouse reached the net and looked at the thick ropes around the lion. It could not lift the net, but it could bite one strand at a time. The lion stopped pulling so the small animal could work. The mouse held a rope between its teeth and chewed until the strand broke. It moved to another and did the same thing. Slowly a hole opened. The lion pushed his head through it, then his shoulders. At last he stepped out onto the forest floor. The mouse was still beside the broken ropes. The lion looked down at the animal he had once held in one paw. He thanked it for coming when he called. The mouse reminded him of the day he had let it go. They left the hunters’ net behind, walking away from the place where the lion had been trapped.`,
    B1:`The mouse ran to the edge of the net while the lion pulled at it again. The ropes only tightened, so he held still and let the smaller animal work. The mouse chose a strand, bit through it, then began on the next. Its teeth were small, but they could cut where the lion’s paws could not reach. One by one the ropes gave way. When the gap was wide enough, the lion pushed his head and shoulders through and climbed free. He stood beside the mouse, looking back at the net that had held him. He thanked the animal whose promise he had once found amusing. The mouse had remembered the open paw and the chance to leave safely. Now the lion could walk away because the mouse had returned. The two left the broken net on the ground and went back into the forest.`,
  },
  'book-aesop-2': {
    A2:`The wolf came closer to the lamb after each answer. The lamb pointed to the direction of the stream. The water ran from the wolf toward the lamb, not the other way round. That answer did not stop the wolf. When he spoke of the year before, the lamb said it had not even been born. The wolf changed his story again and spoke of the lamb’s family. The lamb could not tell him what any relative had said. It stood by the water with no more answers to give. The wolf had not been waiting for an explanation. He moved toward the lamb and attacked it. The clear stream continued to run past them. Nothing the lamb had said about the water or the earlier year had changed the wolf’s actions. He had made his decision before he asked the first question.`,
    B1:`The lamb tried once more to show the wolf where each of them stood beside the stream. Mud could not travel against the flow of water. The wolf did not look at the current. He stepped nearer and brought up the insult from the year before. When the lamb explained that it had not yet been born, he made a new claim about its family. The lamb could answer for its own words, not for an unknown relative. Its calm explanations became shorter as the distance between them closed. The wolf did not need to win the argument; he only wanted to make an attack sound deserved. He sprang at the lamb despite its answers. The water flowed on from the place where the wolf had stood to the place where the lamb had been drinking. The facts had remained plain even while his story kept changing.`,
  },
  'book-aesop-3': {
    A2:`Each morning the ass looked for drops on the grass and leaves. It lowered its head and licked up the dew, then waited for more. It returned to the same leaves, but found only a few tiny drops there. The grasshopper was small enough to live on very little, but the ass had a large body to feed. It grew hungry. When it tried to work, its legs felt weak. It listened for its own voice, hoping that the song would come, but it could not sing like the grasshopper. The other animal had not told it to give up its usual food. The ass had decided to do that by itself after hearing the music. More mornings passed, and the little drops still were not enough. The ass had less strength each day. It could no longer do its ordinary work. The grasshopper’s song continued in the field while the ass lay weak nearby.`,
    B1:`The ass went out early to find dew on the leaves. It took small drops from the grass and waited for the sun to bring another morning. The grasshopper could sing after living on such a light diet, so the ass kept hoping for the same result. Its own large body needed more food. Hunger made it slow, and before long it could not work as it had before. It tried to make a beautiful sound, but the change in food had not changed its voice. The grasshopper had simply described its own life; it had not asked the ass to stop eating. The ass had made that choice alone without knowing whether dew could sustain it. Day after day it grew weaker. The singing insect remained in the field, while the animal that had admired its music struggled to stand and carry out ordinary tasks.`,
  },
  'book-aesop-4': {
    A2:`The crane pulled its long beak away from the wolf’s mouth as soon as the bone came free. It stepped back and watched him breathe normally again. Then it asked for the reward he had promised. The wolf opened his mouth, showing the teeth the crane had just passed. He said that the crane was lucky to have taken its head out safely. He would give it nothing else. The crane looked at the wolf for a moment. It had done exactly what he asked, but he would not keep his promise. It did not put its beak near him again or try to argue while standing beside his teeth. The bird walked away with its head safe. Behind it, the wolf could eat again because the bone was gone. The crane had no reward to carry away, only the memory of what he had said before and after it helped him.`,
    B1:`When the bone came out, the crane withdrew its beak carefully and moved beyond the wolf’s jaws. The wolf could breathe and swallow again. The crane asked for the payment they had agreed on before it put its head in danger. Instead of reaching for a reward, the wolf showed his teeth. He said that allowing the crane to escape alive was payment enough. The bird had no safe way to make him keep his promise. It had entered his mouth to remove the bone, but it would not put its head there a second time to demand fairness. The crane stepped away and left him with the bone on the ground. The wolf went back to his food, no longer in pain. The crane walked off without the reward it had been offered, remembering the difference between his words before the rescue and his words afterward.`,
  },
};
