import { parseWritingBlocks } from './library-round-19-overrides';

export const scienceWriting = parseWritingBlocks(`
Climate Change
L=A changing climate affects seasons, water, and growing conditions.|The effects differ from one region to another.|Choices about energy and land influence future warming.
H=Climate change is a long-term shift that appears through many local experiences.|The people least responsible for emissions can face severe consequences.|Adaptation and cutting emissions address different parts of the problem.
V=emissions~Gases released into the air~I would cut emissions from transport.|greenhouse gas~A gas that traps heat~Carbon dioxide is a greenhouse gas.|adaptation~Preparing for changing conditions~Adaptation can protect homes.|mitigation~Reducing the causes of warming~Mitigation needs cooperation.|heatwave~A period of unusually hot weather~A heatwave can close schools.|carbon footprint~Emissions linked to an activity~I would compare the carbon footprint.|resilience~Ability to cope with shocks~Resilience matters during floods.
S=Hotter days affect my walk to school.|I would plant shade trees.|Some families need help now.|We should waste less energy.|I want to know what works.|One town cannot do everything.
T=If my city faced more heatwaves, I would ask who lacks a cool place to go.|Cutting emissions and preparing for change should happen together.|I would rather support a measurable policy than rely on guilt alone.|A carbon footprint can inform choices without explaining every inequality.|I wonder whose experience is missing from climate decisions.|Climate action should make ordinary life safer and fairer.

Renewable Energy
L=Sun, wind, and moving water can provide power.|Electricity must reach homes when it is needed.|A community chooses an energy site for more than its output.
H=Renewable power reduces fuel burning but still requires materials and land.|Storage and flexible grids help match supply with demand.|Local participation can decide whether a project earns trust.
V=solar panel~A device turning sunlight into electricity~I would put a solar panel on the roof.|wind turbine~A machine using wind to generate power~A wind turbine needs a good site.|grid~A network carrying electricity~The grid needs upgrades.|battery storage~Equipment holding energy for later~Battery storage can help at night.|hydropower~Electricity from moving water~Hydropower changes a river.|capacity~The maximum possible output~I would check the capacity.|intermittent~Not available all the time~Wind power is intermittent.
S=I would choose a sunny roof.|The wind does not blow every day.|We need power after dark.|A nearby project needs local support.|I would ask about the cost.|One source may not be enough.
T=If my town built turbines, I would want residents involved before the site was chosen.|Battery storage helps, but it does not remove every grid challenge.|I would rather compare whole systems than call one technology perfect.|Hydropower may provide electricity while changing river habitats.|I wonder who owns the benefits of a community energy project.|Reliable renewable power depends on planning as well as weather.

Plastic Waste
L=Plastic is useful because it is light and durable.|The same durability makes discarded pieces linger.|Sorting waste helps only when collection systems can process it.
H=Plastic pollution begins with production and product design, not just littering.|Some packaging protects food, while other layers add little value.|Reducing unnecessary materials can work before recycling begins.
V=packaging~Material wrapping a product~I would reduce packaging.|microplastic~A tiny plastic fragment~A microplastic can enter water.|single-use~Designed for one use~I would avoid a single-use cup.|recycling~Processing used material into new products~Recycling needs careful sorting.|refill~Filling a container again~I would choose a refill.|disposal~Getting rid of waste~Disposal rules differ by place.|durability~Ability to last~Durability is useful until we throw it away.
S=I would carry a bottle.|This wrapper seems unnecessary.|The bin label is confusing.|We could offer refills.|Some plastic keeps food safe.|I want less waste at school.
T=If a shop removed plastic, I would check whether its replacement is actually better.|Recycling cannot solve a product designed to become waste immediately.|I would rather see refill systems than blame individual shoppers alone.|Microplastics make cleanup much harder than prevention.|I wonder which packaging protects food and which merely attracts buyers.|A durable material needs a plan for what happens after use.

Wildlife Conservation
L=Animals need food, shelter, and room to move.|A protected area can help when nearby land also stays healthy.|Local people often know changes in a habitat first.
H=Conservation succeeds when it protects relationships across an ecosystem.|A single charismatic species can attract support but obscure less visible life.|Long-term care depends on communities having a meaningful role.
V=population~A group of one species in an area~I would track the population.|migration corridor~A route animals use between habitats~A migration corridor needs space.|poaching~Illegal hunting~Poaching harms threatened wildlife.|restoration~Repairing damaged nature~Restoration takes time.|ecosystem~Living things and their surroundings~An ecosystem has many links.|ranger~A person caring for protected land~A ranger knows the area.|biodiversity~Variety of living things~Biodiversity helps ecosystems cope.
S=I would protect a path for animals.|The river needs clean water.|Local people should help decide.|A small insect also matters.|I want to learn what changed.|We should visit without disturbing them.
T=If we protected only famous animals, we might miss what supports them.|A migration corridor can matter more than an isolated reserve.|I would rather ask local communities about needs than announce a distant plan.|Restoration takes patience because an ecosystem cannot be rebuilt overnight.|I wonder how conservation can support livelihoods as well as wildlife.|The least visible species may play a crucial role.

Urban Nature
L=Trees and gardens give city animals places to live.|Shade can make a hot street easier to use.|Even a small patch of soil can hold surprising life.
H=Urban nature is part of infrastructure for heat, water, and wellbeing.|Connected green spaces help wildlife move across built areas.|Access matters when some neighborhoods have far fewer trees.
V=tree canopy~The cover formed by treetops~The tree canopy shades the street.|pollinator~An animal helping plants reproduce~A pollinator visited the flowers.|green corridor~A linked route of planted areas~A green corridor could join parks.|rain garden~A planted area catching runoff~I would build a rain garden.|native plant~A species local to the region~A native plant may support insects.|runoff~Water flowing over hard ground~Runoff collects near the road.|biodiversity~Variety of living things~The garden adds biodiversity.
S=I would plant near the bus stop.|Birds use this small tree.|The pavement is too hot.|We could make room for flowers.|I want a park I can reach.|Rain collects here after storms.
T=If my neighborhood gained trees, I would ask who gets shade first.|A rain garden can solve a drainage problem while supporting insects.|I would rather connect small habitats than celebrate one isolated lawn.|Native plants may help local pollinators better than decorative imports.|I wonder which residents can actually reach a safe green space.|Urban nature should be planned as carefully as roads.

Public Transport
L=A bus or train carries many people along one route.|Frequency matters when a passenger has no flexible schedule.|A safe walk to the stop is part of the trip.
H=Public transport works as a network, not a collection of vehicles.|Reliability shapes whether people can trust it for work or school.|Accessible routes expand who can participate in city life.
V=route~The path a service follows~I would change the route.|frequency~How often a service runs~Frequency matters at night.|transfer~A change from one service to another~My transfer takes too long.|fare~The price of a ride~I would lower the fare.|platform~A place for boarding a train~The platform needs clear signs.|accessibility~Ease of use for people with different needs~Accessibility should guide design.|timetable~A schedule of departures~I would check the timetable.
S=I would take the bus to school.|The stop needs a shelter.|This transfer is too slow.|A clear sign would help.|I want a safe ride home.|The fare matters to me.
T=If I redesigned a route, I would begin with trips people actually need.|A low fare helps little when the last bus leaves too early.|I would rather improve reliability than add a flashy vehicle.|Accessibility includes the path to the stop and the information along it.|I wonder whose travel time city planners count.|A useful network should serve ordinary days, not just busy centers.

Cities of the Future
L=A city can change its streets as people grow and move.|Homes, parks, and services need to fit together.|A clever device cannot fix a badly planned neighborhood.
H=Future cities will reflect choices about housing, climate, and public space.|Technology helps only when residents can understand and shape it.|A good plan should work for children, older people, and people with disabilities.
V=mixed-use~Combining homes, shops, and services~I prefer a mixed-use street.|density~How many people live in an area~Density can support frequent buses.|smart sensor~A device gathering local information~A smart sensor could detect leaks.|public space~A place open to everyone~Public space needs shade.|zoning~Rules for how land may be used~Zoning can separate homes and shops.|walkability~Ease of getting around on foot~Walkability matters near schools.|housing supply~The amount of available housing~Housing supply affects choices.
S=I want a park near home.|The streets should feel safe.|A shop within walking distance helps.|We need homes people can afford.|I would add shade to the square.|A robot cannot solve every problem.
T=If I planned a city, I would ask residents what already works before drawing new towers.|A smart sensor is useful only when someone responds to its information.|I would rather have reliable buses than spectacular empty buildings.|Mixed-use streets can make daily errands easier without a car.|I wonder how future housing can remain affordable.|A successful city lets more people share its benefits.

Space Exploration
L=Space missions use instruments to learn about distant places.|An unmanned probe can travel where people cannot safely go.|Each mission has limited fuel, time, and power.
H=Exploration asks scientific questions while also expressing human ambitions.|Robotic craft and astronauts offer different kinds of observation.|The cost of a mission invites debate about benefits on Earth.
V=probe~An unmanned craft for investigation~A probe could measure the atmosphere.|orbit~A path around another body~The craft entered orbit.|telescope~An instrument for observing distant objects~A telescope reveals faint light.|payload~Equipment carried for a mission~I would check the payload.|mission control~The team directing a mission~Mission control sent a command.|trajectory~A planned path through space~The trajectory saves fuel.|life support~Systems keeping astronauts alive~Life support needs backups.
S=I would send a small robot first.|The journey could take years.|What would it measure?|Astronauts need safe air.|I want to see the images.|The cost needs a reason.
T=If I designed a mission, I would start with one question the instruments could answer.|A robotic probe can take risks that would be unacceptable for people.|I would rather fund a careful long mission than a dramatic short visit.|Life support makes human exploration far more complex than a camera flight.|I wonder which discoveries justify the expense to society.|Exploration is most valuable when its findings are shared widely.

Mars Missions
L=Mars is far away, and a message takes time to travel.|Robots can examine rocks before people arrive.|Dust and cold make equipment difficult to maintain.
H=A Mars mission must plan for delays, hazards, and uncertain results.|Samples could tell a history that images alone cannot show.|Sending people would require reliable supplies and a way home.
V=rover~A robot that moves over another world's surface~A rover could inspect rocks.|landing site~The chosen arrival area~I would compare landing sites.|sample~A small collected piece~The sample may reveal history.|dust storm~A large movement of airborne dust~A dust storm could delay work.|communication delay~Time before a message arrives~Communication delay complicates control.|habitat module~A shelter for astronauts~The habitat module needs protection.|return mission~A trip designed to come home~A return mission doubles the challenge.
S=I would send a rover.|The dust could cover its camera.|A message cannot arrive at once.|I want to study a rock.|People need shelter there.|Coming home matters too.
T=If a landing site looked exciting but dangerous, I would choose safety first.|A sample brought home might answer questions a rover cannot.|I would rather send better robots before committing people to the trip.|Communication delay means a crew must solve some problems alone.|I wonder what evidence would justify the risks of a human mission.|The return journey deserves as much planning as the arrival.

Satellites
L=A satellite travels around Earth while collecting or sending information.|Different instruments watch weather, land, or communication signals.|Old equipment in orbit can become a hazard.
H=Satellites make distant information available quickly but create dependence.|Images can reveal broad changes while missing local context.|Crowded orbits raise questions about shared space and responsibility.
V=orbit~A path around Earth~I would choose a stable orbit.|sensor~A device measuring something~The sensor tracks clouds.|signal~Information sent through the air~The signal reached the receiver.|ground station~A site receiving satellite data~A ground station collects the data.|space debris~Discarded objects in orbit~Space debris can strike equipment.|resolution~The detail visible in an image~Higher resolution may help.|navigation~Finding a route or position~Navigation depends on signals.
S=I would use it to watch storms.|The image looks blurry.|A signal could help a ship.|Old parts should not float forever.|Who can see the data?|The view from above is useful.
T=If I used satellite images, I would check what they cannot show on the ground.|A stronger signal helps only when people have access to a receiver.|I would rather plan for space debris before adding more equipment.|Resolution changes what we can infer and what privacy concerns arise.|I wonder who should manage a crowded orbit.|Satellite data needs local knowledge to become useful action.

Inventions
L=An invention begins with a problem someone notices.|Early versions often fail in useful ways.|A new device may need other systems before people adopt it.
H=Inventions emerge from teams, earlier ideas, and practical constraints.|A clever prototype is not the same as a safe useful product.|The consequences of a device may differ from its inventor's goal.
V=prototype~An early version for testing~I would build a prototype.|patent~A legal claim to an invention~I would read about the patent.|iteration~A revised version after testing~The next iteration should be smaller.|constraint~A limit shaping a design~Cost is a constraint.|manufacturing~Making goods at scale~Manufacturing changes the design.|user need~A problem a person wants solved~I would check the user need.|trade-off~A choice that sacrifices one benefit~That trade-off seems fair.
S=I would fix the broken handle.|The first version might fail.|Let us ask who needs it.|I would test it safely.|The idea could be simpler.|Someone else may improve it.
T=If I invented a tool, I would watch how people use it before defending my design.|A patent may reward one person even when many contributed ideas.|I would rather solve a small real problem than build a dramatic useless device.|Manufacturing can reveal flaws a prototype hides.|I wonder who bears the cost of a new invention's side effects.|Useful innovation includes maintenance after the first sale.

Medical Technology
L=A medical device can help doctors see or measure a problem.|Tests must show that a tool is safe enough to use.|Clear instructions matter when patients use equipment at home.
H=Medical technology combines scientific promise with evidence about real patients.|A tool can improve diagnosis yet remain inaccessible because of cost.|Privacy and human judgment still matter when software analyzes health data.
V=diagnosis~Identifying an illness~A careful diagnosis needs context.|scan~An image of the body's inside~The scan showed a change.|clinical trial~A study testing a treatment or tool~A clinical trial needs safeguards.|monitor~A device tracking a body signal~The monitor checks heart rhythm.|false positive~A result suggesting a problem that is absent~A false positive can cause worry.|accessibility~Ease of use for varied patients~Accessibility matters in device design.|informed consent~Agreement after understanding risks~Informed consent should be clear.
S=I would ask how the tool works.|A clear picture could help.|The result might be wrong.|Patients need simple instructions.|Not everyone can afford it.|A doctor should explain the choice.
T=If a device found more possible problems, I would also ask how many alerts were false.|A promising clinical trial does not guarantee equal access.|I would rather have a slower explained diagnosis than an opaque instant one.|Informed consent requires language patients can understand.|I wonder who is left out when a tool is tested on too narrow a group.|Technology should support care, not replace the patient's voice.

Food Waste
L=Food can be lost on farms, in shops, or at home.|A date label may tell different things about safety and quality.|Planning a meal can keep useful ingredients from being forgotten.
H=Food waste reflects storage, transport, marketing, and household habits.|Discarding edible food also wastes the land and water behind it.|Solutions differ depending on where in the chain the loss happens.
V=spoilage~Food becoming unsafe or unpleasant~Cold storage slows spoilage.|portion~An amount served to one person~I would choose a smaller portion.|date label~Words marking a product date~I would read the date label.|storage~Keeping food under suitable conditions~Good storage helps.|surplus~More than is needed~The shop had a surplus.|compost~Decayed organic material for soil~I would compost scraps.|meal plan~A schedule of intended meals~My meal plan uses leftovers.
S=I would use the carrots tonight.|This portion is too big.|Let us freeze the rest.|The label is confusing.|I can make soup from leftovers.|The bin should be the last option.
T=If a shop had surplus food, I would look for a safe way to share it.|A date label should guide decisions without encouraging needless disposal.|I would rather plan flexible meals than buy ingredients for a perfect week.|Compost helps with scraps but does not recover a whole wasted meal.|I wonder where most food is lost before shoppers see it.|Preventing waste begins with understanding why food was bought or grown.

Sustainable Fashion
L=Clothes use materials, energy, and labor before reaching a shop.|Repair can keep a favorite garment useful longer.|Buying fewer pieces may be easier when they last.
H=The environmental cost of clothing includes production, transport, use, and disposal.|A green label is less useful than clear information about a garment's life.|Workers' conditions belong in a discussion of sustainability.
V=fast fashion~Rapid production of cheap changing styles~I would question fast fashion.|repair~Fixing a damaged item~I would repair the seam.|fiber~A strand used in fabric~This fiber dries quickly.|dye~A substance adding color~The dye may pollute water.|supply chain~Steps from material to shop~I would ask about the supply chain.|secondhand~Previously owned~I would search secondhand shops.|durability~Ability to last~Durability matters more than a trend.
S=I would mend this shirt.|I could swap clothes with a friend.|The fabric feels strong.|I do not need another jacket.|A worker made this.|I want it to last.
T=If a brand claimed to be sustainable, I would ask for evidence beyond the label.|Repairing a garment can preserve something I already enjoy wearing.|I would rather buy one durable piece than several weak copies.|A supply chain includes workers whose conditions are often hidden.|I wonder whether constant new collections can ever be responsible.|Sustainable clothing should be accessible, not just fashionable.

Water Conservation
L=Clean water needs to be collected, treated, and delivered.|A dripping tap wastes water slowly but steadily.|Farms, homes, and businesses use water differently.
H=Conserving water means matching use to local supply and ecological needs.|Leaks in public systems can waste more than household habits alone.|Rules should protect basic access while encouraging careful use.
V=watershed~Land draining to one waterway~I would protect the watershed.|leak~An unwanted escape of water~I would report the leak.|irrigation~Supplying water to crops~Irrigation can be improved.|treatment plant~A facility cleaning water~The treatment plant needs upkeep.|drought~A long period with too little rain~Drought changes local plans.|reuse~Using water again for another purpose~I would support safe reuse.|meter~A device measuring consumption~The meter showed a leak.
S=I would fix that tap.|We can collect rain for plants.|The river needs water too.|This shower could be shorter.|Farmers need fair support.|I want safe drinking water.
T=If my town faced drought, I would ask where the largest losses occur.|A household meter can help, but public pipes matter too.|I would rather invest in repair than blame people for every drop.|Safe reuse could free clean water for drinking.|I wonder how water rules can protect low-income families.|Conservation works when users understand the needs of the whole watershed.
`);
