import { parseWritingBlocks } from './library-round-19-overrides';

export const digitalWriting = parseWritingBlocks(`
Video Games
L=A player learns a game by testing its rules, not just reading them.|The same level can feel different when played with friends.|Small design choices influence whether a challenge feels fair.
H=Games create feedback loops in which every action changes the next decision.|A carefully balanced system can offer freedom without losing a clear purpose.|The social setting around a game may shape its meaning as much as the code.
V=level~A section of a game with its own challenge~I would redesign the first level.|checkpoint~A saved place for restarting play~I would add a checkpoint here.|co-op~A game mode where players work together~I prefer co-op with friends.|difficulty curve~How challenge increases through a game~This difficulty curve feels steep.|controller~A device used to direct game actions~I would redesign the controller.|quest~A task a player tries to complete~The quest could have two solutions.|feedback loop~A cycle where results affect later actions~A feedback loop can keep me playing.
S=I would replay that level with a different plan.|A checkpoint would make the challenge less frustrating.|I prefer playing with friends when a puzzle is difficult.|The controls should be simple to learn.|I would change the ending after a clever choice.|A game can be fun without a huge map.
T=If the rules were less clear, I might enjoy discovering them myself.|I would rather a game reward creative solutions than fast button presses.|A difficulty curve should make failure useful instead of exhausting.|Co-op play can turn one person's mistake into a group conversation.|I wonder which part of the game would stay interesting after ten plays.|The best design may be the decision the player never notices.

Game Design
L=Designers start with a question about what players should do.|A rough paper version can test an idea early.|Watching a confused player reveals problems hidden from the creator.
H=Good design separates a player's meaningful choices from needless complexity.|Repeated playtests expose patterns that one enthusiastic tester may miss.|A mechanic becomes interesting when players can use it in several ways.
V=mechanic~A rule governing one kind of game action~I would test one mechanic first.|prototype~An early model used for testing~My prototype could use paper.|playtest~A session where people try an unfinished game~I would run a playtest.|tutorial~A short guide teaching a game~The tutorial should let me try things.|balance~Fairness between different game choices~The balance feels wrong here.|level design~Planning the spaces and challenges of a game~I would change the level design.|player feedback~What players say or show after play~Player feedback could reveal a hidden problem.
S=I would test the game with someone new.|A paper prototype could save time.|The first rule should be easy to try.|I would watch where players get stuck.|A confusing button needs a clearer sign.|The game should let mistakes teach something.
T=If a playtest failed, I would ask what the player expected to happen.|I would rather cut a weak mechanic than add another tutorial.|Balance does not mean every choice must feel identical.|A level can teach a rule through its layout instead of a paragraph.|I wonder whether surprising players is worth confusing them.|The designer's favorite feature may be the first one to remove.

Esports
L=Competitive players study opponents as well as their own moves.|A team can lose despite one player's excellent performance.|The audience often follows decisions that happen in seconds.
H=Esports blends individual skill with communication under pressure.|Rules and equipment standards help make comparisons more meaningful.|Public attention can make recovery after a loss unusually difficult.
V=roster~The list of players on a team~I would check the roster.|scrimmage~A practice match between teams~Our scrimmage exposed mistakes.|commentator~A person describing the match to viewers~The commentator made the tactic clear.|bracket~A diagram showing tournament matches~I would study the bracket.|reaction time~The speed of responding to a signal~Reaction time matters here.|team call~A short spoken instruction during play~Our team call was too late.|sportsmanship~Fair and respectful conduct in competition~Sportsmanship matters after a loss.
S=I would practice talking clearly with teammates.|A good commentator helps me follow the match.|The final round could feel tense.|I would congratulate the other team.|One clever play might change our plan.|Rest should be part of training.
T=If I joined a team, I would value reliable communication over a flashy move.|A fair tournament needs more than identical computers.|The pressure of a live audience might change even practiced decisions.|I would rather lose with good sportsmanship than win by bending a rule.|I wonder how teams review mistakes without blaming one person.|Competitive gaming should make room for rest and healthy routines.

Social Media
L=A feed can make an ordinary day seem full of dramatic moments.|People choose a small part of life to put online.|A private joke can reach an unintended audience.
H=Platforms reward some forms of attention while leaving other experiences unseen.|A post's context can disappear when it is reshared.|Users negotiate between connection, privacy, and the wish to be noticed.
V=feed~A stream of posts shown by a platform|caption~Words placed beside a post~I would change the caption.|repost~To share someone else's post again~I would ask before a repost.|audience~The people who may see a message|engagement~Responses such as likes and comments~Engagement is not the same as trust.|privacy setting~A control limiting who sees content~I would check the privacy setting.|context collapse~Different audiences seeing the same post~Context collapse can make a joke confusing.
S=I would ask before posting a friend's photo.|A short caption can change the meaning.|The feed should show more ordinary moments.|I might delete a joke that feels unkind.|A private message could be better than a public reply.|I would take a break after too much scrolling.
T=If a post reached people outside my friend group, I might explain its context.|I would rather see fewer thoughtful posts than an endless feed.|Engagement can measure attention without showing whether people understood.|A privacy setting cannot control screenshots someone else takes.|I wonder who benefits when a platform encourages quick reactions.|The best online conversation might move to a quieter place.

Online Privacy
L=Information can spread even from a small group chat.|An old account may still hold personal details.|Someone can copy a picture without asking.
H=Privacy is partly about deciding who sees information and when.|Security tools help, but social choices affect exposure too.|A single public detail can become more revealing when combined with others.
V=passphrase~A long secret used to protect an account~I would choose a passphrase.|two-factor login~A second check during sign-in~Two-factor login can slow an intruder.|data trail~Information left by online actions~My data trail might surprise me.|screenshot~An image copied from a screen~A screenshot can outlast a post.|permission~Agreement before an action is taken~I would ask permission first.|profile~A page showing information about a user~I would review my profile.|account recovery~Steps for regaining access to an account~Account recovery needs careful checks.
S=I would ask before sharing a group photo.|A longer passphrase is easier to remember as a sentence.|My old profile might need a review.|I would keep recovery details somewhere safe.|A screenshot can leave the group chat.|Privacy should include my friends' choices too.
T=If a friend shared my photo, I would explain why permission matters.|I would rather use an extra login step than lose an account.|Privacy settings can help, but they cannot undo every copy.|A harmless detail may reveal more when linked to other information.|I wonder who should teach young people to manage their data trails.|The right to share a story should include the right to leave someone out.

Screen Time
L=Two hours on a screen can hold very different activities.|A video call may leave someone energized.|Mindless scrolling may feel tiring even without effort.
H=Counting minutes alone misses the purpose and quality of digital activity.|Interruptions can matter more than total time when studying.|A useful boundary should fit a person's work, friendships, and rest.
V=notification~An alert from a device or app|scrolling~Moving through content on a screen|app timer~A tool showing or limiting app use~I would set an app timer.|focus mode~A setting that reduces interruptions~Focus mode might help me study.|break reminder~A prompt to pause an activity~A break reminder could help.|video call~A conversation using live video~A video call can feel social.|digital boundary~A personal rule for device use~My digital boundary could change.
S=I would silence alerts while doing homework.|A video call with friends feels different from scrolling.|I might set a timer before opening an app.|The phone can stay outside my bedroom.|A break should include moving around.|I would ask what I gained from that hour.
T=If I tracked screen time, I would note what I was doing as well as minutes.|I would rather protect uninterrupted study than impose one strict daily number.|A notification that seems small can break a difficult train of thought.|I wonder whether social calls should count as rest or screen use.|My boundaries should change when school and family needs change.|A useful device habit leaves room for both connection and quiet.

Digital Footprints
L=A casual comment can be found long after it was written.|Photos may reveal more than their captions say.|People can change, while old posts remain visible.
H=Searchable traces can flatten years of growth into a few isolated moments.|Deleting a post does not ensure every copy disappears.|A thoughtful footprint includes what we choose not to share.
V=search result~A page shown after an online search~That search result is old.|archived post~An older saved online message~I found an archived post.|tag~A label connecting a person to content~I would remove that tag.|public comment~A reply visible to many people~A public comment can travel.|metadata~Information about a file, such as time or location~Photo metadata can reveal a place.|digital trail~The traces left by online activity~My digital trail includes old accounts.|reputation~What others generally think about someone~One post should not decide a reputation.
S=I would read an old post before sharing it again.|A tag should need my permission.|My joke might look different later.|I would check what a search shows.|A photo can reveal where I was.|I want room to change my mind.
T=If an old comment embarrassed me, I would add context rather than pretend it vanished.|I would rather be judged by a pattern of actions than one teenage post.|Search results can separate a sentence from the conversation around it.|A friend tagging me should consider my boundaries too.|I wonder how long schools should keep old student work online.|A careful digital trail leaves evidence of learning, not just polished success.

Internet Memes
L=A meme changes as people add new captions.|A funny picture can mean different things to different groups.|Some jokes need background knowledge to make sense.
H=Memes act like small pieces of shared culture that people continually remake.|A new caption can reverse the meaning of an old image.|Speed of sharing can make it hard to trace who created an idea.
V=caption~Words placed beside an image|reaction image~A picture used to show a response~I would choose a reaction image.|remix~A new version of existing material~My remix could change the joke.|template~A reusable pattern for making content~This meme template feels old.|inside joke~Humor understood by a particular group~An inside joke can exclude people.|credit~Recognition given to a creator~I would give the creator credit.|viral spread~Fast sharing between many people~Viral spread can change a meme.
S=I would add a kinder caption.|That meme needs a little explanation.|My friends might understand it differently.|I would credit the original artist.|A silly picture could start a story.|I would not share a joke that hurts someone.
T=If I remixed a meme, I would check whether the original creator deserves credit.|I would rather share a clever joke than one that embarrasses a classmate.|An inside joke loses something when the whole internet sees it.|A new caption can make the same image argue the opposite view.|I wonder when a meme becomes a useful explanation instead of only a joke.|Fast sharing can outrun the time needed to understand the context.

Artificial Intelligence
L=An AI tool can produce a convincing answer from patterns.|It may miss a fact that a person would check.|The user still decides what to trust.
H=AI systems can generate plausible text without directly verifying its truth.|Training data influences which patterns a model finds familiar.|The value of an output depends on the task and the human review around it.
V=training data~Examples used to teach an AI system~I would check who chose the training data.|prompt~The instruction given to an AI tool~I would write a clearer prompt.|hallucination~A plausible but unsupported AI output~That hallucination needs checking.|model~A trained system that produces outputs~The model gave two answers.|bias~A tendency toward some results over others~Bias can appear in training data.|source check~A step verifying where a claim came from~I would do a source check.|human oversight~People reviewing and guiding a system~Human oversight matters for decisions.
S=I would check the answer in another source.|A clear prompt might help.|The tool could miss an important detail.|I would show when AI helped me.|A human should decide the final result.|I would ask what information it used.
T=If I used AI for an essay, I would explain which parts it helped draft.|I would rather receive an uncertain answer than a confident mistake.|A model's fluent language can hide gaps in evidence.|Human oversight matters more when a decision affects someone else's life.|I wonder which creative tasks benefit from a machine's suggestions.|The best use may be asking better questions, not accepting the first response.

Robots and Automation
L=A robot can do one repeated factory movement accurately.|People still inspect and repair the machines.|Changing a task can require a new program.
H=Automation shifts work instead of simply making it disappear.|Sensors and software help machines respond to limited changes.|Workers need a voice in how a new system changes their jobs.
V=assembly line~A sequence of work stations making a product~I would watch an assembly line.|sensor~A device noticing changes nearby|robot arm~A moving machine part used for tasks~A robot arm could lift boxes.|programmer~A person writing computer instructions~A programmer might adjust the machine.|maintenance~Work keeping equipment in good condition~Maintenance should be planned.|precision~Exactness in movement or measurement~The robot needs precision.|worker training~Practice for a changing job~Worker training can reduce confusion.
S=I would let the robot lift heavy boxes.|A worker should be able to stop it.|The machine needs regular checks.|I would ask what job changes next.|People should help design the new routine.|One robot cannot solve every problem.
T=If a factory added robots, I would ask workers which tasks cause strain.|I would rather automate dull repetition than creative judgment.|Precision is useful only when the machine knows the right goal.|A new system may create maintenance work that was not needed before.|I wonder who benefits when automation saves time.|Worker training should begin before the machines arrive, not afterward.

Virtual Reality
L=A headset can make a room look like another place.|Turning your head changes the view.|Some people feel uncomfortable after a long session.
H=Virtual reality connects visual movement with body movement to create presence.|A convincing simulation can support practice without real-world risk.|Designers must account for motion comfort and different physical abilities.
V=headset~A device worn over eyes for a virtual view|avatar~A person's figure in a virtual space~My avatar could wave.|motion sickness~Discomfort caused by conflicting movement signals~Motion sickness might stop me.|simulation~A modeled experience of a situation|hand controller~A device used to act in virtual space~I would hold a hand controller.|immersion~The feeling of being inside an experience~Immersion can be exciting.|virtual room~A simulated shared space~Our virtual room could show a museum.
S=I would visit a virtual forest.|The headset might feel heavy.|I could meet a friend there.|I would take a short break.|My avatar might look different.|I want to try a safe flying game.
T=If I practiced a speech in VR, I would want the audience to respond naturally.|I would rather visit a real park than spend hours in its simulation.|A virtual room can connect people who cannot travel together.|Motion sickness should be treated as a design problem, not a user's fault.|I wonder which skills transfer best from simulation to life.|Immersion is powerful only when people can leave comfortably.

Coding
L=A program follows instructions in a chosen order.|A missing symbol can change what happens.|The programmer tests a small piece before moving on.
H=Code translates a human idea into steps a machine can perform.|Clear names and structure help other people understand a program.|Debugging often means checking an assumption rather than guessing at random.
V=variable~A named place for a value in code~I would name the variable clearly.|loop~Instructions repeated until a condition changes~A loop could save typing.|bug~A mistake causing unwanted behavior~I would search for the bug.|debug~To find and fix a program error~I would debug one step at a time.|function~A reusable block of instructions~I would write a small function.|syntax~Rules for writing valid code~A syntax error can stop the program.|test case~A chosen input used to check a program~I would add a test case.
S=I would build a tiny quiz.|A bug might make it funny.|I would check one line at a time.|A loop could repeat the question.|I want a friend to test it.|The first version can be simple.
T=If my code failed, I would try to reproduce the same error first.|I would rather write readable code than finish ten minutes sooner.|A good test case can reveal a mistake I did not expect.|A small function might make later changes easier.|I wonder when a program needs a rewrite instead of another patch.|Coding with a partner could improve both the idea and the explanation.

Cybersecurity
L=A fake message may ask for an urgent click.|A software update can close a known weakness.|An extra login step makes stealing an account harder.
H=Security depends on people, procedures, and technology working together.|Attackers exploit rushed decisions as often as technical flaws.|A simple habit of checking the sender can prevent a costly mistake.
V=phishing~A trick to steal information through fake messages~I would report phishing.|password manager~A tool storing strong passwords~I would use a password manager.|security update~A change that fixes software weaknesses~A security update can help.|verification code~A short number used for a second login check~I would protect my verification code.|suspicious link~A web address that may lead somewhere unsafe~I would not open a suspicious link.|account recovery~Steps for regaining access after a lockout~Account recovery should be secure.|backup~A saved copy used if the original is lost~I would keep a backup.
S=I would check the sender first.|A rushed message makes me suspicious.|I would not share a login code.|A backup could save my work.|I would ask for help after a strange link.|Updates can be worth the wait.
T=If a message demanded immediate action, I would slow down and check its source.|I would rather spend time on a second login step than recover a stolen account.|Security advice should be clear enough for ordinary users to follow.|A backup is useful only if I know how to restore it.|I wonder how schools can teach scams without making everyone fearful.|Good cybersecurity makes careful behavior easier, not just mandatory.

Online Learning
L=A recorded lesson lets a student pause and replay.|A live class can answer a question immediately.|A quiet learner may prefer typing first.
H=Online learning changes how students ask for help and show confusion.|Good lessons combine clear independent tasks with chances to talk.|Reliable access and a suitable place to study are part of the learning environment.
V=recording~A saved lesson that can be replayed~I would watch the recording again.|live session~A class happening in real time~I would join a live session.|chat box~A space for typed questions~I would use the chat box.|self-paced~Done at a learner's chosen speed~A self-paced lesson could help.|discussion board~A place for written class conversations~I would post on the discussion board.|internet access~The ability to connect to the network~Internet access can vary.|breakout room~A small online group space~Our breakout room could be quiet.
S=I would pause the video to take notes.|A live question could save time.|I might type before speaking.|A short task helps me focus.|I would ask classmates for help.|The internet should not decide who learns.
T=If I taught online, I would leave pauses for questions rather than fill every minute.|I would rather replay a difficult explanation than pretend I understood it live.|A discussion board can give thoughtful students more time to respond.|Reliable access is a basic learning need, not a luxury.|I wonder how teachers notice confusion when cameras are off.|The strongest online course might blend independent work with real conversation.

Digital Art
L=An artist can work on separate layers of one image.|Undo makes a risky experiment easier.|A tablet pen can respond to pressure.
H=Digital tools change how easily an artist revises a picture.|A layer can separate light, color, and line without losing earlier work.|The choices behind the image still belong to its maker.
V=layer~A separate part of a digital image|stylus~A pen-shaped tool used on a screen|brush preset~A saved digital brush setting~I would try a brush preset.|undo~A command reversing the last action|opacity~How much of a layer can be seen through~I would lower the opacity.|canvas size~The dimensions of a digital picture~I would set the canvas size.|pixel~A tiny unit of a digital image~One pixel can change a line.
S=I would draw on a tablet.|An undo button makes me braver.|I could add color on another layer.|My brush might look like chalk.|I would save the first version.|The final picture should feel like mine.
T=If I painted digitally, I would try a bold change on a separate layer.|I would rather keep one interesting mistake than undo every imperfect mark.|A brush preset can save time but cannot choose the idea for me.|Changing opacity could make a shadow feel softer.|I wonder whether unlimited undo changes how artists learn.|The final image still carries a human series of choices.
`);
