/** Chapter-scoped endings for lessons whose old final paragraph was commentary. */
export const kidEndings: Record<string, Record<'A2'|'B1', string>> = {
  'book-alice-3': {
    A2: 'The mouse was upset with Alice and left. Alice called after him, but he did not come back. She tried to tell the other animals how gentle Dinah was at home. This made matters worse. The birds knew that a cat could catch them too, so one by one they found reasons to go away. Soon Alice was sitting alone beside the pool. She missed Dinah and wished she had not spoken about hunting. Then she heard the White Rabbit nearby. He was still worried about being late and was looking for something he had lost.',
    B1: 'The mouse moved away before Alice could explain herself. She turned to the other animals and tried to praise Dinah, but describing a cat that caught birds frightened them too. One said it had to go home, and the rest soon followed. Alice called for them to stay, then found herself alone on the bank. She thought of Dinah at home and wished she could see her, although she now understood why her new companions did not want to hear about her. Before long the White Rabbit came by, hurrying and searching for something he had lost.',
  },
  'book-sherlock-1': {
    A2: 'When Holmes and Watson returned, Irene had already left with the man she had married. She had left a letter for Holmes. In it she explained that she recognized his disguise and followed him to make sure of his plan. She also promised that she would keep the photograph with the King only for her own safety. The King was satisfied when he heard this. He offered Holmes an expensive ring, but the detective asked for the photograph Irene had left behind instead. Watson and Holmes went home without the picture they had searched for.',
    B1: 'By the time Holmes returned to Irene’s house, she and her new husband had gone. She had left a letter explaining how she recognized the disguised detective and followed him after the false fire alarm. Her photograph with the King was still in her possession, but she promised to use it only if he threatened her. She left another photograph of herself in its place. The King accepted this promise and offered Holmes an expensive ring. Holmes chose Irene’s own photograph instead. Watson watched his friend take the picture, aware that Irene had anticipated their next move.',
  },
  'book-sherlock-2': {
    A2: 'When the two men climbed out of the tunnel, Holmes and the police caught them. Spaulding was really John Clay, a thief who had used the strange job to get Wilson out of the shop. Clay tried to escape but could not pass the officers. The bank’s money was still safe. Later Holmes explained the trick to Watson: the low wages Spaulding accepted, his visits to the cellar, and the worn knees of his trousers had led Holmes to the tunnel. Wilson could return to his shop, though he would receive no more pay from the League.',
    B1: 'When the tunnel opened, Holmes and the police seized the men climbing through it. Wilson’s assistant was John Clay, a wanted criminal who had used the League to make the shopkeeper leave his business every day. Clay protested, but the officers took him away before he could reach the bank’s money. Afterward Holmes walked Watson through the clues: Spaulding’s low wages made little sense unless he wanted access to the shop; his time in the cellar and the marks on his knees pointed to digging. The end of the copying job meant that the tunnel was nearly ready.',
  },
  'book-sherlock-3': {
    A2: 'Holmes invited Windibank to his rooms and showed him what the typed letters revealed. Windibank did not deny the trick for long. He had dressed as Hosmer, used dark glasses, and changed his voice so Mary would not know him. He wanted her to promise to wait for Hosmer and avoid another marriage. Holmes was angry and reached for a whip, but Windibank ran away. Mary had already left the rooms before this meeting. Holmes did not tell her the answer. He told Watson that she would probably refuse to believe him if he did.',
    B1: 'Holmes summoned Windibank and compared the typed letters with a sample from his office. The same faults appeared in the typewriter’s letters. Confronted with this evidence, Windibank could no longer hide that he had posed as Hosmer. By making Mary promise to remain faithful after her fiancé vanished, he hoped to keep her income in the household. Holmes threatened to take a whip to him, and Windibank fled the room. Mary was not present for the confrontation. Holmes chose not to tell her the solution, saying that she would not believe him. Watson heard the explanation after she had gone.',
  },
  'book-sherlock-4': {
    A2: 'Turner wrote down his confession for Holmes. Holmes said he would use it if James could not be cleared in another way. He did not want Turner’s daughter to learn her father’s secret unless it was necessary. James’s case was later resolved without Holmes handing over the confession. Turner, already very ill, died some months afterward. Holmes and Watson left the valley knowing why the marks near the pool had not fitted the villagers’ first story. Alice and James could look ahead without the charge of murder hanging over him any longer.',
    B1: 'Turner gave Holmes a written confession. Holmes promised to keep it private unless the court needed it to clear James. The other evidence helped free the young man, so Holmes did not have to reveal the confession. Turner died later from his illness. Alice and James could plan their future without a murder charge hanging over him, though they did not know every part of the older men’s history. Back in London, Holmes reviewed the scene with Watson, explaining how the footprints and the dying man’s words had pointed beyond the son whom everyone first suspected.',
  },
};
