import { parseWritingBlocks } from './library-round-19-overrides';

export const wellbeingWriting = parseWritingBlocks(`
Team Sports
L=Players share a goal but have different jobs on the field.|A team must respond when its first plan stops working.|Practice can improve communication as well as movement.
H=Team sports reward coordinated decisions that no single player can make alone.|A strong player can lift others or make them hesitate, depending on behavior.|How a team handles defeat reveals its habits more clearly than an easy win.
V=formation~The arrangement of players~I would change the formation.|pass~To send the ball to another player~I would pass earlier.|defense~Actions that stop the opposing team~Our defense needs help.|captain~A player chosen to guide the team~The captain listened first.|substitute~A player who enters later~A substitute can bring new energy.|strategy~A plan for play~Our strategy needs to change.|sportsmanship~Respectful conduct in competition~Sportsmanship matters after a loss.
S=I would pass to a teammate.|We need to talk more clearly.|The new player should get a turn.|I can try a different position.|Let us practice that move.|Losing does not end the team.
T=If our plan failed, I would ask what the other team had noticed.|A captain should make quieter players feel able to speak.|I would rather share chances than build every move around one star.|A substitute deserves a role, not just the final seconds.|I wonder when competition makes teammates less honest with each other.|The best teams improve how they lose as well as how they win.

Solo Sports
L=An individual athlete makes many decisions without teammates nearby.|Practice often repeats a small movement many times.|A coach or training partner can still offer support.
H=Solo sports combine personal responsibility with networks of instruction and care.|Progress may appear slowly before one small change unlocks it.|Comparing only results can hide different starting points and resources.
V=technique~A practiced way of moving~I would adjust my technique.|personal best~An athlete's best result so far~I beat my personal best.|pace~Speed maintained over time~My pace was too fast at first.|coach~A person guiding practice~I would ask my coach.|recovery~Rest after effort~Recovery belongs in training.|focus~Concentrated attention~I lost focus near the end.|training plan~A schedule for improving~My training plan needs rest days.
S=I would practice the start.|My pace felt too fast.|A coach could spot a mistake.|I am proud of a small improvement.|I need a rest day.|I want to enjoy the sport.
T=If I missed a personal best, I would still look for a stronger technique.|A solo result often rests on help from people the audience never sees.|I would rather follow a sustainable training plan than chase one dramatic week.|Recovery can be a deliberate part of improvement.|I wonder how athletes stay motivated when progress is hard to measure.|Competing with myself feels useful only when it leaves room for joy.

Fitness
L=Different activities strengthen different parts of the body.|A routine works better when it fits ordinary life.|Rest gives muscles time to recover after effort.
H=Fitness includes strength, endurance, mobility, and the ability to enjoy movement.|A plan should be adjusted when pain signals a problem.|Numbers can track progress, but they cannot describe every benefit.
V=endurance~Ability to keep going during effort~I want to build endurance.|strength~Ability to produce force~Strength helps me carry things.|mobility~Ease of moving joints~Mobility matters to me.|warm-up~Gentle activity before harder work~I would do a warm-up.|repetition~One complete exercise movement~I would add a repetition slowly.|recovery~Rest that allows repair~Recovery is part of exercise.|intensity~How demanding an activity is~I would lower the intensity.
S=I enjoy walking with a friend.|I would start slowly.|This exercise hurts my knee.|A short routine fits my day.|Rest helps me come back.|I want to feel stronger.
T=If I planned exercise, I would choose something I could repeat without dread.|More intensity is not automatically better when technique breaks down.|I would rather notice energy and sleep than judge myself only by numbers.|A warm-up prepares me to move, but it should not become a test.|I wonder how public spaces shape who feels welcome to exercise.|Fitness should make daily life easier, not smaller.

Outdoor Adventures
L=A hike or camp changes when weather changes.|A route needs enough time for the slowest person.|Small preparations can prevent a difficult day.
H=Outdoor adventures balance curiosity with responsibility for companions and the place.|Maps, forecasts, and local advice each answer different questions.|Turning back can be the strongest decision when conditions change.
V=trail~A path through an outdoor area~I would follow the marked trail.|forecast~A prediction of weather~I would read the forecast.|navigation~Finding a route~Navigation takes practice.|first-aid kit~Supplies for minor injuries~I would carry a first-aid kit.|shelter~Protection from weather~We need shelter before dark.|landmark~A visible feature used for orientation~That landmark helps us turn.|leave no trace~A principle of minimizing damage~I would follow leave no trace.
S=I would pack water first.|The path may be muddy.|Let us check the forecast.|I want to turn back before dark.|We should stay together.|I would take the rubbish home.
T=If the forecast worsened, I would change the route instead of defending the plan.|A first-aid kit helps only when someone knows how to use it.|I would rather finish a short safe trail than force a longer one.|Navigation should use more than a single phone battery.|I wonder how visitors can enjoy wild places without wearing them down.|An adventure includes caring for the people who came with us.

Mysteries and Clues
L=A clue matters because it points toward more than one possibility.|The first explanation can seem convincing but still be wrong.|A careful question may reveal what a witness actually saw.
H=A fair mystery gives readers enough evidence to revise their theories.|Misleading details can create suspense without requiring a dishonest narrator.|The most satisfying solution explains small contradictions as well as the main event.
V=alibi~An account of where someone was~I would check the alibi.|witness~A person who saw an event~The witness may remember differently.|motive~A reason to act~That motive seems weak.|red herring~A misleading clue~The note was a red herring.|timeline~The order of events~I would draw a timeline.|inference~A conclusion drawn from evidence~My inference may be wrong.|contradiction~Two claims that cannot both be true~That contradiction matters.
S=I would check the time.|The note might be a trick.|Can we ask the witness again?|I have two possible answers.|That detail does not fit.|I want one more clue.
T=If a witness sounded certain, I would still compare their account with the timeline.|A good red herring distracts without making the final answer unfair.|I would rather revise my theory than bend every clue to fit it.|The smallest contradiction may reveal the most important mistake.|I wonder when readers know enough to solve the mystery themselves.|A strong ending makes earlier details meaningful in a new way.

Unexplained Places
L=An unfamiliar site can attract stories before anyone studies it carefully.|Old buildings may have lost their original purpose.|Maps and local memories can offer different kinds of clues.
H=Unexplained places invite imagination because evidence is incomplete.|A dramatic legend may hide an ordinary but interesting history.|Respect for the people connected to a site matters while investigating it.
V=ruin~A damaged remainder of a building~I would study the ruin carefully.|archive~A collection of old documents~An archive might hold a map.|legend~A story passed down over time~That legend has several versions.|artifact~An object made or used by people~The artifact may be fragile.|excavation~Careful digging for evidence~Excavation needs permission.|oral history~Memories shared by speaking~An oral history could offer a clue.|hypothesis~A possible explanation to test~My hypothesis could change.
S=I would start with an old map.|The story sounds exciting.|We should not take objects home.|Could a local person explain it?|I see a door in the wall.|There may be a simple answer.
T=If I visited a mysterious site, I would ask who has the right to tell its story.|A legend can be valuable even when it is not a literal explanation.|I would rather protect an artifact than grab a dramatic photograph.|An archive might challenge the most popular version of events.|I wonder why some abandoned places attract attention while others are forgotten.|A careful hypothesis should leave room for evidence we have not found.

Optical Illusions
L=An image can make two equal lines look different.|The brain uses context to interpret what the eyes receive.|Looking again can reveal a hidden pattern.
H=Optical illusions expose useful shortcuts in visual perception.|An error in one setting may reflect a skill that usually helps us navigate.|Explaining an illusion requires separating the image from our experience of it.
V=perception~How the brain interprets senses~My perception changed after a second look.|contrast~A difference between light or colors~Contrast affects the image.|perspective~The impression of depth or position~Perspective made one line seem longer.|afterimage~An image felt after looking away~I noticed an afterimage.|pattern~A repeated arrangement~The pattern seems to move.|blind spot~An area the eye does not detect~A blind spot can hide a dot.|visual cue~A detail helping interpretation~That visual cue suggests depth.
S=Those lines look unequal.|Now I can see the other picture.|The colors seem to move.|I would ask a friend what they see.|I cannot trust the first glance.|The background changes it.
T=If two people saw different images first, I would ask what cues each noticed.|An illusion does not mean vision is broken; it reveals a useful shortcut.|I would rather test the picture than argue from my first impression.|Changing the contrast can transform the same shapes.|I wonder which visual cues artists use to guide attention.|Perception is an active interpretation, not a photograph.

Healthy Eating
L=Meals give the body energy and materials for growth.|A mix of foods can offer different nutrients.|Eating patterns need to fit culture, access, and appetite.
H=Healthy eating is a practical relationship with food, not a single perfect menu.|Different bodies and circumstances require different choices.|Public advice is more useful when it considers price, time, and availability.
V=nutrient~A substance the body uses~Vegetables offer different nutrients.|fiber~A part of food that helps digestion~Beans provide fiber.|protein~A nutrient used to build and repair tissue~Eggs contain protein.|portion~An amount served~My portion depends on hunger.|hydration~Having enough fluid~Hydration matters after sport.|whole grain~A grain retaining more of its parts~I would choose a whole grain.|balanced meal~A meal with varied useful foods~I would plan a balanced meal.
S=I would add fruit to breakfast.|This meal keeps me full.|I like food from my family.|Water sounds good after sport.|I want to learn to cook beans.|I do not need a perfect plate.
T=If I planned meals for a school, I would ask students what is affordable and familiar.|A balanced meal can look different across cultures.|I would rather build a habit I enjoy than follow a strict list for a week.|Fiber and protein can help a meal stay satisfying.|I wonder how food advice changes when time and money are limited.|Healthy eating should include pleasure and enough food.

Stress Management
L=Stress can make a familiar task feel harder.|A short pause may help someone notice what they need.|Talking to a trusted person can make a problem less lonely.
H=Stress responses can be useful briefly but exhausting when pressure continues.|Coping strategies work differently for different people and situations.|Reducing an unfair workload may matter more than adding another relaxation tip.
V=stress signal~A sign that pressure is affecting someone~My stress signal is a tense shoulder.|breathing exercise~A planned way to slow breathing~I would try a breathing exercise.|support network~People available to help~My support network includes a teacher.|workload~The amount of work to do~My workload feels too heavy.|coping strategy~A way to handle difficulty~Walking is one coping strategy.|boundary~A limit protecting time or energy~I need a boundary around study time.|recovery~Time to regain energy~Recovery cannot be rushed.
S=I need a short break.|I would tell someone I trust.|My shoulders feel tense.|One task at a time may help.|I can ask for more time.|Rest is part of the plan.
T=If I felt overwhelmed, I would name the immediate problem before choosing a coping strategy.|A breathing exercise may help in the moment without fixing an unfair workload.|I would rather ask for support early than wait until I cannot sleep.|A boundary around time can protect both study and relationships.|I wonder which pressures schools can change instead of asking students to endure.|Recovery deserves as much planning as the work itself.

Travel Planning
L=A trip begins with decisions about time, money, and transport.|A flexible plan leaves room for delays and discoveries.|Travelers need to check what everyone in the group can manage.
H=Good planning balances a clear purpose with uncertainty.|The cheapest ticket can become expensive when transfers or lost time are counted.|Local conditions and accessibility shape what a realistic itinerary includes.
V=itinerary~A planned sequence of trip activities~I would leave space in the itinerary.|reservation~An arranged place or service~I would confirm the reservation.|connection~A change between journeys~That connection looks too short.|travel budget~Money planned for a trip~My travel budget includes food.|travel insurance~Cover for specified trip problems~I would read the travel insurance terms.|accessibility~Ease of use for varied travelers~Accessibility matters at the station.|contingency plan~An alternative if something changes~We need a contingency plan.
S=I would check the train time.|We need money for meals.|This stop looks too rushed.|Could we rest after arriving?|I want one free afternoon.|Let us plan a backup route.
T=If our connection failed, I would want a clear second route rather than panic.|A travel budget should include ordinary costs beyond the ticket.|I would rather experience fewer places well than rush through a long checklist.|Accessibility can determine whether the whole group can enjoy the itinerary.|I wonder how visitors can support local businesses respectfully.|The best plan gives travelers enough information to make new choices.
`);
