/** Short answers refer to successive three-sentence parts of each A1 story. */
export const focus: Record<string, string[]> = {
  'book-jungle-1': ['A boy arrives', 'Mother Wolf refuses', 'The pack agrees', 'Jungle lessons', 'Finding village fire'],
  'book-jungle-2': ['The monkey warning', 'Mowgli is taken', 'Friends seek help', 'Kaa joins them', 'Mowgli is safe'],
  'book-jungle-3': ['A new home', 'Village and cattle', 'A valley plan', 'The trapped tiger', 'Back to forest'],
  'book-jungle-4': ['A white seal', 'Hunters on beach', 'A long search', 'More unsafe beaches', 'A safe home'],
  'book-alice-1': ['Alice sees Rabbit', 'Into the hole', 'A long fall', 'A little door', 'Bottle and cake', 'A new size'],
  'book-alice-2': ['Alice grows big', 'The Rabbit returns', 'Into the pool', 'Mouse dislikes cats', 'Other wet animals', 'Toward the shore'],
  'book-alice-3': ['Wet animals', 'Everybody wins', 'A long tale', 'Mouse leaves', 'Birds fear Dinah', 'Rabbit returns'],
  'book-alice-4': ['Rabbit gives orders', 'Alice grows big', 'Bill in chimney', 'Cakes from stones', 'Alice runs out', 'A playful puppy'],
  'book-oz-1': ['Dorothy and Toto', 'A storm comes', 'Toto hides', 'The flying house', 'A strange place', 'Green trees'],
  'book-oz-2': ['Free Munchkins', 'Dorothy wants home', 'The yellow road', 'Silver shoes', 'A good witch', 'Toward the Wizard'],
  'book-oz-3': ['A talking Scarecrow', 'Dorothy helps him', 'A wish for brains', 'A new friend', 'Along the road', 'A hard path'],
  'book-oz-4': ['Broken yellow road', 'Rest by water', 'Dorothy misses home', 'The farmer’s Scarecrow', 'Into the forest', 'A house at night'],
  'book-peter-1': ['Darling children', 'Stories of Peter', 'Dreams of Neverland', 'Strange leaves', 'The boy appears'],
  'book-peter-2': ['Peter loses shadow', 'A hidden shadow', 'Michael’s medicine', 'Nana goes outside', 'Parents leave', 'Nana barks'],
  'book-peter-3': ['Fairy finds shadow', 'Peter cannot fix it', 'Wendy sews shadow', 'Children learn flying', 'Out the window', 'Empty beds'],
  'book-peter-4': ['Across the sea', 'Cold hungry children', 'Michael starts falling', 'Peter catches him', 'Island in sight', 'Wendy remembers home'],
  'book-sherlock-1': ['The king’s problem', 'Holmes watches Irene', 'A false fire', 'Irene finds photo', 'Irene leaves', 'A letter and gift'],
  'book-sherlock-2': ['Wilson’s strange job', 'A cellar clue', 'A bank nearby', 'Police wait', 'Thieves in tunnel', 'Money stays safe'],
  'book-sherlock-3': ['Mary loses Hosmer', 'Stepfather and letters', 'A strange disguise', 'Money keeps Mary home', 'Holmes finds truth', 'Mary does not know'],
  'book-sherlock-4': ['James is blamed', 'Marks near pool', 'Turner’s old secret', 'Turner writes truth', 'James is freed', 'Alice can stay'],
  'book-aesop-1': ['Lion catches Mouse', 'Lion lets it go', 'Lion in net', 'Mouse bites ropes', 'Lion gets free', 'Friends walk away'],
  'book-aesop-2': ['Lamb drinks water', 'Wolf blames Lamb', 'An old insult', 'A family excuse', 'Wolf comes closer', 'Lamb is attacked'],
  'book-aesop-3': ['Ass hears song', 'Dew on leaves', 'Ass stops eating', 'Too little food', 'Ass grows weak', 'Grasshopper sings'],
  'book-aesop-4': ['Bone in throat', 'Crane can help', 'A promised gift', 'Crane pulls bone', 'Wolf shows teeth', 'Crane walks away']
};

export const concreteWords: Record<string, string[]> = {
  'book-jungle-1': ['tiger', 'wolf', 'cave', 'bear', 'fire'],
  'book-jungle-2': ['monkeys', 'trees', 'bird', 'snake', 'wall'],
  'book-jungle-3': ['village', 'clothes', 'cattle', 'valley', 'skin'],
  'book-jungle-4': ['seal', 'island', 'beach', 'rocks', 'sea'],
  'book-alice-1': ['book', 'rabbit', 'watch', 'hole', 'key'],
  'book-alice-2': ['cake', 'key', 'fan', 'pool', 'Mouse'],
  'book-alice-3': ['pool', 'feathers', 'race', 'sweets', 'birds'],
  'book-alice-4': ['house', 'gloves', 'chimney', 'stones', 'puppy'],
  'book-oz-1': ['farm', 'dog', 'storm', 'bed', 'flowers'],
  'book-oz-2': ['house', 'witch', 'road', 'shoes', 'city'],
  'book-oz-3': ['field', 'straw', 'pole', 'brain', 'wood'],
  'book-oz-4': ['bricks', 'holes', 'bread', 'corn', 'forest'],
  'book-peter-1': ['dog', 'nursery', 'boy', 'leaves', 'window'],
  'book-peter-2': ['window', 'shadow', 'drawer', 'medicine', 'yard'],
  'book-peter-3': ['fairy', 'shadow', 'drawer', 'needle', 'beds'],
  'book-peter-4': ['sea', 'birds', 'food', 'wind', 'island'],
  'book-sherlock-1': ['king', 'photo', 'house', 'fire', 'letter'],
  'book-sherlock-2': ['shop', 'cellar', 'bank', 'tunnel', 'money'],
  'book-sherlock-3': ['man', 'letters', 'machine', 'glasses', 'money'],
  'book-sherlock-4': ['father', 'valley', 'pool', 'paper', 'secret'],
  'book-aesop-1': ['tree', 'paw', 'Mouse', 'net', 'ropes'],
  'book-aesop-2': ['water', 'stream', 'Lamb', 'Wolf', 'family'],
  'book-aesop-3': ['Ass', 'song', 'drops', 'leaves', 'legs'],
  'book-aesop-4': ['food', 'bone', 'throat', 'beak', 'teeth']
};

export const simpleMeanings: Record<string, string> = {
  tiger: 'a big striped cat', wolf: 'a wild dog', cave: 'a hole in rock', bear: 'a large furry animal', fire: 'hot bright flames',
  monkeys: 'animals that climb trees', trees: 'tall plants with leaves', bird: 'an animal with wings', snake: 'a long animal with no legs', wall: 'the side of a building',
  village: 'a small town', clothes: 'things people wear', cattle: 'large farm animals', valley: 'low land between hills', skin: 'the outside of a body',
  seal: 'an animal that swims in the sea', island: 'land with water all around', beach: 'sand beside the sea', rocks: 'hard pieces of stone', sea: 'a great body of salt water',
  book: 'pages with words to read', rabbit: 'a small animal with long ears', watch: 'a small clock', hole: 'an open space in something', key: 'a tool that opens a lock',
  cake: 'a sweet food', fan: 'a thing that moves air', pool: 'a small body of water', mouse: 'a small animal with a long tail',
  feathers: 'soft parts on a bird', race: 'a run to see who is fastest', sweets: 'small sugary foods', birds: 'animals with wings',
  house: 'a place to live', gloves: 'clothes for hands', chimney: 'a way for smoke to leave', stones: 'small pieces of rock', puppy: 'a young dog',
  farm: 'land for crops or animals', dog: 'a common pet animal', storm: 'strong wind and rain', bed: 'a place to sleep', flowers: 'colourful parts of plants',
  witch: 'a person with magic in stories', road: 'a path for walking or driving', shoes: 'things worn on feet', city: 'a large town',
  field: 'open land', straw: 'dry plant stems', pole: 'a long upright stick', brain: 'part inside a head for thinking', wood: 'a place with many trees',
  bricks: 'blocks used to build', holes: 'open spaces in something', bread: 'food made from flour', corn: 'a tall food plant', forest: 'a large area of trees',
  nursery: 'a room for children', boy: 'a young male person', leaves: 'flat green parts of plants', window: 'glass opening in a wall',
  shadow: 'a dark shape made by light', drawer: 'a sliding box in furniture', medicine: 'something taken when ill', yard: 'open ground by a house',
  fairy: 'a tiny magic person in stories', needle: 'a thin tool for sewing', beds: 'places to sleep',
  food: 'things we eat', wind: 'moving air', king: 'a man who rules a country', photo: 'a picture made by a camera', letter: 'a written message',
  shop: 'a place to buy things', cellar: 'a room below a building', bank: 'a place that keeps money', tunnel: 'a path under the ground', money: 'coins or notes for buying',
  man: 'an adult male person', letters: 'written messages', machine: 'a tool with moving parts', glasses: 'lenses worn over eyes',
  father: 'a male parent', paper: 'thin material for writing', secret: 'something kept hidden', tree: 'a tall plant', paw: 'an animal foot', net: 'woven ropes for catching', ropes: 'strong thick strings',
  water: 'a drinkable clear liquid', stream: 'a small moving river', lamb: 'a young sheep', family: 'people who care for each other',
  ass: 'an animal like a small horse', song: 'words and sounds sung together', drops: 'tiny bits of liquid', legs: 'body parts used to walk',
  bone: 'hard part inside a body', throat: 'the passage inside a neck', beak: 'a bird’s hard mouth', teeth: 'hard parts used to bite',
  garden: 'land where plants grow', gate: 'a door in a fence', coat: 'warm clothing for the body', basket: 'a container to carry things', cat: 'a small furry pet',
  duck: 'a bird that swims', eggs: 'round things from which birds hatch', fox: 'a wild animal with a bushy tail', squirrel: 'a small animal with a bushy tail', lake: 'a large body of water', owl: 'a bird that hunts at night', nuts: 'hard seeds some animals eat', tail: 'a body part behind an animal',
  hen: 'a female chicken', grain: 'a small seed of a food plant', wheat: 'a plant used to make bread', flour: 'powder used to make bread', woman: 'an adult female person', oven: 'a place to bake food', cow: 'a large farm animal', bears: 'large furry animals', bowls: 'round dishes for food', chair: 'a seat for one person', leather: 'animal skin used to make shoes', elves: 'small magic helpers in stories', table: 'furniture with a flat top'
};

export const talkQuestions: Record<string, string> = {
  'book-jungle-1': 'Would you live with the wolves?',
  'book-jungle-2': 'Should Mowgli listen to Baloo next time?',
  'book-jungle-3': 'Where should Mowgli live now?',
  'book-jungle-4': 'Would you follow Kotick to the new beach?',
  'book-alice-1': 'Would you follow the White Rabbit?',
  'book-alice-2': 'Would you help the Mouse out?',
  'book-alice-3': 'Should everyone get a race prize?',
  'book-alice-4': 'Would you enter the Rabbit’s house?',
  'book-oz-1': 'Would you go back for Toto?',
  'book-oz-2': 'Would you walk to the Wizard?',
  'book-oz-3': 'Would you help the Scarecrow?',
  'book-oz-4': 'Would you sleep in the forest?',
  'book-peter-1': 'Would you tell Mother about Peter?',
  'book-peter-2': 'Should Nana sleep inside with the children?',
  'book-peter-3': 'Would you fly away with Peter?',
  'book-peter-4': 'Would you keep flying or go home?',
  'book-sherlock-1': 'Should Irene keep the photo?',
  'book-sherlock-2': 'Would you take Wilson’s easy job?',
  'book-sherlock-3': 'Should Holmes tell Mary the truth?',
  'book-sherlock-4': 'Should Holmes show Turner’s paper?',
  'book-aesop-1': 'Would you free the little Mouse?',
  'book-aesop-2': 'Was the Wolf fair to the Lamb?',
  'book-aesop-3': 'Should the Ass eat only dew?',
  'book-aesop-4': 'Should the Crane help the Wolf?'
};
