// Curated, evergreen source sentences. Each row is title | overview | four facts | three discussion questions.
// The overview and facts are deliberately short enough to support the A1 children's level.
const kids = `
Cats|Cats are small hunters that often live with people.|Cats use whiskers to feel nearby objects.|Their claws help them climb and grip.|Cats can see well in dim light.|A kitten learns by playing with others.|Would you rather watch cats climb or play?|Should cats have quiet places at home?|How can people help a shy cat?
Dogs|Dogs are social animals that often live with people.|Dogs use their noses to explore.|Puppies learn through play and practice.|Different dogs have different kinds of fur.|Dogs need exercise and time with others.|Would you rather walk or train a dog?|What makes a dog feel safe?|Should every dog learn a simple game?
Horses|Horses are large animals that can run fast.|A horse has strong legs and hard hooves.|Horses eat grass and other plants.|Their ears can turn toward sounds.|Horses often rest while standing.|Would you rather groom or ride a horse?|What space does a horse need?|How should people treat working horses?
Elephants|Elephants are large animals with flexible trunks.|A trunk can lift food and drink water.|Elephants live in family groups.|Their wide ears help release heat.|Young elephants learn from older relatives.|Would you rather see elephants eat or play?|Why might a family group matter?|How can people give elephants more space?
Giraffes|Giraffes are tall animals from African grasslands.|A giraffe reaches leaves with its long neck.|Its tongue helps pull leaves from branches.|Each giraffe has its own spot pattern.|Giraffes can spread their legs to drink.|Would you rather draw spots or a long neck?|What helps giraffes reach food?|Should animals have room to roam?
Zebras|Zebras are striped animals that eat grass.|Each zebra has a different stripe pattern.|Zebras often travel in groups.|Their ears move toward new sounds.|A zebra can run to avoid danger.|Would you rather count stripes or watch a herd?|How does a group help zebras?|Which animal pattern do you like best?
Lions|Lions are big cats that live in groups.|A lion group is called a pride.|Lions rest for much of the day.|Their rough tongues help clean fur.|Lion cubs learn through chasing games.|Would you rather watch cubs or adults?|Why might lions live together?|What can a cub learn through play?
Tigers|Tigers are big striped cats that usually live alone.|Tiger stripes help hide them among plants.|Tigers can swim across water.|Each tiger has a different stripe pattern.|A tiger walks quietly on soft paws.|Would you rather see a tiger swim or walk?|Why are stripes useful in a forest?|Should wild cats have quiet habitats?
Pandas|Pandas are bears that eat mostly bamboo.|Pandas hold food with a special wrist bone.|Bamboo grows in tall green stems.|Young pandas stay close to their mothers.|Pandas spend much time finding enough food.|Would you rather watch a panda climb or eat?|Why does a panda need many bamboo plants?|How could forests help pandas?
Koalas|Koalas are tree-dwelling animals from Australia.|Koalas eat leaves from certain eucalyptus trees.|Their hands grip branches tightly.|Koalas sleep for many hours.|Young koalas ride on their mothers' backs.|Would you rather see a koala climb or rest?|Why do koalas need healthy trees?|What makes a safe home for a koala?
Kangaroos|Kangaroos are jumping animals from Australia.|A kangaroo moves with strong back legs.|A mother carries her baby in a pouch.|Its long tail helps it balance.|Kangaroos eat grasses and other plants.|Would you rather jump or balance like one?|How does a pouch help a baby?|What spaces suit jumping animals?
Penguins|Penguins are birds that swim instead of flying.|Penguin wings work like underwater flippers.|Many penguins live near cold seas.|Parents take turns caring for chicks.|Penguins use calls to find family members.|Would you rather watch penguins swim or walk?|How do parents help their chicks?|Why are calls useful in a crowd?
Polar Bears|Polar bears are large bears of the Arctic.|Thick fur helps keep a bear warm.|Wide paws spread weight on snow.|Polar bears can swim between pieces of ice.|Cubs stay with their mothers to learn.|Would you rather study fur or paws?|How does ice help polar bears?|What might a cub learn from its mother?
Dolphins|Dolphins are sea mammals that breathe air.|Dolphins come to the surface to breathe.|They use sounds to find nearby objects.|Dolphins often swim in social groups.|A young dolphin learns from its mother.|Would you rather hear dolphin calls or watch swimming?|Why must dolphins reach the surface?|How can sound help underwater?
Whales|Whales are large mammals that live in oceans.|Whales breathe air through holes on top.|Some whales filter small food from water.|Other whales hunt fish and squid.|Whale calves drink milk from their mothers.|Would you rather see a whale dive or surface?|Why do whales need air?|How are whale calves like human babies?
Sharks|Sharks are fish with skeletons made of cartilage.|Sharks sense movement in the water.|Different sharks eat different kinds of food.|Many sharks have rows of replacement teeth.|Sharks help keep ocean food webs balanced.|Would you rather study shark fins or senses?|Why do sharks need healthy oceans?|What surprises you about shark teeth?
Sea Turtles|Sea turtles are reptiles that live in oceans.|Sea turtles use flippers to swim.|Females lay eggs on sandy beaches.|Young turtles move toward the sea.|Some sea turtles eat jellyfish or plants.|Would you rather watch turtles swim or nest?|Why are clean beaches important?|How could people help young turtles?
Frogs|Frogs are animals that begin life in water.|A tadpole grows legs as it changes.|Adult frogs breathe through lungs and skin.|Many frogs catch insects with sticky tongues.|Frogs often call to find mates.|Would you rather watch a tadpole or frog?|Why do frogs need clean water?|Which frog sound would you invent?
Butterflies|Butterflies are insects with four colorful wings.|A caterpillar changes inside a chrysalis.|Butterflies drink nectar with a long tube.|Their wings can show warning colors.|Many butterflies help move pollen between flowers.|Would you rather see a caterpillar or butterfly?|Why do butterflies visit flowers?|Should gardens leave space for insects?
Bees|Bees are insects that visit flowers for food.|Bees carry pollen between many flowers.|Some bees live together in hives.|Other bees make nests alone.|Bees use body movements to share directions.|Would you rather watch bees fly or communicate?|Why do flowers need visiting insects?|How can a garden welcome bees?
Dinosaurs|Dinosaurs were animals that lived long ago.|Some dinosaurs ate plants, and others ate animals.|Birds descended from one dinosaur group.|Fossils help us learn about dinosaurs.|Dinosaurs had many sizes and shapes.|Would you rather study a footprint or bone?|Which dinosaur body shape interests you?|How can fossils change our ideas?
Fossils|Fossils are traces of ancient living things.|Some fossils show bones or shells.|Other fossils show tracks or leaf marks.|Rock layers can protect old traces.|Scientists compare fossils to learn about life.|Would you rather find a shell or footprint?|What could a footprint tell us?|Should people leave fossils for museums?
The Moon|The Moon travels around Earth.|Sunlight makes different moon shapes visible.|The Moon has rocky ground and craters.|People see the same side most nights.|Its gravity helps make ocean tides.|Would you rather draw a crater or moon shape?|Why does the Moon look different?|What would you study on the Moon?
The Sun|The Sun is the star near Earth.|Sunlight gives Earth light and warmth.|Plants use sunlight to make food.|Earth turns, making day and night.|The Sun looks small because it is far.|Would you rather watch sunrise or sunset?|Why do plants need sunlight?|How does sunlight change your day?
Planets|Planets travel around stars.|Our planets travel around the Sun.|Some planets are rocky; others are mostly gas.|Planets differ in size and temperature.|Earth is a planet with liquid water.|Would you rather visit a rocky or gas planet?|Which planet feature would you investigate?|How is Earth special to you?
Stars|Stars are hot balls of glowing gas.|The Sun is a star near Earth.|Stars appear tiny because they are distant.|Groups of stars can form patterns.|Some stars look brighter than others.|Would you rather map stars or watch the Moon?|Why do stars look small?|What pattern would you draw in the sky?
Rockets|Rockets move by pushing gas backward.|A rocket needs fuel to launch.|Some rockets carry people or supplies.|Rocket stages can separate during flight.|Spacecraft use rockets to leave Earth.|Would you rather design a rocket or spacecraft?|Why does a rocket need fuel?|What would you send into space?
Astronauts|Astronauts are people trained for space travel.|Astronauts practice working in special suits.|They exercise to keep their bodies strong.|Teams plan meals and tasks in space.|Astronauts study Earth from above.|Would you rather train or work in space?|Which task would you try first?|Why is teamwork important in space?
Volcanoes|Volcanoes are openings where melted rock can escape.|Melted rock is called lava above ground.|Some volcanoes form mountains over time.|Volcanic ash can make dark clouds.|Scientists watch volcanoes for signs of change.|Would you rather study lava or ash?|Why do people watch volcanoes?|What could a model volcano show?
Earthquakes|Earthquakes make the ground shake.|Earth's rocky plates move slowly.|A sudden plate movement can cause shaking.|Buildings can be designed to move safely.|Scientists measure shaking with special tools.|Would you rather build or test a safe model?|Why should buildings bend a little?|What would you put in an emergency kit?
Mountains|Mountains rise high above nearby land.|Some mountains form when land plates meet.|Higher places can be colder than valleys.|Mountain slopes shelter many kinds of plants.|Rivers often begin in mountain areas.|Would you rather walk a valley or slope?|Why can mountains have cold tops?|How might a mountain shape a river?
Rivers|Rivers are moving streams of water.|Rain and melting snow can feed rivers.|Rivers flow toward lakes or seas.|Many animals live beside riverbanks.|People use bridges to cross rivers.|Would you rather cross by bridge or boat?|Why do riverbanks support animals?|How could we keep a river clean?
Oceans|Oceans are huge bodies of salty water.|Waves move across the ocean surface.|Many creatures live at different depths.|Ocean water helps shape weather.|Currents carry water around the world.|Would you rather explore waves or deep water?|Why do animals live at different depths?|How can people care for oceans?
Coral Reefs|Coral reefs are underwater homes built by tiny animals.|Coral animals make hard outer skeletons.|Many fish shelter among reef shapes.|Warm shallow water supports many reefs.|Clear water helps sunlight reach reef life.|Would you rather see reef fish or coral shapes?|Why do fish shelter near coral?|How could people protect reef water?
Rainforests|Rainforests are forests with much rain.|Tall trees make a leafy roof.|Smaller plants grow below that roof.|Many animals live at different tree levels.|Rainforest plants help hold water in soil.|Would you rather explore treetops or forest floor?|Why are there many layers?|How can trees help the soil?
Deserts|Deserts are places with very little rain.|Some deserts are hot; others are cold.|Many desert animals rest during hot days.|Some plants store water in thick parts.|Desert nights can be much cooler.|Would you rather study desert plants or animals?|Why might animals rest by day?|How could a plant save water?
Forests|Forests are places where many trees grow.|Tree leaves catch sunlight for food.|Fallen leaves add material to soil.|Birds and insects use trees for shelter.|Different forests grow in different climates.|Would you rather explore trees or forest floor?|Why are fallen leaves useful?|What makes a forest feel alive?
Seasons|Seasons change as Earth moves around the Sun.|Earth's tilt changes how sunlight reaches places.|Some places have four clear seasons.|Other places have wet and dry seasons.|Plants and animals respond to seasonal changes.|Would you rather have rain or snow seasons?|How do seasons change daily life?|Which seasonal change would you observe?
Rain|Rain falls from clouds as water drops.|Warm air can carry water vapor upward.|Cloud drops join and become heavy.|Rain gives water to plants and rivers.|Rainfall differs from place to place.|Would you rather walk in light or heavy rain?|Why do plants need rain?|How does rain change a school day?
Snow|Snow is frozen water that falls from clouds.|Snowflakes form from tiny ice crystals.|Snow can cover and protect plant roots.|Sunlight can melt snow into water.|Wet snow can stick together in balls.|Would you rather catch or build with snow?|Why does snow melt in warmth?|How does snow change a landscape?
Wind|Wind is air moving from place to place.|Uneven heating helps create moving air.|Wind can push clouds across the sky.|Some seeds travel on the wind.|People use wind to move sails.|Would you rather fly a kite or sail?|How can wind help a seed?|When does wind feel helpful?
Clouds|Clouds are tiny water drops or ice crystals.|Warm air rises and cools into clouds.|Different clouds have different shapes.|Some clouds bring rain or snow.|Clouds can shade the ground below.|Would you rather draw a low or high cloud?|How can clouds change sunlight?|What might cloud shapes tell us?
Rainbows|Rainbows appear when light meets water drops.|Water bends and separates sunlight colors.|A rainbow appears opposite the Sun.|Rainbows look different from different places.|You need light and water to see one.|Would you rather see a rainbow after rain or mist?|Why do rainbows show colors?|Can two people see the same rainbow?
Water Cycle|The water cycle moves water around Earth.|Sunlight helps water rise as vapor.|Cooling vapor can form clouds.|Water falls again as rain or snow.|Rivers return some water to oceans.|Would you rather follow a drop through clouds or rivers?|Why does the Sun matter here?|Where might a drop travel next?
Plant Growth|Plants grow from seeds when conditions suit them.|Roots take in water from soil.|Leaves use sunlight to make food.|Stems hold leaves toward the light.|Flowers can make new seeds.|Would you rather grow flowers or vegetables?|Why do roots need soil?|What helps a seed begin growing?
Cooking|Cooking changes food using heat and other steps.|People wash hands before preparing food.|Heat can make some foods softer.|Recipes list ingredients and steps.|Different cultures cook with different flavors.|Would you rather chop or stir ingredients?|Why do recipes have steps?|Which flavor would you try in a meal?
Baking|Baking cooks food with heat in an oven.|Dough can rise when gas forms inside.|Flour helps give dough its shape.|Measuring helps a recipe work well.|Bread smells different after it bakes.|Would you rather bake bread or muffins?|Why should bakers measure ingredients?|What might change if dough gets wetter?
Fruits|Fruits grow from flowers on many plants.|Many fruits contain seeds inside.|Apples grow on trees; berries grow elsewhere.|Fruit colors can change as they ripen.|People eat fruit fresh or cooked.|Would you rather try a crunchy or soft fruit?|Why do fruits contain seeds?|How can color show ripeness?
Vegetables|Vegetables can come from different plant parts.|Carrots are roots; lettuce gives us leaves.|Some vegetables grow above the ground.|Others grow below the soil.|Cooking can change their taste and texture.|Would you rather grow roots or leaves?|Why do vegetables taste different when cooked?|Which plant part would you eat?
Breakfast|Breakfast is a meal eaten after sleeping.|Breakfast foods differ around the world.|A balanced meal can include several food groups.|Some people eat breakfast at home.|Others carry breakfast on a journey.|Would you rather eat warm or cold breakfast?|Why do morning meals differ by place?|What makes a breakfast easy to prepare?
School Lunch|School lunch is a meal during the school day.|Some students bring food from home.|Others eat food made at school.|Water is a useful drink with lunch.|Lunch gives classmates time to talk.|Would you rather pack or choose lunch?|How can lunch time help friendships?|What makes a lunch easy to carry?
Caring for Pets|Pet care means meeting an animal's daily needs.|Pets need suitable food and clean water.|Many pets need exercise and attention.|A safe space helps a pet rest.|Different animals need different kinds of care.|Would you rather care for fish or a dog?|Why does a pet need quiet space?|How can a family share pet jobs?
School Day|A school day has lessons, breaks, and routines.|Students may study different subjects each day.|Breaks give time to move and talk.|Classrooms use materials for different tasks.|A plan helps everyone know what comes next.|Would you rather start with art or reading?|Why do schools include breaks?|Which routine helps you learn?
Classroom Rules|Classroom rules help people learn together.|Listening lets others finish their ideas.|Sharing materials gives everyone a chance.|Rules can help make games fair.|Students can discuss why a rule matters.|Would you rather write or draw class rules?|Which rule helps quiet students?|Should students help choose class rules?
Making Friends|Making friends often begins with a kind hello.|Shared games can help people meet.|Good friends listen to each other.|Friends can enjoy different interests.|A small invitation can include someone new.|Would you rather invite someone to play or talk?|What makes a kind first question?|Can different interests help a friendship?
Family Traditions|Family traditions are things families do again.|Some families cook a special meal.|Others tell stories or visit relatives.|Traditions can change as families grow.|People may have different traditions at home.|Would you rather cook or tell a story?|Why do families repeat traditions?|Can a new tradition start today?
Birthday Parties|Birthday parties mark another year of someone's life.|People may play games or share food.|Some parties are small and quiet.|Others bring many friends together.|A kind message can be a gift.|Would you rather play games or make food?|What makes a guest feel welcome?|Can a quiet party still be fun?
Festivals Around the World|Festivals bring people together for shared activities.|Some festivals include music and dancing.|Others include food, lights, or stories.|Festival customs differ among communities.|Visitors can ask respectful questions about customs.|Would you rather hear music or try festival food?|How can visitors show respect?|Why do communities enjoy celebrations?
Holidays|Holidays give time away from usual routines.|People may travel or stay near home.|Some holidays follow family or community customs.|Free time can include rest and play.|Holiday plans differ between families.|Would you rather explore or relax on holiday?|Can staying home feel special?|What activity would you plan together?
Jobs People Do|Jobs are ways people help and earn money.|Builders make places for people to use.|Drivers help move people and goods.|Cooks prepare food for others.|Many jobs need people to work together.|Would you rather build or cook at work?|Why do many jobs need teamwork?|Which job would you like to observe?
Soccer|Soccer is a team game played with a ball.|Players usually move the ball with their feet.|Teams try to score in a goal.|Passing helps teammates work together.|A goalkeeper guards one team's goal.|Would you rather pass or shoot the ball?|Why do teams need a goalkeeper?|What makes a fair soccer game?
Basketball|Basketball is a team game with two hoops.|Players bounce the ball while moving.|Teams score by putting the ball through hoops.|Passing can create a clear shot.|Players need space to move safely.|Would you rather pass or take a shot?|Why is passing useful?|How can a team include everyone?
Swimming|Swimming means moving through water with your body.|Arms and legs push against water.|Breathing matters when learning to swim.|Different strokes use different movements.|A trained adult should watch young swimmers.|Would you rather practice floating or kicking?|Why does breathing matter in water?|What helps a new swimmer feel confident?
Cycling|Cycling means traveling on a bicycle.|Pedals turn a bike's wheels.|A helmet helps protect a rider's head.|Brakes help slow the bicycle.|Cyclists watch roads and people around them.|Would you rather cycle in a park or lane?|Why should riders check brakes?|How can cyclists share a path?
Running|Running moves the body faster than walking.|Arms help balance the moving body.|Runners breathe harder during exercise.|People can run short or long distances.|Rest helps muscles recover after activity.|Would you rather sprint or run slowly?|Why do runners need rest?|How can friends make running fun?
Dancing|Dancing uses body movements with rhythm.|Music can help dancers keep time.|People dance alone, in pairs, or groups.|Different cultures have different dance styles.|Practice helps a group move together.|Would you rather dance alone or with friends?|Why does rhythm help dancers?|Can dancing tell a story?
Board Games|Board games use pieces, turns, and rules.|Some games use dice to choose moves.|Other games ask players to make plans.|Players often learn by trying again.|Fair play helps everyone enjoy the game.|Would you rather roll dice or plan moves?|Why do games need rules?|Can losing teach a useful skill?
Puzzles|Puzzles ask people to find a solution.|A jigsaw picture has pieces that fit.|Some puzzles use words or numbers.|Looking for patterns can help.|Friends may solve a puzzle together.|Would you rather solve a picture or word puzzle?|Why do patterns help?|When is teamwork useful for puzzles?
Building Blocks|Building blocks can make many shapes.|Wide bases can help towers stand.|Different block shapes fit in different ways.|Builders can test and change a design.|Sharing blocks lets friends build together.|Would you rather build a tower or bridge?|Why does a wide base help?|How can friends share one design?
Kites|Kites are light shapes flown in wind.|Wind pushes against a kite's surface.|A string helps a person guide it.|Tails can help some kites balance.|Open spaces make kite flying easier.|Would you rather build or fly a kite?|Why does a kite need wind?|Which kite shape might fly well?
Playgrounds|Playgrounds are spaces for outdoor play.|Slides, swings, and climbing frames offer choices.|Children can practice balance and movement.|Taking turns helps everyone use equipment.|Safe play includes watching for others.|Would you rather swing or climb?|Why should people take turns?|What would you add to a playground?
Superheroes|Superheroes are imagined characters with unusual abilities.|A hero may solve problems through teamwork.|Some heroes help without special powers.|Stories give heroes difficult choices.|A hero's actions show what matters to them.|Would you rather fly or talk to animals?|Can teamwork beat a special power?|What makes a hero kind?
Robots|Robots are machines that can follow instructions.|Sensors help some robots notice surroundings.|Motors can move robot parts.|People design robots for different tasks.|A robot still needs careful human choices.|Would you rather design a robot for home or school?|Why do robots need sensors?|Which task should a robot do?
Trains|Trains carry people or goods on tracks.|Carriages join behind a train engine.|Stations help travelers board safely.|Tracks guide wheels along a route.|Some trains run using electricity.|Would you rather travel by day or night train?|Why do trains use tracks?|What makes a station easy to use?
Airplanes|Airplanes carry people through the air.|Wings help an airplane stay aloft.|Engines push the plane forward.|Pilots use controls to guide flight.|Airports have spaces for takeoff and landing.|Would you rather watch takeoff or landing?|Why do planes need wings?|What would you pack for a flight?
Boats|Boats move people or goods over water.|Some boats use sails and wind.|Others use engines or human paddles.|A wide hull can help a boat float.|Boat size depends on its job.|Would you rather paddle or sail?|Why do boats have different shapes?|Which boat suits a quiet river?
Musical Instruments|Musical instruments make sounds in many ways.|Drums sound when their surfaces vibrate.|Strings vibrate on guitars and violins.|Wind instruments need moving air.|Musicians practice to play together.|Would you rather play drums or strings?|Why do instruments make different sounds?|How could a group start a song?
Drawing|Drawing makes images with lines and shapes.|Pencils can make light or dark marks.|Artists use shapes to plan pictures.|Practice helps hands control lines.|A drawing can show real or imagined things.|Would you rather draw from life or imagination?|How can lines show movement?|Can a simple shape tell a story?
Painting|Painting makes images with colored material.|Painters mix colors to make new shades.|Brushes can make wide or thin marks.|Water changes how some paints spread.|A painting can show a mood or place.|Would you rather paint with wide or thin brushes?|How can color show a feeling?|What would you paint from memory?
The Five Senses|The five senses help us notice the world.|Eyes detect light and shapes.|Ears detect sounds around us.|Skin helps us feel touch and temperature.|Noses and tongues help us smell and taste.|Would you rather explore by touch or sound?|Which sense helps you cook?|How do senses help us stay aware?
`.trim().split('\n');

export type ContentSeed = { title: string; overview: string; facts: string[]; angles: string[] };
function parse(lines: string[]): ContentSeed[] {
  return lines.map((line) => {
    const parts = line.trim().split('|');
    if (parts.length !== 9) throw new Error(`Invalid Round 18 content row: ${line}`);
    return { title: parts[0], overview: parts[1], facts: parts.slice(2, 6), angles: parts.slice(6) };
  });
}
export const kidsContent = parse(kids);

const teens = `
Video Games|Video games are interactive systems built around rules and player choices.|Some games reward planning rather than speed.|A difficulty setting can change a player's challenge.|Cooperative games ask players to share goals.|Game sound can signal a change before visuals do.|Should games reward practice or natural skill more?|When does a challenge stop being fun?|Can a game teach something without a lesson?
Game Design|Game design shapes the choices players make.|Rules determine what actions a player can try.|Playtesting reveals confusing instructions or unfair challenges.|Feedback helps players understand their progress.|Designers revise games after watching real players.|Should a game explain every rule at the start?|Which matters more: freedom or clear goals?|Can a frustrating game still be well designed?
Esports|Esports are organized competitions in video games.|Teams practice communication as well as game skills.|Competition rules aim to make matches fair.|Spectators can follow tactics during a match.|Training includes rest as well as practice.|Should esports count as sport?|Does team strategy matter more than reflexes?|How should players handle losing publicly?
Social Media|Social media lets people share and respond online.|A feed selects which posts users see.|A short post can travel beyond its first audience.|Comments can change the tone of a discussion.|People choose what parts of life to share.|Should feeds show newest posts or chosen posts?|Can online sharing strengthen real friendships?|What should someone think before posting?
Online Privacy|Online privacy concerns who can see personal information.|A strong password helps protect an account.|Privacy settings limit some kinds of sharing.|Screenshots can preserve a post after deletion.|Sharing less information can reduce unwanted attention.|Should accounts start with strict privacy settings?|Who should decide what a friend shares?|Is convenience worth giving up some privacy?
Screen Time|Screen time measures time spent using digital devices.|The purpose of a screen session matters.|A call with friends differs from endless scrolling.|Breaks can help eyes and bodies rest.|Notifications can interrupt a difficult task.|Should homework screen time count differently?|Which device habit would you change first?|Can a screen help people spend time together?
Digital Footprints|A digital footprint is the trail left by online actions.|Public comments may remain easy to find.|Search results can show old posts without context.|Private messages can still be copied.|People can review their accounts before sharing more.|Should old posts represent who someone is now?|Who owns a picture posted by a friend?|How much should schools consider online history?
Internet Memes|Internet memes are ideas copied and changed online.|An image can gain new meanings through captions.|A joke often depends on shared background knowledge.|Memes spread when people make their own versions.|A funny post can still exclude someone.|When does a meme become a kind joke?|Should creators receive credit for meme ideas?|Can a meme explain an important idea well?
Artificial Intelligence|Artificial intelligence uses computer systems to find patterns and produce outputs.|Training examples shape what a system learns.|An AI answer can sound confident and be wrong.|People still choose how to use the output.|Checking sources matters when decisions have consequences.|Should students disclose help from AI tools?|Which tasks need a human final decision?|Can AI creativity be judged like human creativity?
Robots and Automation|Automation lets machines repeat tasks with limited human direction.|Sensors can help robots respond to surroundings.|Factories use robots for precise repeated movements.|People maintain and program automated systems.|Changing tasks can reshape what workers do.|Which repetitive task should robots handle?|What work should always involve people?|Can automation make a job more interesting?
Virtual Reality|Virtual reality creates a simulated space people can explore.|Headsets track movement to change the view.|A shared virtual space can connect distant people.|Simulation can help people practice unfamiliar tasks.|Comfort and accessibility differ between users.|Is a virtual visit as valuable as a real one?|What should designers do for motion discomfort?|Where could a simulation help learning?
Coding|Coding means writing instructions for computers.|Programs use steps, choices, and repeated actions.|A small error can change an output.|Testing helps programmers find and fix problems.|Readable code helps people work together.|Should everyone learn basic coding?|Which matters more: speed or clarity?|Can debugging teach patience?
Cybersecurity|Cybersecurity protects digital systems and information.|Updates can repair known software weaknesses.|Extra login checks reduce account takeovers.|Suspicious links may lead to fake pages.|Good security depends on human habits too.|Should schools require extra login checks?|How much convenience should safety cost?|Who should teach young people about scams?
Online Learning|Online learning uses digital tools to connect learners and materials.|Recorded lessons let students pause and replay.|Live discussions can build a sense of class.|Unequal internet access changes who can join.|Clear instructions matter when help is distant.|Should students choose online or classroom lessons?|When is a recording better than a live class?|How can an online class include quiet learners?
Digital Art|Digital art uses software as a creative material.|Layers let artists revise separate parts of images.|A stylus can imitate a pencil or brush.|Undo tools encourage experiments without losing earlier work.|The finished work still reflects human choices.|Does an undo button change creativity?|Should digital and painted art be judged alike?|Which tool best helps an artist experiment?
Friendship|Friendship grows through trust, shared time, and care.|Friends can disagree without ending a relationship.|Listening can reveal what a friend actually needs.|Different friends may support different parts of life.|Respecting boundaries can strengthen a friendship.|Should close friends share every secret?|Is honesty always kinder than reassurance?|Can a friendship survive very different opinions?
Peer Pressure|Peer pressure happens when a group influences someone's choices.|Pressure can be spoken or simply expected.|Groups can encourage helpful habits too.|A prepared answer can make refusal easier.|Friends may not notice their own influence.|Is silent pressure stronger than direct pressure?|When should loyalty give way to independence?|Can a group make good choices easier?
Teamwork|Teamwork combines different skills toward a shared goal.|Clear roles can stop work being repeated.|Disagreement can reveal a better solution.|A quiet member may hold a useful idea.|Teams need ways to check their progress.|Should teams assign roles or share every task?|How can a leader draw out quiet members?|Is a strong team better than strong individuals?
Music Genres|Music genres group songs by shared features and history.|Rhythm, instruments, and voice can shape a style.|Genres often borrow ideas from one another.|The same song can fit several labels.|Listeners connect genres with different communities.|Do genre labels help or limit music?|Should artists stay within one style?|Can you enjoy a song without its history?
Live Music|Live music happens when performers and listeners share a moment.|Musicians adjust timing in response to each other.|A venue's size changes how sound feels.|Audiences can affect a performance's energy.|Small mistakes may make a performance memorable.|Is live music better than a recording?|Should audiences sing along or listen quietly?|Does the venue matter more than the song?
Songwriting|Songwriting joins words, melody, rhythm, and structure.|A repeated chorus helps listeners remember an idea.|Writers often revise lines to fit a beat.|One song can tell a story or describe a mood.|Collaborators may contribute different musical strengths.|Should lyrics or melody lead a song?|Can simple words carry a deep meaning?|How much should a writer revise first ideas?
Film Genres|Film genres set expectations about mood and story.|A comedy often uses surprise for laughter.|A mystery holds back information to build questions.|Some films mix several genres.|Music and lighting can signal a genre.|Do genre labels reveal too much?|Can a comedy also be serious?|Which film convention would you change?
Film Making|Film making turns a planned story into moving images.|A shot choice controls what viewers notice.|Editors arrange images to shape pace.|Sound can suggest events outside the frame.|Many workers contribute to a finished scene.|Should a film show everything clearly?|Does editing matter more than acting?|Can a simple phone film tell a great story?
Fashion|Fashion reflects practical needs and cultural choices.|Clothing materials affect comfort and durability.|A style can spread when people copy it.|Uniforms can signal belonging or limit choice.|Repairing clothes can extend their use.|Should comfort matter more than style?|Do uniforms help people feel equal?|Can fashion express an idea without words?
Personal Style|Personal style is how someone chooses to present themselves.|Color and shape can express a mood.|Style can change with setting or age.|People often combine borrowed ideas in new ways.|Feeling comfortable may matter more than trends.|Should style show personality or fit a group?|Can a uniform still allow self-expression?|Who influences your choices most?
Food Culture|Food culture includes how communities grow, cook, and share meals.|Climate influences which ingredients grow locally.|Family recipes can carry memories across generations.|Table manners differ between places.|New dishes often combine several traditions.|Should recipes stay traditional or change?|Can food help strangers understand each other?|What makes a meal feel like home?
Cooking Skills|Cooking skills turn ingredients into safe, enjoyable meals.|Chopping size affects how evenly food cooks.|Heat can change texture and flavor.|Tasting helps a cook adjust seasoning.|Planning steps can save time and food.|Should schools teach everyone to cook?|Is following a recipe better than improvising?|Which skill makes the biggest difference?
Language Learning|Language learning develops understanding, speaking, reading, and writing.|Repeated conversations help words become familiar.|Mistakes can reveal what a learner needs.|Different languages organize ideas in different ways.|A useful phrase may matter before perfect grammar.|Should learners speak before they feel ready?|Which teaches more: correction or conversation?|Can films replace real language partners?
Travel Etiquette|Travel etiquette means showing care for people in a new place.|Greetings can differ between communities.|Observing before acting can prevent misunderstandings.|Asking permission matters before photographing people.|Visitors can learn a few local phrases.|Should travelers adapt to every local custom?|When is asking better than guessing?|Can respectful travel still feel spontaneous?
Local Traditions|Local traditions connect people through repeated practices.|A tradition may involve food, music, or stories.|Older and younger members can interpret it differently.|Communities may choose to change a custom.|Visitors can learn without claiming ownership.|Should traditions change with new generations?|Who gets to speak for a local custom?|Can a new tradition become meaningful quickly?
Exams|Exams are one way to show what students have learned.|A timed test measures more than knowledge alone.|Practice questions reveal gaps before an exam.|Sleep and planning can support concentration.|Different formats let students show different strengths.|Should exams decide most of a grade?|Do open-book exams test deeper thinking?|How could schools make assessment fairer?
Homework|Homework gives students practice beyond class time.|Clear tasks help students work independently.|Feedback matters more when it arrives soon.|Different homes provide different study conditions.|Practice can be useful without being long.|Should homework be optional?|Is daily practice better than one large task?|How should teachers account for home differences?
School Clubs|School clubs bring people together around shared interests.|A club can let students try new roles.|Small groups may make speaking easier.|Members learn by planning events together.|A welcoming club explains how newcomers can join.|Should schools fund every student club?|What makes a club welcoming?|Can clubs teach more than lessons?
Part-Time Jobs|Part-time jobs give students experience alongside school.|Schedules affect time for study and rest.|Workers learn to communicate with customers or teams.|Pay is only one part of job value.|Local rules may limit young workers' hours.|Should teens work during school terms?|What matters more: pay or experience?|How can a job support learning?
Future Jobs|Future jobs will change as tools and needs change.|Some roles combine skills from several subjects.|Adaptability helps people learn new tasks.|Human judgment matters even with automation.|No forecast can name every future career.|Should schools train for jobs or flexible skills?|Which human skill will stay valuable?|Can a hobby become a future job?
Entrepreneurship|Entrepreneurship starts by noticing a need and offering a solution.|A small project can test an idea.|Feedback may show a different customer need.|Costs and time matter before profit.|Teams can bring different skills to a project.|Should students try a small business?|Is solving a problem better than chasing profit?|When should a project change direction?
Money and Saving|Saving means keeping some money for a later goal.|Small regular choices can build a habit.|A clear goal makes trade-offs easier.|Unexpected needs can change a savings plan.|People have different resources and priorities.|Should young people save for fun or emergencies?|Is a shared goal easier to reach?|How can someone avoid judging others' spending?
Budgeting|Budgeting is planning how available money will be used.|A plan separates needs from optional choices.|Tracking spending shows patterns people may miss.|A budget can change when circumstances change.|Time and effort are resources too.|Should budgets include room for surprises?|Is tracking every small expense useful?|How can a budget respect personal priorities?
Volunteering|Volunteering means giving time to help without pay.|Local groups often know what help is useful.|Listening prevents helpers from assuming needs.|Shared tasks can build community connections.|Reliable attendance matters more than big promises.|Should volunteering be required at school?|How can helpers avoid taking over?|Can a small regular action beat a big event?
Public Speaking|Public speaking shares ideas with a group.|A clear opening helps listeners follow the topic.|Examples make abstract ideas easier to understand.|Pauses give speakers and listeners time to think.|Practice can reduce uncertainty without removing nerves.|Should speakers memorize every word?|Is a strong story better than many facts?|How can a speaker include shy listeners?
Study Habits|Study habits are repeated ways of preparing to learn.|Short review sessions can help memory.|Testing yourself shows what you can explain.|A quiet place can reduce distractions.|Rest helps learning continue after practice.|Should students study alone or with friends?|Which habit is hardest to keep?|Can a mistake be the best study guide?
Sleep and Learning|Sleep supports attention, memory, and daily energy.|A regular bedtime helps the body expect rest.|Bright screens can delay feeling sleepy.|Memory continues to settle after study.|Sleep needs differ between people and ages.|Should schools start later for teens?|Is rest more useful than extra revision?|How can a family protect sleep time?
Choosing Subjects|Choosing subjects shapes what students practice and explore.|Interest can make difficult work feel worthwhile.|A subject choice need not fix a career.|Advice helps when it includes the student's goals.|Trying unfamiliar subjects can reveal strengths.|Should students choose subjects early?|Is interest or practical value more important?|Who should have the strongest voice in choices?
Gap Years|A gap year is time between study stages.|People may work, travel, or volunteer then.|A plan can give the time direction.|Costs and opportunities vary between families.|Reflection can help people choose their next step.|Should everyone consider a gap year?|Is local work as valuable as travel?|What makes time away from school worthwhile?
Career Skills|Career skills help people work across many jobs.|Clear communication prevents avoidable mistakes.|Asking questions can be a strength.|Teams need people who meet commitments.|Learning new tools takes practice and feedback.|Should schools teach workplace communication?|Which matters more: reliability or creativity?|Can a hobby build career skills?
Climate Change|Climate change describes long-term shifts in Earth's climate.|Greenhouse gases hold some heat in the atmosphere.|Human activities add extra greenhouse gases.|Warming affects rainfall and habitats differently.|Communities can plan ways to reduce risks.|Should individuals or institutions act first?|How should communities choose climate priorities?|Can hopeful stories support useful action?
Renewable Energy|Renewable energy comes from sources that naturally replenish.|Solar panels turn sunlight into electricity.|Wind turbines use moving air to generate power.|Energy storage helps when supply changes.|Every energy source has land and material needs.|Should a town prioritize solar or wind?|How much should scenery affect energy plans?|Can saving energy matter as much as producing it?
Plastic Waste|Plastic waste can persist after a product is used.|Some plastic pieces break into smaller fragments.|Sorting materials can help some recycling systems.|Reuse can avoid making a new item.|Collection systems differ between communities.|Should shops reduce packaging first?|Is reuse easier than recycling?|Who should pay for waste collection?
Wildlife Conservation|Wildlife conservation works to protect animals and habitats.|Connected habitats let animals move between areas.|Local people often know an ecosystem well.|Protecting one species can help others.|Conservation plans balance several human and animal needs.|Should protection focus on species or habitats?|Who should guide a local conservation plan?|Can tourism help wildlife without disturbing it?
Urban Nature|Urban nature includes plants and animals in towns.|Street trees can provide shade.|Parks give people room to move and rest.|Buildings may offer nesting spaces for birds.|Connected green areas help some animals travel.|Should cities favor parks or street trees?|Can a small garden improve a neighborhood?|Who should care for shared green space?
Public Transport|Public transport carries groups of people on shared routes.|Buses can change routes more easily than trains.|Trains can move many people along fixed lines.|Good connections make transfers simpler.|Accessible stops help more people travel independently.|Should cities invest first in buses or trains?|What makes a journey feel reliable?|How can transport serve distant neighborhoods?
Cities of the Future|Future cities will still need homes, movement, and public space.|Compact neighborhoods can shorten some trips.|Trees can cool streets and offer shade.|Shared systems need careful maintenance.|Residents should help decide what their city needs.|Should future cities grow upward or outward?|Which public space matters most?|Can technology solve a poorly planned street?
Space Exploration|Space exploration uses missions to study places beyond Earth.|Robots can visit places too risky for people.|Spacecraft instruments measure distant objects.|Long journeys require careful supplies and communication.|Discoveries can change questions about Earth.|Should robots explore before humans?|Is learning about space worth large costs?|Which question should the next mission answer?
Mars Missions|Mars missions study a cold, rocky planet.|Robotic vehicles can examine rocks and soil.|Dust and distance make missions difficult.|Signals take time to travel between planets.|A human trip would need long-term supplies.|Should people travel to Mars soon?|What should robots study first?|How much risk is fair for exploration?
Satellites|Satellites are objects that orbit larger bodies.|Artificial satellites can relay signals across Earth.|Some satellites observe weather and land.|Orbits depend on speed and gravity.|Old satellites can become space debris.|Should satellite launches face stricter limits?|Which satellite service matters most?|Who should clean up space debris?
Inventions|Inventions are new solutions to practical or creative problems.|Many inventions improve earlier ideas.|A prototype lets makers test a design.|Unexpected failures can reveal better approaches.|People judge an invention by its effects.|Should inventors focus on simple problems?|When does an improvement become a new invention?|Is an invention useful if few people can afford it?
Medical Technology|Medical technology helps people observe, diagnose, or treat health conditions.|Imaging tools reveal structures inside a body.|Devices may support movement or hearing.|Testing helps assess safety and usefulness.|Access can differ between communities.|Should simple tools receive more funding?|How should patients help shape device design?|Can technology replace careful listening?
Food Waste|Food waste happens when edible food is discarded.|Planning meals can reduce unused ingredients.|Storage changes how long some foods last.|Leftovers can become ingredients for another meal.|Waste also uses the water and work behind food.|Should shops or households act first?|Can menus make leftover food appealing?|How can a school reduce food waste?
Sustainable Fashion|Sustainable fashion considers clothing's materials and lifespan.|Repair can keep a garment useful longer.|Secondhand clothes avoid making a new item.|Producing fabric uses water and energy.|Quality can matter more than frequent purchases.|Should people buy fewer clothes?|Is repair a creative choice or a chore?|Can fashion be both affordable and sustainable?
Water Conservation|Water conservation means using freshwater with care.|Fixing leaks prevents waste without changing routines.|Gardens can use water collected from rain.|Farms, homes, and industry all need water.|Local climate affects which solutions work.|Should households or farms change first?|What water habit is easiest to improve?|How can a community share limited water fairly?
Team Sports|Team sports combine individual effort with shared plans.|Players take different roles during a match.|Communication helps teammates respond quickly.|Practice builds trust as well as skill.|Rules give teams a fair framework.|Should everyone get equal playing time?|Is teamwork more important than winning?|How should a team welcome beginners?
Solo Sports|Solo sports focus attention on personal choices and progress.|Athletes still learn from coaches and partners.|A personal goal can differ from a competition result.|Practice includes repeating small skills.|Rest helps prevent overtraining.|Are solo sports really individual?|Should progress matter more than ranking?|How can athletes stay motivated alone?
Fitness|Fitness includes strength, movement, stamina, and recovery.|Different activities challenge the body in different ways.|Regular movement can support daily energy.|Rest gives the body time to adapt.|Enjoyment can make a habit easier to keep.|Should fitness goals focus on ability or appearance?|Is fun more important than measurement?|How can schools offer more movement choices?
Outdoor Adventures|Outdoor adventures bring people into changing natural places.|Weather can alter even a familiar route.|A map helps travelers plan and navigate.|Groups need water and suitable clothing.|Leaving little trace protects places for others.|Should adventures involve risk or comfort?|Is planning part of the fun?|How can visitors respect a natural place?
Mysteries and Clues|Mystery stories hide some information from the audience.|A clue should connect to a possible explanation.|False leads can make a story harder to solve.|Readers compare details as new facts appear.|A satisfying ending explains earlier clues.|Should readers solve the mystery before the detective?|When is a false lead unfair?|Can a mystery work without a surprise?
Unexplained Places|Unexplained places invite questions when evidence is incomplete.|A strange sound can have several causes.|Stories may change as people retell them.|Maps and records can test local claims.|Curiosity works best alongside careful checking.|Should every mystery have an answer?|When should a local story be preserved?|Can uncertainty make a place more interesting?
Optical Illusions|Optical illusions show differences between seeing and interpreting.|The brain uses context to judge shapes.|Light and shadow can change apparent size.|Two people may notice different details first.|An illusion can reveal a useful visual shortcut.|Should we trust our first impression?|Can an illusion teach us about mistakes?|Which matters more: eyesight or interpretation?
Healthy Eating|Healthy eating means choosing a varied pattern of food.|Different foods supply different nutrients.|Regular meals can support energy and concentration.|Culture and access shape food choices.|No single food decides a person's health.|Should schools teach cooking or nutrition first?|Can healthy food also be convenient?|How can advice respect different food cultures?
Stress Management|Stress management involves noticing pressure and choosing helpful responses.|A short break can create space to think.|Talking with someone can clarify a problem.|Sleep and movement may affect how stress feels.|Different strategies work for different people.|Should schools build breaks into lessons?|When is asking for help a strength?|Can some pressure improve performance?
Travel Planning|Travel planning connects routes, time, money, and interests.|A flexible schedule leaves room for surprises.|Maps help compare different journeys.|Local customs can affect daily plans.|A backup option can reduce avoidable stress.|Should trips be planned tightly or loosely?|Which matters most: price, time, or comfort?|Can getting lost improve a trip?
`.trim().split('\n');

export const teensContent = parse(teens);
