import { parseWritingBlocks } from './library-round-19-overrides';

export const cultureWriting = parseWritingBlocks(`
Friendship
L=Friends often build trust through small promises kept over time.|A friendship can survive disagreement when both people listen.|The same friend may offer company one day and honest advice the next.
H=Friendship requires room for people to change without treating every change as rejection.|Unequal effort can go unnoticed until one person feels exhausted.|Repairing a misunderstanding often matters more than winning its argument.
V=trust~Confidence in someone~I would give trust time to grow.|loyalty~Steady support~Loyalty should not require silence.|boundary~A limit about what feels acceptable~I would explain my boundary.|misunderstanding~A mistaken reading of another person's words~We could clear up that misunderstanding.|support~Help during difficulty~My friend offered support.|apology~Words taking responsibility for harm~I would make a specific apology.|reconcile~To become friendly again after conflict~I hope we can reconcile.
S=I would tell my friend why I felt hurt.|We could talk after both of us calm down.|I like friends who remember small details.|I would keep that promise.|It is okay to need time alone.|I would ask what my friend meant.
T=If our interests changed, I would look for new ways to spend time together.|Loyalty should include the courage to disagree kindly.|I would rather hear an awkward truth than a comfortable excuse.|A clear boundary might make our friendship stronger.|I wonder whether we expect too much from one person.|An apology matters more when behavior changes afterward.

Peer Pressure
L=A group can make a risky choice seem ordinary.|Someone may agree simply to avoid being left out.|A prepared answer is easier to use under pressure.
H=Pressure can come from silence and expectations as well as direct demands.|The fear of losing status may hide behind a casual joke.|One person's refusal can give others permission to speak honestly.
V=conform~To match group behavior~I do not always need to conform.|refusal~The act of saying no~My refusal can be calm.|bystander~A person watching an event~A bystander could help.|status~Standing within a group~Status should not decide my choices.|risk~A chance of harm~I would name the risk.|expectation~A belief about what someone should do~That expectation feels unfair.|exit plan~A prepared way to leave~I would make an exit plan.
S=I would say no and suggest something else.|A friend could leave with me.|I might feel nervous speaking first.|That joke does not make it safe.|I would call someone I trust.|I want a choice that feels like mine.
T=If everyone laughed, I might still say the plan made me uncomfortable.|A quiet refusal can be more effective than a long argument.|I would rather lose a little status than ignore a serious risk.|The bystander who speaks first may change the whole group.|I wonder when fitting in stops feeling like belonging.|Planning an exit before the moment could protect my judgment.

Teamwork
L=A group works better when everyone knows their part.|People can contribute different strengths to one task.|A quick check can catch confusion before it spreads.
H=Shared work fails when invisible tasks fall on the same person repeatedly.|Clear roles help only if the team can revise them.|Listening to a quieter member may uncover an idea nobody else considered.
V=role~An assigned part in group work~I would choose a clear role.|coordination~Arranging efforts to fit together~Coordination matters near a deadline.|feedback~Advice about work~I would ask for feedback.|compromise~An agreement where sides adjust~We could reach a compromise.|workload~The amount of work assigned~The workload should be fair.|deadline~The time when work is due~I would check the deadline.|contribution~A person's part of the result~Every contribution should be visible.
S=I can draw while you explain.|Let us check who has finished.|I would ask the quiet person for an idea.|We should share the hard work.|I need help with this part.|Our first plan can change.
T=If one member fell behind, I would ask what blocked them before blaming them.|A fair workload should include the work nobody sees.|I would rather adjust roles than pretend the original plan still works.|Good feedback points to a change we can actually make.|I wonder whether agreement sometimes hides a useful disagreement.|The strongest contribution may be helping another person succeed.

Music Genres
L=A genre gives listeners clues about rhythm and instruments.|Songs can cross genre lines without losing their identity.|The same melody may feel different with another beat.
H=Genre names help people find music but can also flatten local traditions.|Artists often borrow a sound and change its meaning for a new audience.|A playlist can reveal more overlap between styles than a strict label suggests.
V=beat~A regular pulse in music~The beat makes me move.|melody~A pattern of musical notes~I remember the melody.|instrumentation~The instruments chosen for a piece~I would change the instrumentation.|tempo~The speed of music~A slower tempo changes the mood.|fusion~A blend of styles~This fusion surprised me.|refrain~A repeated part of a song~I can sing the refrain.|improvisation~Music invented during performance~Improvisation can feel exciting.
S=I like the beat in this song.|That melody stays in my head.|I would mix these two styles.|The slow part feels calm.|I want to hear it on another instrument.|A label cannot tell me everything.
T=If I made a playlist, I would group songs by feeling rather than label.|A genre can guide discovery without becoming a fence.|I would rather hear an unusual fusion than another perfect copy.|The instrumentation changes how I understand the same melody.|I wonder who gets credit when a popular style borrows a local sound.|A live improvisation might challenge what I thought the genre allowed.

Live Music
L=Performers and listeners share the same moment.|A singer may change a line in response to a crowd.|A small venue can make quiet sounds feel close.
H=Live performance includes mistakes and surprises that recordings can hide.|Crowd energy can help performers, but it can also drown out detail.|The room itself changes how instruments and voices sound.
V=venue~A place where music is performed~I prefer a small venue.|acoustics~How sound behaves in a room~The acoustics make voices clear.|encore~An extra performance after applause~I hoped for an encore.|setlist~The planned order of songs~I would change the setlist.|soundcheck~A test of equipment before a show~The soundcheck took time.|audience~The people watching a performance~The audience joined in.|stage presence~How a performer connects with viewers~Her stage presence felt warm.
S=I would stand near the back.|The crowd singing together sounds fun.|I want to hear that song live.|A quiet concert could be special.|I would clap for another song.|The room might change the sound.
T=If the singer forgot a line, the audience could turn it into a shared moment.|I would rather hear a sincere imperfect show than a flawless distant one.|A thoughtful setlist can take listeners through different moods.|Good acoustics matter more to me than bright lights.|I wonder whether filming a concert makes it harder to listen.|The best encore should feel earned, not automatic.

Songwriting
L=A writer can begin with a line, a rhythm, or a tune.|Repeating a phrase can give a song its center.|Changing one word may change the feeling of a whole verse.
H=Strong lyrics leave enough space for listeners to bring their own memories.|A chorus can answer a verse or complicate it.|Writers sometimes remove their favorite line to make the song clearer.
V=verse~A section that develops a song's story~I would rewrite the verse.|chorus~A repeated central section~The chorus needs a stronger idea.|hook~A memorable musical or verbal phrase~That hook is easy to remember.|rhyme~Matching ending sounds~I would avoid a forced rhyme.|imagery~Words creating sensory pictures~The imagery makes rain feel close.|bridge~A contrasting section near the end~A bridge could shift the mood.|demo~An early recording of a song~I would make a simple demo.
S=I would start with one honest line.|The chorus should be easy to sing.|That rhyme sounds forced.|I could write about a bus ride.|A slow beat fits this mood.|I would ask a friend to listen.
T=If I wrote this song, I would let the second verse challenge the first.|A catchy hook matters less if the words feel borrowed.|I would rather keep a strange truthful line than a neat empty rhyme.|The bridge could reveal something the singer was hiding.|I wonder how much detail a listener needs to imagine the scene.|Revising a song means deciding what to leave unsaid.

Film Genres
L=A comedy invites one kind of expectation and a mystery another.|Films can surprise us by mixing familiar styles.|Music and lighting help signal what may happen next.
H=Genre conventions let filmmakers create suspense before anything occurs.|Breaking a convention works best when the audience knows the rule.|A film's label can affect who gives it a chance.
V=convention~A familiar feature of a style~I expected that convention.|suspense~Excited uncertainty about what happens next~The suspense kept me watching.|comedy~A story designed to amuse~I enjoy quiet comedy.|thriller~A tense story driven by danger~The thriller moved quickly.|soundtrack~Music used in a film~The soundtrack changed the scene.|plot twist~An unexpected story turn~That plot twist felt earned.|hybrid~A mixture of two styles~The hybrid surprised me.
S=I thought it would be funny.|The music made me nervous.|I like mysteries with fair clues.|That twist came too early.|I would watch a mixed-genre film.|The ending should fit the story.
T=If a film broke its genre's usual ending, I would want a reason within the story.|Suspense is stronger when I care about the person in danger.|I would rather be surprised by a character than by a random twist.|A familiar convention can be comforting without making a film dull.|I wonder whether genre labels shape our judgment before the first scene.|The soundtrack can tell us what to feel, or deliberately mislead us.

Film Making
L=A short scene needs choices about camera position and sound.|One action may be filmed several times from different angles.|Editing decides which moments the viewer sees.
H=Filmmaking turns separate performances and technical choices into one sequence.|A close shot can invite intimacy while a wide shot explains space.|The story may change greatly when an editor removes a few seconds.
V=shot~One continuous camera recording~I would start with a wide shot.|frame~The visible area of an image~I would move the person within the frame.|edit~A change made when assembling film~That edit makes the scene clearer.|storyboard~Drawings planning a sequence~I would sketch a storyboard.|lighting~The arrangement of light~Soft lighting fits this scene.|sound design~The planned sounds of a film~Sound design can build tension.|take~One recorded attempt at a scene~I would try another take.
S=I would film the door first.|A close shot could show fear.|We need quieter sound.|Let us try one more take.|I would cut the long pause.|The light makes it feel lonely.
T=If I directed the scene, I would hold the wide shot long enough to establish the room.|An edit should clarify whose choice matters, not merely make the scene faster.|I would rather use one strong sound than cover every pause with music.|The storyboard helps, but actors might discover a better movement.|I wonder when a camera angle tells us too much.|A small lighting change could make the same room feel welcoming or threatening.

Fashion
L=Clothes can signal a group, a job, or a mood.|A fabric's feel may matter as much as its color.|Styles often return with a different meaning.
H=Fashion is shaped by climate, labor, advertising, and social belonging.|A trend may spread quickly while the people who made it remain unseen.|Choosing what to wear can be both personal and constrained.
V=fabric~Material used to make clothes~This fabric feels light.|silhouette~The overall outline of an outfit~I like that loose silhouette.|trend~A style becoming popular~I would skip that trend.|tailoring~Adjusting clothes to fit a body~Tailoring can extend a garment's life.|secondhand~Previously owned~I would buy a secondhand jacket.|label~A brand name on clothing~The label is not my priority.|uniform~Required clothing for a group~A uniform can simplify mornings.
S=I would wear the comfortable jacket.|That color fits the weather.|I like clothes I can repair.|A uniform could save time.|I would borrow instead of buying.|The fabric matters to me.
T=If a trend changed next month, I would still wear what works for me.|A secondhand piece can have more character than a new copy.|I would rather pay for good tailoring than a visible label.|The silhouette may express confidence even when the colors are quiet.|I wonder who does the work behind a cheap garment.|Fashion feels most interesting when it leaves room for individual choice.

Personal Style
L=People choose details that make an outfit feel like theirs.|Comfort can help someone act confidently.|A favorite item may carry a memory.
H=Personal style develops through repetition and experimentation, not one purchase.|An outfit can change how someone is read before they speak.|The freedom to dress differently depends partly on a setting's rules.
V=accessory~A small item added to an outfit~I would choose one accessory.|fit~How clothing sits on the body~The fit matters more than the brand.|texture~How a surface feels or looks~I like the soft texture.|signature item~A detail someone wears often~That scarf is my signature item.|layering~Wearing pieces over one another~Layering helps in changing weather.|contrast~A strong difference between elements~The color contrast is bold.|alteration~A change made to clothing~A simple alteration improved the fit.
S=I would keep the old scarf.|These shoes feel like me.|I might try a brighter color.|Comfort helps me relax.|I would change one detail first.|That jacket reminds me of home.
T=If I borrowed a style from someone else, I would adapt it instead of copying it.|My signature item might be something ordinary with a story.|I would rather look comfortable and curious than perfectly current.|A small alteration can turn unwanted clothes into a favorite piece.|I wonder when dress rules protect people and when they restrict them.|Personal style can evolve without erasing an earlier version of ourselves.

Food Culture
L=Meals can mark celebrations or ordinary time together.|The same ingredient may be prepared differently across families.|A recipe can travel and change while keeping a link to home.
H=Food carries memories of migration, trade, and local growing conditions.|Calling one version authentic can hide the variety within a community.|Sharing a meal often communicates care without a formal speech.
V=recipe~Instructions for preparing food~My aunt changed the recipe.|ingredient~A food used in a dish~That ingredient is new to me.|seasoning~Ingredients added for flavor~I would adjust the seasoning.|staple~A food eaten regularly~Rice is a staple in many homes.|hospitality~Warm welcome offered to guests~Hospitality can begin with tea.|fusion dish~A meal combining traditions~That fusion dish tells a story.|food tradition~A repeated practice around eating~Our food tradition changes with the season.
S=I would ask how this dish is made.|My family cooks it another way.|The smell reminds me of home.|I like sharing food after school.|I would try a small bite first.|This recipe has a story.
T=If I learned a family recipe, I would ask why each step matters.|A changed dish can still carry a real connection to its origins.|I would rather hear a cook's story than argue about the only authentic version.|Hospitality may look different when time or money is tight.|I wonder which everyday meals future generations will remember.|Food can connect us without requiring everyone to like the same taste.

Cooking Skills
L=Measuring, tasting, and timing each solve a different problem.|A sharp knife can be safer than a dull one when used carefully.|Cleaning as you go makes the last step easier.
H=Cooking well depends on noticing changes in heat, texture, and smell.|A recipe gives a starting point, while judgment grows through repetition.|Learning a few basic methods makes unfamiliar ingredients less intimidating.
V=simmer~To cook gently below boiling~I would let the sauce simmer.|dice~To cut into small cubes~I would dice the onion.|season~To add flavorings~I would season it lightly.|texture~The feel of food in the mouth~The texture seems too soft.|food safety~Practices that prevent illness from food~Food safety matters with raw meat.|batch~An amount prepared at one time~I would cook a larger batch.|substitute~An ingredient used in place of another~I need a substitute for milk.
S=I would wash my hands first.|Let us taste it before adding salt.|I can cut the carrots.|The pan looks too hot.|We could save some for tomorrow.|I need help with the knife.
T=If an ingredient were missing, I would look for a substitute with a similar job.|A gentle simmer might develop flavor better than a fast boil.|I would rather learn one flexible method than memorize ten recipes.|Checking texture tells me more than staring at the clock.|I wonder which mistakes are useful and which are unsafe.|Cooking for others means asking what they can eat before choosing a menu.

Language Learning
L=A learner may understand a word long before using it aloud.|Small daily conversations offer repeated practice.|Mistakes can show what a learner is ready to notice.
H=Language grows through meaningful contact, not only rule memorization.|Confidence and accuracy can develop at different speeds.|Using a new phrase in a real exchange helps it stay memorable.
V=pronunciation~How a word sounds when spoken~I would practice the pronunciation.|fluency~Speaking with a steady flow~Fluency takes practice.|context~The situation surrounding words~Context helped me understand.|paraphrase~To express an idea in different words~I can paraphrase that sentence.|accent~A pattern of speech sounds~An accent tells part of a story.|feedback~Advice about performance~I would ask for specific feedback.|conversation partner~Someone who practices speaking with you~My conversation partner was patient.
S=I can say it another way.|Could you speak more slowly?|I learned that phrase from a friend.|I want to try it aloud.|That mistake helped me notice a rule.|Let us practice together.
T=If I forgot a word, I would paraphrase rather than stop speaking.|I would rather have a patient conversation than a perfect silent worksheet.|An accent should not be mistaken for a lack of ideas.|Useful feedback tells me what to try next time.|I wonder why some phrases stay with me after one real conversation.|Learning another language may change how I listen in my own.

Travel Etiquette
L=Visitors may need to learn how people greet one another.|Quiet behavior in one place can be polite but unfriendly elsewhere.|Watching before acting helps avoid an awkward mistake.
H=Respectful travel begins with curiosity and attention to local guidance.|A custom has a purpose that may not be obvious to an outsider.|Apologizing simply can matter more than pretending a mistake never happened.
V=greeting~A way to welcome someone~I would learn a greeting.|custom~A usual local practice~I would ask about the custom.|queue~A line of people waiting~I would join the queue.|dress code~Rules about clothing~I would check the dress code.|gesture~A movement carrying meaning~That gesture may mean something else here.|host~A person welcoming visitors~I would thank the host.|courtesy~Considerate behavior toward others~Courtesy begins with listening.
S=I would watch what others do.|Could you show me the polite way?|I will wait my turn.|I would learn a greeting first.|Sorry, I did not know.|I want to be a good guest.
T=If I misunderstood a custom, I would apologize and learn rather than defend myself.|A respectful visitor asks questions without treating local people as exhibits.|I would rather slow down than assume the rules match home.|A small gesture of courtesy can make a crowded place easier for everyone.|I wonder how hosts feel when visitors demand an explanation for every tradition.|Good etiquette leaves room for differences among people in the same place.

Local Traditions
L=A repeated celebration can bring neighbors together.|Families may keep the same tradition in different ways.|Children often learn by helping with preparations.
H=Traditions survive partly because people adapt them to new circumstances.|A public festival and a quiet household ritual can matter equally.|The person telling a tradition's story influences what others remember.
V=ritual~A repeated meaningful action~Our ritual starts at dusk.|festival~A planned public celebration~The festival brings neighbors together.|heritage~Practices passed from earlier generations~Heritage can change.|ceremony~A formal event with special actions~I would attend the ceremony.|craft~A skill for making things by hand~The craft takes patience.|oral history~Memories shared by speaking~I would share an oral history.|community~People connected by a shared place or activity~Our community helps prepare.
S=I would help decorate the room.|My family does this a little differently.|I want to learn the song.|The food reminds us of earlier years.|I would ask an elder about it.|We could invite new neighbors.
T=If a tradition changed, I would ask what the change helps people keep.|A young person's version can honor heritage without copying every detail.|I would rather hear several family memories than one official account.|The work behind a festival deserves as much attention as its performance.|I wonder which ordinary habits will become traditions later.|A local custom can welcome newcomers when people explain how to join.
`);
