export const SENTENCES = {
  easy: [
    'The cat sat on the mat.',
    'She likes to read books.',
    'He went to the store.',
    'The dog is very happy.',
    'I can see the moon.',
    'We play in the park.',
    'The bird can fly high.',
    'She has a red ball.',
    'They eat lunch together.',
    'He runs very fast.',
  ],
  medium: [
    'The children are playing in the garden.',
    'She always drinks coffee in the morning.',
    'My brother likes to play basketball.',
    'The teacher gave us a lot of homework.',
    'We are going to the beach tomorrow.',
    'He usually walks to school every day.',
    'The students finished their test on time.',
    'I want to learn how to cook.',
    'They watched a movie at the cinema.',
    'She bought a beautiful dress last weekend.',
  ],
  hard: [
    'The scientist discovered a new species of butterfly in the rainforest.',
    'Although it was raining heavily, they decided to go hiking in the mountains.',
    'The students were excited because their teacher organized a surprise field trip.',
    'My grandmother always tells us interesting stories about her childhood adventures.',
    'The restaurant on the corner serves the best Italian food in the city.',
    'If you study hard every day, you will definitely pass the final exam.',
    'The little girl carefully placed all of her toys back on the shelf.',
    'We should always try to be kind and helpful to the people around us.',
    'The old castle on the hill has been standing there for over five hundred years.',
    'After finishing their homework, the children went outside to play with their friends.',
  ],
};
