-- Founding Captains teacher beta applications and lifecycle tracking.
create table public.beta_applications (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  email_normalized text not null unique,
  first_name text not null,
  teaching_format text not null
    check (teaching_format = 'online'),
  learner_levels text[] not null default '{}',
  learner_age_band text,
  typical_class_size text,
  teaching_platform text,
  biggest_challenge text,
  contact_consent boolean not null,
  contact_consent_at timestamptz not null default now(),
  contact_consent_version text not null default 'beta-v1',
  program text not null default 'founding-captains'
    check (program = 'founding-captains'),
  status text not null default 'applied'
    check (status in ('applied', 'signed_up', 'onboarded', 'activated', 'retained')),
  cohort_state text not null default 'active'
    check (cohort_state in ('active', 'inactive', 'declined')),
  teacher_id uuid unique references public.teachers(id) on delete set null,
  landing_path text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  applied_at timestamptz not null default now(),
  signed_up_at timestamptz,
  onboarded_at timestamptz,
  activated_at timestamptz,
  retained_at timestamptz,
  last_activity_at timestamptz,
  feedback_requested_at timestamptz,
  testimonial_permission boolean,
  testimonial_requested_at timestamptz,
  testimonial_received_at timestamptz,
  classroom_use_confirmed_at timestamptz,
  analytics_signup_completed_at timestamptz,
  internal_notes text,
  updated_at timestamptz not null default now()
);

create index beta_applications_status_idx on public.beta_applications(status);
create index beta_applications_cohort_state_idx on public.beta_applications(cohort_state);
create index beta_applications_teacher_idx on public.beta_applications(teacher_id);
create index beta_applications_applied_idx on public.beta_applications(applied_at desc);
create index beta_applications_campaign_idx
  on public.beta_applications(utm_source, utm_campaign, applied_at desc);

create or replace function public.set_beta_application_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger beta_applications_set_updated_at
  before update on public.beta_applications
  for each row execute function public.set_beta_application_updated_at();

-- Deny browser access. Phase 1 reads and writes are service-role only.
alter table public.beta_applications enable row level security;

comment on table public.beta_applications is
  'Founding Captains lifecycle: applied -> signed_up -> onboarded -> activated -> retained. Automated activation is a qualifying-session proxy: an ended session owned by the teacher in a non-demo class with at least one session_participants row. Retention requires a second qualifying session on a later date. classroom_use_confirmed_at is the founder confirmation of real classroom use.';

-- Abuse attempts store a one-way salted client-IP hash, never a raw IP.
create table public.beta_application_attempts (
  id bigint generated by default as identity primary key,
  ip_hash text not null check (char_length(ip_hash) = 64),
  attempted_at timestamptz not null default now()
);

create index beta_application_attempts_ip_time_idx
  on public.beta_application_attempts(ip_hash, attempted_at desc);
create index beta_application_attempts_time_idx
  on public.beta_application_attempts(attempted_at desc);

alter table public.beta_application_attempts enable row level security;

comment on table public.beta_application_attempts is
  'Service-role-only abuse accounting for the public beta application endpoint. Contains salted SHA-256 IP hashes only; raw IP addresses are never stored. Rows older than 30 days are purged atomically when claim_beta_application_attempt next runs; without later endpoint traffic, expired rows may remain until the next claim.';

-- A single global transaction lock deliberately serializes claims. This makes
-- the global and per-IP checks exact even when many application requests arrive
-- concurrently. The table is service-role-only and the RPC is not executable by
-- browser roles.
create or replace function public.claim_beta_application_attempt(p_ip_hash text)
returns text
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_now timestamptz;
  v_ip_count bigint;
  v_global_count bigint;
begin
  if p_ip_hash is null or p_ip_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid beta application IP hash';
  end if;

  -- Every caller uses the same lock key. It is released automatically at the
  -- end of the RPC transaction, including on error or rollback.
  perform pg_advisory_xact_lock(hashtextextended('beta-application-attempts-global', 0));
  v_now := clock_timestamp();

  -- Explicit abuse-data retention: remove salted hashes after 30 days.
  delete from public.beta_application_attempts
    where attempted_at < v_now - interval '30 days';

  select count(*) into v_ip_count
  from public.beta_application_attempts
  where ip_hash = p_ip_hash
    and attempted_at >= v_now - interval '1 hour';

  if v_ip_count >= 10 then
    return 'ip_limited';
  end if;

  select count(*) into v_global_count
  from public.beta_application_attempts
  where attempted_at >= v_now - interval '1 day';

  if v_global_count >= 500 then
    return 'global_limited';
  end if;

  insert into public.beta_application_attempts(ip_hash, attempted_at)
  values (p_ip_hash, v_now);

  return 'allowed';
end;
$$;

revoke all on function public.claim_beta_application_attempt(text) from public;
revoke all on function public.claim_beta_application_attempt(text) from anon;
revoke all on function public.claim_beta_application_attempt(text) from authenticated;
grant execute on function public.claim_beta_application_attempt(text) to service_role;

comment on function public.claim_beta_application_attempt(text) is
  'On each claim, atomically purges beta abuse hashes older than 30 days, enforces 10 attempts per salted IP hash per hour and 500 attempts globally per day, and records an allowed attempt.';
